"""Phase 28 — Godot 4 project emitter.

Same GameSpec, second engine target: emits a complete Godot 4.3 project
(project.godot + main.tscn + GDScript templates + copied GLBs). Godot is MIT —
the open-source desktop/mobile engine of record (Unreal stays an opt-in
adapter because of its proprietary EULA). Deterministic templates, no LLM.

Validated headlessly: `godot --headless --path <proj> --import` must exit 0.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from .spec import GameSpec

_SKY = {
    "day":      ("0.53, 0.71, 0.88", 1.0),
    "sunset":   ("0.91, 0.60, 0.42", 0.7),
    "night":    ("0.05, 0.09, 0.15", 0.15),
    "overcast": ("0.60, 0.64, 0.68", 0.6),
}

_PROJECT = """; Engine configuration — generated by Fantasy Studio (Phase 28)
config_version=5

[application]
config/name="__TITLE__"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.3")

[rendering]
renderer/rendering_method="mobile"
"""

_PLAYER_GD = """extends CharacterBody3D
# Fantasy Studio player controller — generated, deterministic template.
const WALK := __WALK__
const RUN := __RUN__
var yaw := 0.0
var pitch := 0.35

func _ready() -> void:
\tInput.mouse_mode = Input.MOUSE_MODE_CAPTURED

func _unhandled_input(event: InputEvent) -> void:
\tif event is InputEventMouseMotion:
\t\tyaw -= event.relative.x * 0.004
\t\tpitch = clampf(pitch + event.relative.y * 0.003, 0.05, 1.2)
\tif event.is_action_pressed("ui_cancel"):
\t\tInput.mouse_mode = Input.MOUSE_MODE_VISIBLE

func _physics_process(delta: float) -> void:
\tvar input := Vector3.ZERO
\tinput.x = Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left")
\tinput.z = Input.get_action_strength("ui_down") - Input.get_action_strength("ui_up")
\tvar speed := RUN if Input.is_key_pressed(KEY_SHIFT) else WALK
\tvar dir := (Basis(Vector3.UP, yaw) * input).normalized()
\tif not is_on_floor():
\t\tvelocity.y -= 9.81 * delta
\tvelocity.x = dir.x * speed
\tvelocity.z = dir.z * speed
\tif dir.length() > 0.1:
\t\t$Model.rotation.y = lerp_angle($Model.rotation.y, atan2(dir.x, dir.z) + PI, 10.0 * delta)
\tmove_and_slide()
\t# third-person camera on a yaw/pitch arm
\t$Arm.rotation = Vector3(-pitch, yaw, 0)
"""

_NPC_GD = """extends Node3D
# Fantasy Studio NPC — wander/follow template AI.
@export var behavior := "__BEHAVIOR__"
@export var speed := __SPEED__
var _target := Vector3.ZERO
var _have_target := false

func _process(delta: float) -> void:
\tvar player := get_tree().get_first_node_in_group("player")
\tvar tgt := Vector3.INF
\tif behavior == "follow" and player:
\t\tif position.distance_to(player.position) > 2.6:
\t\t\ttgt = player.position
\telif behavior == "wander":
\t\tif not _have_target or position.distance_to(_target) < 0.6:
\t\t\t_target = Vector3(randf_range(-__ROAM__, __ROAM__), 0, randf_range(-__ROAM__, __ROAM__))
\t\t\t_have_target = true
\t\ttgt = _target
\tif tgt != Vector3.INF:
\t\tvar dir := (tgt - position); dir.y = 0
\t\tif dir.length() > 0.1:
\t\t\tdir = dir.normalized()
\t\t\trotation.y = lerp_angle(rotation.y, atan2(dir.x, dir.z), 6.0 * delta)
\t\t\tposition += dir * speed * delta
"""


def _tscn(spec: GameSpec, assets: list[tuple[str, str]]) -> str:
    """Build main.tscn: env + sun + ground + player(+camera) + NPCs + scatter."""
    sky_rgb, sun_e = _SKY.get(spec.world.sky, _SKY["day"])
    size = spec.world.size_m
    g = spec.world.ground_color
    cap_h = max(spec.player.height_m - 0.7, 0.3)

    ext = ['[ext_resource type="Script" path="res://player.gd" id="pgd"]',
           '[ext_resource type="Script" path="res://npc.gd" id="ngd"]']
    for i, (res_id, fname) in enumerate(assets):
        ext.append(f'[ext_resource type="PackedScene" path="res://assets/{fname}" id="{res_id}"]')

    subs = f"""[sub_resource type="ProceduralSkyMaterial" id="skym"]
sky_top_color = Color({sky_rgb}, 1)
sky_horizon_color = Color({sky_rgb}, 1)

[sub_resource type="Sky" id="sky"]
sky_material = SubResource("skym")

[sub_resource type="Environment" id="env"]
background_mode = 2
sky = SubResource("sky")

[sub_resource type="PlaneMesh" id="gmesh"]
size = Vector2({size}, {size})

[sub_resource type="StandardMaterial3D" id="gmat"]
albedo_color = Color({g[0]}, {g[1]}, {g[2]}, 1)
roughness = 1.0

[sub_resource type="BoxShape3D" id="gshape"]
size = Vector3({size}, 0.1, {size})

[sub_resource type="CapsuleShape3D" id="pcap"]
height = {spec.player.height_m:.2f}
radius = 0.35
"""
    nodes = [f'[node name="Main" type="Node3D"]',
             '',
             '[node name="Env" type="WorldEnvironment" parent="."]',
             'environment = SubResource("env")',
             '',
             '[node name="Sun" type="DirectionalLight3D" parent="."]',
             'transform = Transform3D(0.866, -0.354, 0.354, 0, 0.707, 0.707, -0.5, -0.612, 0.612, 0, 25, 0)',
             f'light_energy = {sun_e}',
             'shadow_enabled = true',
             '',
             '[node name="Ground" type="StaticBody3D" parent="."]',
             '[node name="GMesh" type="MeshInstance3D" parent="Ground"]',
             'mesh = SubResource("gmesh")',
             'surface_material_override/0 = SubResource("gmat")',
             '[node name="GCol" type="CollisionShape3D" parent="Ground"]',
             'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.05, 0)',
             'shape = SubResource("gshape")',
             '',
             '[node name="Player" type="CharacterBody3D" parent="." groups=["player"]]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {spec.player.height_m/2:.2f}, 0)',
             'script = ExtResource("pgd")',
             '[node name="PCol" type="CollisionShape3D" parent="Player"]',
             'shape = SubResource("pcap")',
             f'[node name="Model" parent="Player" instance=ExtResource("player_glb")]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {-spec.player.height_m/2:.2f}, 0)',
             '[node name="Arm" type="SpringArm3D" parent="Player"]',
             f'spring_length = {spec.camera.distance_m:.1f}',
             '[node name="Cam" type="Camera3D" parent="Player/Arm"]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {spec.camera.height_m*0.4:.2f}, {spec.camera.distance_m:.1f})',
             f'fov = {spec.camera.fov_deg:.0f}']

    # NPCs (one node per instance) + scatter (deterministic seeded ring)
    import random
    rng = random.Random(spec.seed)
    ni = 0
    for ent, (res_id, _f) in zip(spec.entities, assets[1:1 + len(spec.entities)]):
        for c in range(ent.count):
            ni += 1
            x = (rng.random() - 0.5) * size * 0.3
            z = (rng.random() - 0.5) * size * 0.3
            nodes += [f'[node name="NPC{ni}" type="Node3D" parent="." instance=ExtResource("{res_id}")]',
                      f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {x:.2f}, 0, {z:.2f})',
                      'script = ExtResource("ngd")',
                      f'behavior = "{ent.behavior}"',
                      f'speed = {ent.speed:.2f}']
    si = 0
    scatter_assets = assets[1 + len(spec.entities):]
    for sct, (res_id, _f) in zip(spec.world.scatter, scatter_assets):
        for c in range(sct.count):
            si += 1
            import math
            ang = rng.random() * 6.283
            dist = 11.0 + rng.random() * (size * 0.4 - 11.0)
            s = 1 + (rng.random() - 0.5) * 2 * sct.scale_jitter
            x, z = math.cos(ang) * dist, math.sin(ang) * dist
            nodes += [f'[node name="Prop{si}" parent="." instance=ExtResource("{res_id}")]',
                      f'transform = Transform3D({s:.2f}, 0, 0, 0, {s:.2f}, 0, 0, 0, {s:.2f}, {x:.2f}, 0, {z:.2f})']

    load_steps = len(ext) + 8
    header = f"[gd_scene load_steps={load_steps} format=3]\n"
    return header + "\n" + "\n".join(ext) + "\n\n" + subs + "\n" + "\n".join(nodes) + "\n"


def export_godot_game(spec: GameSpec, out_dir: str | Path, verbose: bool = True) -> Path:
    """Emit a Godot 4 project. Returns the project dir."""
    proj = Path(out_dir) / "godot"
    assets_dir = proj / "assets"
    if assets_dir.exists():
        shutil.rmtree(assets_dir)
    assets_dir.mkdir(parents=True, exist_ok=True)

    # copy assets; assign ext_resource ids: player first, then entities, then scatter
    pairs: list[tuple[str, str]] = []

    def bring(src: str, res_id: str) -> None:
        srcp = Path(src)
        if not srcp.exists():
            raise FileNotFoundError(f"asset missing: {src}")
        shutil.copy2(srcp, assets_dir / srcp.name)
        pairs.append((res_id, srcp.name))

    bring(spec.player.asset, "player_glb")
    for i, ent in enumerate(spec.entities):
        bring(ent.asset, f"ent{i}")
    for i, sct in enumerate(spec.world.scatter):
        bring(sct.asset, f"sct{i}")

    (proj / "project.godot").write_text(
        _PROJECT.replace("__TITLE__", spec.title.replace('"', "'")), encoding="utf-8")
    (proj / "player.gd").write_text(
        _PLAYER_GD.replace("__WALK__", f"{spec.player.walk_speed:.2f}")
                  .replace("__RUN__", f"{spec.player.run_speed:.2f}"), encoding="utf-8")
    (proj / "npc.gd").write_text(
        _NPC_GD.replace("__BEHAVIOR__", "wander")
               .replace("__SPEED__", "1.5")
               .replace("__ROAM__", f"{spec.world.size_m * 0.3:.1f}"), encoding="utf-8")
    (proj / "main.tscn").write_text(_tscn(spec, pairs), encoding="utf-8")
    (proj / "icon.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">'
        '<rect width="128" height="128" fill="#1a2b4a"/></svg>', encoding="utf-8")

    if verbose:
        n = sum(1 for _ in proj.rglob("*") if _.is_file())
        print(f"[game] godot project '{spec.title}' -> {proj} ({n} files)")
    return proj
