"""Phase 28+ — Godot 4 project emitter (ENRICHED 2026-07-07).

Same GameSpec, second engine target: emits a complete Godot 4.3 project that
is a real GAME, not a diorama — missions with a quest log, collectibles,
hostile AI with player health and win/lose, survive waves, jump, the
narrative intro overlay, and a step-by-step STEAM_GUIDE.md so users know
exactly how to go from export to a store page. Godot is MIT — the
open-source desktop/mobile engine of record.

Deterministic templates, no LLM. Validated structurally at export
(project.godot format, scene resource ids, script placeholders resolved);
full headless validation (`godot --headless --import`) runs wherever a Godot
binary exists.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from .spec import GameSpec

_SKY = {
    "day":      ("0.53, 0.71, 0.88", 1.0),
    "sunset":   ("0.91, 0.60, 0.42", 0.7),
    "night":    ("0.05, 0.09, 0.15", 0.15),
    "overcast": ("0.60, 0.64, 0.68", 0.6),
    "mars":     ("0.85, 0.60, 0.40", 0.8),
    "space":    ("0.02, 0.03, 0.05", 1.2),
    "dusk":     ("0.23, 0.23, 0.37", 0.35),
}

_PROJECT = """; Engine configuration — generated by Fantasy Studio
config_version=5

[application]
config/name="__TITLE__"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.3")

[rendering]
renderer/rendering_method="mobile"
"""

_PLAYER_GD = """extends CharacterBody3D
# Fantasy Studio player controller — generated, deterministic template.
# WASD move · Space jump · Shift run · F attack · mouse look · Esc frees mouse
const WALK := __WALK__
const RUN := __RUN__
const VIEW := "__VIEW__"    # 3d / topdown / side — same presets as the web runtime
var yaw := 0.0
var pitch := 0.35

func _ready() -> void:
\tif VIEW == "3d":
\t\tInput.mouse_mode = Input.MOUSE_MODE_CAPTURED
\telse:
\t\t# 2D views: fixed orthographic camera, mouse stays free
\t\tvar cam: Camera3D = $Arm/Cam
\t\tcam.projection = Camera3D.PROJECTION_ORTHOGONAL
\t\tcam.size = 18.0 if VIEW == "side" else 32.0
\t\tif VIEW == "topdown":
\t\t\t$Arm.rotation = Vector3(-1.55, 0, 0)
\t\t\t$Arm.spring_length = 46.0
\t\telse:
\t\t\t$Arm.rotation = Vector3(-0.05, 0, 0)
\t\t\t$Arm.spring_length = 42.0

func _unhandled_input(event: InputEvent) -> void:
\tif VIEW == "3d" and event is InputEventMouseMotion:
\t\tyaw -= event.relative.x * 0.004
\t\tpitch = clampf(pitch + event.relative.y * 0.003, 0.05, 1.2)
\tif event.is_action_pressed("ui_cancel"):
\t\tInput.mouse_mode = Input.MOUSE_MODE_VISIBLE
\tif event is InputEventKey and event.pressed and event.keycode == KEY_F:
\t\t_attack()

func _attack() -> void:
\tvar m := get_node_or_null("/root/Main/Mission")
\tfor n in get_tree().get_nodes_in_group("hostile"):
\t\tif n.has_method("take_hit") and global_position.distance_to(n.global_position) < 2.4:
\t\t\tn.take_hit(1)
\tif m: m.flash_attack()

func _physics_process(delta: float) -> void:
\tvar input := Vector3.ZERO
\tinput.x = Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left")
\tinput.z = Input.get_action_strength("ui_down") - Input.get_action_strength("ui_up")
\tif VIEW == "side":
\t\tinput.z = 0.0    # side-scroller: one lane, A/D run it
\tvar speed := RUN if Input.is_key_pressed(KEY_SHIFT) else WALK
\tvar cam_yaw := yaw if VIEW == "3d" else 0.0
\tvar dir := (Basis(Vector3.UP, cam_yaw) * input).normalized()
\tif is_on_floor():
\t\tif Input.is_key_pressed(KEY_SPACE):
\t\t\tvelocity.y = 5.6
\telse:
\t\tvelocity.y -= 9.81 * delta
\tvelocity.x = dir.x * speed
\tvelocity.z = dir.z * speed
\tif VIEW == "side":
\t\tvelocity.z = (0.0 - position.z) * 6.0   # hold the gameplay lane
\tif dir.length() > 0.1:
\t\t$Model.rotation.y = lerp_angle($Model.rotation.y, atan2(dir.x, dir.z) + PI, 10.0 * delta)
\tmove_and_slide()
\t# third-person camera on a yaw/pitch arm (2D views keep the fixed arm)
\tif VIEW == "3d":
\t\t$Arm.rotation = Vector3(-pitch, yaw, 0)
"""

_NPC_GD = """extends Node3D
# Fantasy Studio NPC — wander/follow/hostile template AI.
@export var behavior := "wander"
@export var speed := 1.5
@export var roam := 20.0
@export var hp := 3
var _target := Vector3.ZERO
var _have_target := false
var _atk_cd := 0.0
var dead := false

func take_hit(dmg: int) -> void:
\tif dead: return
\thp -= dmg
\tif hp <= 0:
\t\tdead = true
\t\tvar m := get_node_or_null("/root/Main/Mission")
\t\tif m: m.enemy_killed()
\t\tqueue_free()

func _process(delta: float) -> void:
\tif dead: return
\tvar player := get_tree().get_first_node_in_group("player")
\tvar mission := get_node_or_null("/root/Main/Mission")
\tvar tgt := Vector3.INF
\tif behavior == "hostile" and player:
\t\tvar d := position.distance_to(player.position)
\t\tif mission and mission.is_player_safe(player.position) and (d < 14.0 or not mission.nearest_safe(position).is_empty()):
\t\t\t# safe_zone rule: the firelight holds them at the edge of the glow
\t\t\tvar s: Dictionary = mission.nearest_safe(player.position)
\t\t\tif not s.is_empty():
\t\t\t\tvar away := Vector2(position.x - s.x, position.z - s.z).normalized()
\t\t\t\ttgt = Vector3(s.x + away.x * (s.r + 3.0), 0, s.z + away.y * (s.r + 3.0))
\t\telif d < 14.0 and d > 1.7:
\t\t\ttgt = player.position
\t\telif d <= 1.7:
\t\t\t_atk_cd -= delta
\t\t\tif _atk_cd <= 0.0:
\t\t\t\t_atk_cd = 1.2
\t\t\t\tvar m := get_node_or_null("/root/Main/Mission")
\t\t\t\tif m: m.player_hit(1)
\telif behavior == "follow" and player:
\t\tif position.distance_to(player.position) > 2.6:
\t\t\ttgt = player.position
\tif tgt == Vector3.INF and behavior != "follow":
\t\tif not _have_target or position.distance_to(_target) < 0.6:
\t\t\t_target = Vector3(randf_range(-roam, roam), 0, randf_range(-roam, roam))
\t\t\t_have_target = true
\t\ttgt = _target
\tif tgt != Vector3.INF:
\t\tvar dir := (tgt - position); dir.y = 0
\t\tif dir.length() > 0.1:
\t\t\tdir = dir.normalized()
\t\t\trotation.y = lerp_angle(rotation.y, atan2(dir.x, dir.z), 6.0 * delta)
\t\t\tposition += dir * speed * delta
\tif mission: mission.push_out(self)   # blocks_enemies rule: fences FENCE
"""

_MISSION_GD = """extends Node
# Fantasy Studio mission system — ordered steps (collect/defeat/reach/survive),
# quest log, hearts, narrative intro, win/lose overlays. UI built in code so
# the scene file stays simple. Same verbs as the web runtime.
@export var steps_json := "[]"
@export var placed_json := "[]"
@export var intro := ""
@export var win_text := "Mission complete!"
@export var reward := ""
@export var player_hp := 5
@export var world_size := 120.0
@export var seed := 7

var steps: Array = []
var idx := -1
var kills := 0
var got := 0
var hp := 5
var done := false
var started := false
var _t0 := 0.0
var _wave := 0
var _rng := RandomNumberGenerator.new()
var _quest: Label
var _obj: Label
var _hearts: Label
var _prompt: Label
var _overlay: Control
var _beacon: Node3D
# placed-item RULES — honored exactly like the web runtime
var safe_zones: Array = []      # [{x, z, r}]
var blockers: Array = []        # [{x, z, r}]
var hurt_zones: Array = []      # [{x, z, r}]
var readables: Array = []       # [{x, z, label, text}]
var _reading := false
var _hurt_cd := 0.0

func _ready() -> void:
\t_rng.seed = seed
\thp = player_hp
\tsteps = JSON.parse_string(steps_json)
\tif steps == null: steps = []
\t_build_ui()
\t_spawn_placed()
\t_show_intro()

func _spawn_placed() -> void:
\tvar items = JSON.parse_string(placed_json)
\tif items == null: return
\tvar root := get_tree().root.get_node("Main")
\tfor it in items:
\t\tvar x: float = it.get("x", 0.0)
\t\tvar z: float = it.get("z", 0.0)
\t\tvar kind: String = it.get("kind", "beacon")
\t\tvar body := StaticBody3D.new()
\t\tbody.position = Vector3(x, 0, z)
\t\tbody.rotation.y = deg_to_rad(float(it.get("yaw_deg", 0.0)))
\t\tvar h := _prop_mesh(kind, body)
\t\tif bool(it.get("collide", true)):
\t\t\tvar col := CollisionShape3D.new()
\t\t\tvar sh := BoxShape3D.new()
\t\t\tsh.size = Vector3(maxf(h * 0.8, 0.6), h, maxf(h * 0.8, 0.6))
\t\t\tcol.shape = sh
\t\t\tcol.position.y = h / 2.0
\t\t\tbody.add_child(col)
\t\troot.add_child(body)
\t\tvar rules: Array = it.get("rules", [])
\t\tif rules.has("safe_zone"):
\t\t\tsafe_zones.append({"x": x, "z": z, "r": 6.0})
\t\tif rules.has("blocks_enemies"):
\t\t\tblockers.append({"x": x, "z": z, "r": maxf(h * 0.6, 0.9)})
\t\tif rules.has("hurts_touch"):
\t\t\thurt_zones.append({"x": x, "z": z, "r": maxf(h * 0.7, 1.2)})
\t\tvar txt: String = str(it.get("interact", "")) if it.get("interact") != null else ""
\t\tif txt != "":
\t\t\treadables.append({"x": x, "z": z,
\t\t\t\t"label": it.get("name", kind), "text": txt})

func _prop_mesh(kind: String, parent: Node3D) -> float:
\t# simplified primitives of the web runtime's procedural props
\tvar add := func(mesh: Mesh, col: Color, pos: Vector3, emiss: float = 0.0) -> void:
\t\tvar mi := MeshInstance3D.new()
\t\tmi.mesh = mesh
\t\tvar mat := StandardMaterial3D.new()
\t\tmat.albedo_color = col
\t\tif emiss > 0.0:
\t\t\tmat.emission_enabled = true
\t\t\tmat.emission = col
\t\t\tmat.emission_energy_multiplier = emiss
\t\tmi.material_override = mat
\t\tmi.position = pos
\t\tparent.add_child(mi)
\tif kind == "fence":
\t\tvar post := BoxMesh.new(); post.size = Vector3(0.13, 1.05, 0.13)
\t\tadd.call(post, Color(0.42, 0.29, 0.18), Vector3(-0.95, 0.52, 0))
\t\tadd.call(post, Color(0.42, 0.29, 0.18), Vector3(0.95, 0.52, 0))
\t\tvar rail := BoxMesh.new(); rail.size = Vector3(2.05, 0.11, 0.09)
\t\tadd.call(rail, Color(0.49, 0.34, 0.21), Vector3(0, 0.86, 0))
\t\tadd.call(rail, Color(0.49, 0.34, 0.21), Vector3(0, 0.46, 0))
\t\treturn 1.1
\tif kind == "campfire":
\t\tvar log := CylinderMesh.new(); log.top_radius = 0.07; log.bottom_radius = 0.07; log.height = 0.95
\t\tadd.call(log, Color(0.36, 0.24, 0.15), Vector3(0, 0.09, 0))
\t\tvar flame := CylinderMesh.new(); flame.top_radius = 0.0; flame.bottom_radius = 0.26; flame.height = 0.6
\t\tadd.call(flame, Color(1.0, 0.48, 0.16), Vector3(0, 0.42, 0), 2.5)
\t\tvar li := OmniLight3D.new(); li.light_color = Color(1.0, 0.6, 0.3)
\t\tli.omni_range = 8.0; li.position.y = 0.8; parent.add_child(li)
\t\treturn 0.85
\tif kind == "building":
\t\tvar wall := BoxMesh.new(); wall.size = Vector3(4.4, 3.3, 3.7)
\t\tadd.call(wall, Color(0.6, 0.56, 0.49), Vector3(0, 1.65, 0))
\t\tvar roof := PrismMesh.new(); roof.size = Vector3(4.8, 1.9, 4.0)
\t\tadd.call(roof, Color(0.42, 0.27, 0.22), Vector3(0, 4.25, 0))
\t\tvar win := BoxMesh.new(); win.size = Vector3(0.7, 0.7, 0.06)
\t\tadd.call(win, Color(1.0, 0.85, 0.54), Vector3(-1.35, 1.9, 1.87), 1.4)
\t\tadd.call(win, Color(1.0, 0.85, 0.54), Vector3(1.35, 1.9, 1.87), 1.4)
\t\treturn 5.2
\tif kind == "rock":
\t\tvar r := SphereMesh.new(); r.radius = 0.7; r.height = 0.9
\t\tadd.call(r, Color(0.55, 0.55, 0.57), Vector3(0, 0.45, 0))
\t\treturn 1.0
\tif kind == "sign":
\t\tvar postm := CylinderMesh.new(); postm.top_radius = 0.05; postm.bottom_radius = 0.07; postm.height = 1.15
\t\tadd.call(postm, Color(0.42, 0.29, 0.18), Vector3(0, 0.57, 0))
\t\tvar board := BoxMesh.new(); board.size = Vector3(0.95, 0.55, 0.07)
\t\tadd.call(board, Color(0.66, 0.52, 0.36), Vector3(0, 1.25, 0), 0.25)
\t\treturn 1.55
\tif kind == "chest":
\t\tvar base := BoxMesh.new(); base.size = Vector3(0.85, 0.45, 0.55)
\t\tadd.call(base, Color(0.42, 0.29, 0.18), Vector3(0, 0.22, 0))
\t\tvar band := BoxMesh.new(); band.size = Vector3(0.87, 0.09, 0.57)
\t\tadd.call(band, Color(0.85, 0.64, 0.25), Vector3(0, 0.32, 0), 0.5)
\t\treturn 0.72
\tif kind == "book":
\t\tvar ped := CylinderMesh.new(); ped.top_radius = 0.3; ped.bottom_radius = 0.36; ped.height = 0.5
\t\tadd.call(ped, Color(0.44, 0.42, 0.47), Vector3(0, 0.25, 0))
\t\tvar pages := BoxMesh.new(); pages.size = Vector3(0.6, 0.06, 0.44)
\t\tadd.call(pages, Color(0.96, 0.93, 0.85), Vector3(0, 0.56, 0), 0.35)
\t\treturn 0.75
\t# default / beacon: glowing pillar
\tvar pil := CylinderMesh.new(); pil.top_radius = 0.12; pil.bottom_radius = 0.19; pil.height = 2.2
\tadd.call(pil, Color(0.73, 0.63, 1.0), Vector3(0, 1.35, 0), 2.2)
\treturn 2.5

func is_player_safe(pos: Vector3) -> bool:
\tfor s in safe_zones:
\t\tif Vector2(pos.x - s.x, pos.z - s.z).length() < s.r:
\t\t\treturn true
\treturn false

func nearest_safe(pos: Vector3) -> Dictionary:
\tfor s in safe_zones:
\t\tif Vector2(pos.x - s.x, pos.z - s.z).length() < s.r:
\t\t\treturn s
\treturn {}

func push_out(n: Node3D) -> void:
\tfor b in blockers:
\t\tvar d := Vector2(n.position.x - b.x, n.position.z - b.z)
\t\tif d.length() < b.r:
\t\t\tvar k: Vector2 = d.normalized() * (b.r + 0.02) if d.length() > 0.001 else Vector2(b.r, 0)
\t\t\tn.position.x = b.x + k.x
\t\t\tn.position.z = b.z + k.y

func _build_ui() -> void:
\tvar cl := CanvasLayer.new(); add_child(cl)
\t_quest = Label.new(); _quest.position = Vector2(16, 16); cl.add_child(_quest)
\t_obj = Label.new(); _obj.position = Vector2(16, 44)
\t_obj.add_theme_color_override("font_color", Color(1.0, 0.85, 0.4)); cl.add_child(_obj)
\t_hearts = Label.new(); _hearts.position = Vector2(16, 72)
\t_hearts.add_theme_color_override("font_color", Color(1.0, 0.45, 0.5)); cl.add_child(_hearts)
\t_prompt = Label.new(); _prompt.position = Vector2(16, 100)
\t_prompt.add_theme_color_override("font_color", Color(0.9, 0.88, 1.0)); cl.add_child(_prompt)
\t_overlay = Control.new(); _overlay.set_anchors_preset(Control.PRESET_FULL_RECT); cl.add_child(_overlay)

func _unhandled_input(event: InputEvent) -> void:
\tif event is InputEventKey and event.pressed and event.keycode == KEY_E:
\t\tif _reading:
\t\t\t_reading = false
\t\t\t_overlay.visible = false
\t\t\treturn
\t\tvar player := get_tree().get_first_node_in_group("player")
\t\tif player == null: return
\t\tfor r in readables:
\t\t\tif Vector2(player.position.x - r.x, player.position.z - r.z).length() < 2.4:
\t\t\t\t_reading = true
\t\t\t\t_center_panel([str(r.label).to_upper(), str(r.text), "E to close"],
\t\t\t\t\t"Close", func(): _reading = false; _overlay.visible = false)
\t\t\t\treturn

func _center_panel(lines: Array, btn_text: String, on_press: Callable) -> void:
\tfor c in _overlay.get_children(): c.queue_free()
\tvar box := VBoxContainer.new()
\tbox.set_anchors_preset(Control.PRESET_CENTER)
\tbox.alignment = BoxContainer.ALIGNMENT_CENTER
\t_overlay.add_child(box)
\tfor l in lines:
\t\tvar lab := Label.new(); lab.text = l
\t\tlab.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
\t\tbox.add_child(lab)
\tvar b := Button.new(); b.text = btn_text; b.pressed.connect(on_press)
\tbox.add_child(b)
\t_overlay.visible = true

func _show_intro() -> void:
\tvar lines := [get_tree().root.get_node("Main").name]
\tif intro != "": lines.append(intro)
\tlines.append("WASD move - Space jump - Shift run - F attack")
\tlines.append("Made with Fantasy Studio")
\t_center_panel(lines, "START", _start)

func _start() -> void:
\t_overlay.visible = false
\tstarted = true
\tInput.mouse_mode = Input.MOUSE_MODE_CAPTURED
\t_advance()

func _advance() -> void:
\tidx += 1
\tif idx >= steps.size():
\t\t_win()
\t\treturn
\tvar st: Dictionary = steps[idx]
\tif st.get("kind") == "collect":
\t\tgot = 0
\t\t_spawn_collectibles(int(st.get("count", 5)))
\telif st.get("kind") == "defeat":
\t\tkills = 0
\telif st.get("kind") == "survive":
\t\t_t0 = Time.get_ticks_msec() / 1000.0
\t\t_wave = 0
\telif st.get("kind") == "reach":
\t\t_spawn_beacon()
\t_render_quest()

func _spawn_collectibles(n: int) -> void:
\tvar root := get_tree().root.get_node("Main")
\tfor i in range(n):
\t\tvar area := Area3D.new()
\t\tvar mesh := MeshInstance3D.new()
\t\tvar sm := SphereMesh.new(); sm.radius = 0.16; sm.height = 0.32
\t\tmesh.mesh = sm
\t\tvar mat := StandardMaterial3D.new()
\t\tmat.emission_enabled = true
\t\tmat.emission = Color(1.0, 0.83, 0.3)
\t\tmat.emission_energy_multiplier = 2.5
\t\tmesh.material_override = mat
\t\tarea.add_child(mesh)
\t\tvar col := CollisionShape3D.new()
\t\tvar sh := SphereShape3D.new(); sh.radius = 1.4
\t\tcol.shape = sh
\t\tarea.add_child(col)
\t\tvar ang := _rng.randf() * TAU
\t\tvar dist := 6.0 + _rng.randf() * world_size * 0.3
\t\tarea.position = Vector3(cos(ang) * dist, 1.0, sin(ang) * dist)
\t\tarea.body_entered.connect(_on_pickup.bind(area))
\t\troot.add_child(area)

func _on_pickup(body: Node3D, area: Area3D) -> void:
\tif done or not body.is_in_group("player"): return
\tarea.queue_free()
\tgot += 1
\t_render_quest()
\tvar st: Dictionary = steps[idx] if idx < steps.size() else {}
\tif st.get("kind") == "collect" and got >= int(st.get("count", 5)):
\t\t_advance()

func _spawn_beacon() -> void:
\tif _beacon: return
\tvar root := get_tree().root.get_node("Main")
\t_beacon = MeshInstance3D.new()
\tvar cm := CylinderMesh.new()
\tcm.top_radius = 1.2; cm.bottom_radius = 1.2; cm.height = 40.0
\t_beacon.mesh = cm
\tvar mat := StandardMaterial3D.new()
\tmat.emission_enabled = true
\tmat.emission = Color(0.62, 0.5, 1.0)
\tmat.albedo_color = Color(0.62, 0.5, 1.0, 0.35)
\tmat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
\t_beacon.material_override = mat
\tvar ang := _rng.randf() * TAU
\tvar dist := world_size * 0.34
\t_beacon.position = Vector3(cos(ang) * dist, 20.0, sin(ang) * dist)
\troot.add_child(_beacon)

func enemy_killed() -> void:
\tkills += 1
\t_render_quest()
\tvar st: Dictionary = steps[idx] if idx >= 0 and idx < steps.size() else {}
\tif st.get("kind") == "defeat" and kills >= int(st.get("count", 3)):
\t\t_advance()

func player_hit(dmg: int) -> void:
\tif done or not started: return
\thp -= dmg
\t_render_quest()
\tif hp <= 0:
\t\tdone = true
\t\tInput.mouse_mode = Input.MOUSE_MODE_VISIBLE
\t\t_center_panel(["You were defeated"], "Retry",
\t\t\tfunc(): get_tree().reload_current_scene())

func flash_attack() -> void:
\tpass  # hook for attack feedback (sound/vfx) — extend freely

func _wake_wave(n: int) -> void:
\tvar player := get_tree().get_first_node_in_group("player")
\tif player == null: return
\tvar hostiles := get_tree().get_nodes_in_group("hostile")
\tif hostiles.is_empty(): return
\tfor i in range(n):
\t\tvar src: Node3D = hostiles[i % hostiles.size()]
\t\tvar c := src.duplicate()
\t\tvar ang := _rng.randf() * TAU
\t\tc.position = player.position + Vector3(cos(ang) * 18.0, 0, sin(ang) * 18.0)
\t\tget_tree().root.get_node("Main").add_child(c)

func _process(_delta: float) -> void:
\tif done or not started: return
\tvar pl := get_tree().get_first_node_in_group("player")
\tif pl:
\t\t# readable prompt (books/signs placed with text)
\t\tvar near := ""
\t\tfor r in readables:
\t\t\tif Vector2(pl.position.x - r.x, pl.position.z - r.z).length() < 2.4:
\t\t\t\tnear = str(r.label); break
\t\t_prompt.text = ("E - read the " + near) if near != "" and not _reading else ""
\t\t# hurts_touch rule: standing in a hurt zone drains 1 HP/s
\t\t_hurt_cd = maxf(0.0, _hurt_cd - _delta)
\t\tif _hurt_cd <= 0.0:
\t\t\tfor hz in hurt_zones:
\t\t\t\tif Vector2(pl.position.x - hz.x, pl.position.z - hz.z).length() < hz.r:
\t\t\t\t\t_hurt_cd = 1.0
\t\t\t\t\tplayer_hit(1)
\t\t\t\t\tbreak
\tif idx < 0 or idx >= steps.size(): return
\tvar st: Dictionary = steps[idx]
\tif st.get("kind") == "reach" and _beacon:
\t\tvar player := get_tree().get_first_node_in_group("player")
\t\tif player and Vector2(player.position.x - _beacon.position.x,
\t\t\t\tplayer.position.z - _beacon.position.z).length() < 2.4:
\t\t\t_advance()
\telif st.get("kind") == "survive":
\t\tvar elapsed := Time.get_ticks_msec() / 1000.0 - _t0
\t\tif elapsed > (_wave + 1) * 20.0:
\t\t\t_wave += 1
\t\t\t_wake_wave(1 + mini(_wave, 3))
\t\t_render_quest()
\t\tif elapsed >= float(st.get("count", 60)):
\t\t\t_advance()

func _win() -> void:
\tdone = true
\tInput.mouse_mode = Input.MOUSE_MODE_VISIBLE
\tvar text := ("You won the %s!" % reward) if reward != "" else win_text
\t_center_panel(["You win!", text, "Made with Fantasy Studio"], "Play again",
\t\tfunc(): get_tree().reload_current_scene())

func _label_for(st: Dictionary) -> String:
\tvar k: String = st.get("kind", "reach")
\tif k == "collect": return "Collect %d %s" % [int(st.get("count", 5)), st.get("label", "items")]
\tif k == "defeat": return "Defeat %d %s" % [int(st.get("count", 3)), st.get("label", "enemies")]
\tif k == "survive": return "Survive %s" % st.get("label", "the onslaught")
\treturn "Reach %s" % st.get("label", "the beacon")

func _render_quest() -> void:
\tvar lines := []
\tfor i in range(steps.size()):
\t\tvar mark := "+" if i < idx else (">" if i == idx else "-")
\t\tlines.append("%s %s" % [mark, _label_for(steps[i])])
\t_quest.text = "\\n".join(lines)
\tvar st: Dictionary = steps[idx] if idx >= 0 and idx < steps.size() else {}
\tvar prog := ""
\tif st.get("kind") == "collect": prog = " - %d/%d" % [got, int(st.get("count", 5))]
\telif st.get("kind") == "defeat": prog = " - %d/%d" % [kills, int(st.get("count", 3))]
\telif st.get("kind") == "survive":
\t\tvar left := maxi(0, int(ceil(float(st.get("count", 60)) - (Time.get_ticks_msec() / 1000.0 - _t0))))
\t\tprog = " - %ds" % left
\t_obj.text = _label_for(st) + prog if not st.is_empty() else ""
\t_hearts.text = "HP " + "#".repeat(maxi(hp, 0))
"""

_MULTIPLAYER_GUIDE = """# Taking this game MULTIPLAYER in Godot — the honest starting point

This export is a complete single-player Godot 4 project. Godot 4 has one of
the best built-in high-level multiplayer APIs of any free engine, and this
project is structured so you can layer it on:

## Why this project is multiplayer-ready
- `player.gd` is a self-contained CharacterBody3D scene — the unit you
  replicate per connected peer.
- `npc.gd` and `mission.gd` keep game state in plain variables — the things
  you sync with a MultiplayerSynchronizer.
- All assets are local files (no runtime downloads) — every client ships the
  same world.

## The 5 steps (Godot 4 high-level API)
1. **Peer setup** — in a new `lobby.gd` autoload:
   `var peer = ENetMultiplayerPeer.new(); peer.create_server(7777)` (host) or
   `peer.create_client(ip, 7777)` (join); `multiplayer.multiplayer_peer = peer`.
2. **Spawn players per peer** — add a `MultiplayerSpawner` to `main.tscn`
   pointing at the player scene; instance one player per
   `multiplayer.peer_connected` with `name = str(peer_id)`.
3. **Give each player authority** —
   `player.set_multiplayer_authority(peer_id)`; in `player.gd`, only process
   input `if is_multiplayer_authority()`.
4. **Sync transforms** — drop a `MultiplayerSynchronizer` in the player scene
   replicating `position` and `rotation`. NPCs/mission state sync the same
   way from the server.
5. **Make mission events server-authoritative** — turn score/kill/win updates
   in `mission.gd` into `@rpc(\"authority\", \"call_local\")` functions.

## Docs worth reading (free)
- Godot high-level multiplayer: docs.godotengine.org -> Networking
- `MultiplayerSpawner` / `MultiplayerSynchronizer` class docs
- For internet play beyond LAN: a cheap VPS relay or Steam sockets
  (GodotSteam, free) once you're on Steam.

Honest scope note: Fantasy Studio's web builds are single-player today —
this Godot path is the intended route to real multiplayer, and everything
above is free and open-source.
"""

_STEAM_GUIDE = """# From this export to Steam — the honest step-by-step

This folder is a complete **Godot 4.3 project**. Godot is the free,
MIT-licensed engine this game now lives in — Fantasy Studio is the on-ramp,
Godot is the road to shipping. Here is the whole path:

## 1. Open and play (5 minutes)
1. Download Godot 4.3+ (free, ~100 MB): https://godotengine.org/download
2. Open Godot → **Import** → select this folder's `project.godot`.
3. Wait for the first asset import to finish, then press **F5** to play.
   WASD move · Space jump · Shift run · F attack · Esc frees the mouse.

## 2. Make it yours (the fun part)
Everything is editable: `mission.gd` (objectives, waves, win text),
`player.gd` (movement feel), `npc.gd` (enemy AI), `main.tscn` (the world).
This is a normal Godot project with **no lock-in and no royalties** — you
own it completely.

## 3. Export a desktop build (30 minutes, once)
1. Editor → **Project → Export…** → Add → **Windows Desktop**
   (and/or macOS, Linux).
2. Godot will prompt to download **export templates** — accept (one-time).
3. Set an icon + product name, click **Export Project** → you get a
   standalone `.exe` you can zip and send to anyone.

## 4. Steam (when you're ready to sell)
1. **Steamworks account**: partner.steamgames.com — one-time $100 USD app
   fee per game (returned after $1,000 revenue).
2. Create your **App ID**, fill the store page (screenshots, description,
   capsule art).
3. Add Steam features (achievements, cloud saves) with **GodotSteam**, the
   standard free integration: https://godotsteam.com — install, initialize
   with your App ID, ship.
4. Upload builds with **SteamPipe** (Steamworks' upload tool) — the
   Steamworks docs walk through `steamcmd` in ~15 minutes.
5. Pass Steam's build review (usually days), press **Release**.

## What carried over from Fantasy Studio (Phase 46 parity)
- **Placed items** (campfires, fences, signs, books, buildings, rocks,
  chests, beacons) spawn as simplified primitives with colliders.
- **Rules are honored**: safe zones hold hostiles at the edge of the glow,
  `blocks_enemies` items push NPCs out (fences fence), hurt zones drain
  1 HP/s, and books/signs are readable — walk up, press **E**.
- **Views**: top-down and side-scroller exports use a fixed orthographic
  camera with matching controls, same as the web build.
- **Styles** map to Godot environment color grading (brightness/saturation,
  horror adds fog) — a close mood match, not a shader-for-shader port.

## Honest notes
- Race objectives from Fantasy Studio become reach-the-beacon here (rival
  route AI is a web-runtime feature for now).
- Placed props are primitive approximations of the web runtime's shapes —
  swap in real meshes freely, the rules stay attached to the position.
- The game has no audio files yet — drop `.ogg` files into an
  `AudioStreamPlayer` node for music/sfx (Kenney.nl has great CC0 packs).
- A Steam-worthy game usually wants 1–2 hours of content: duplicate
  `main.tscn` into level variants, chain them with
  `get_tree().change_scene_to_file(...)` on win.

Made with Fantasy Studio — one sentence became this project.
"""


def _tscn(spec: GameSpec, assets: list[tuple[str, str]]) -> str:
    """Build main.tscn: env + sun + ground + player(+camera) + NPCs + scatter
    + the Mission node carrying objectives and narrative."""
    sky_rgb, sun_e = _SKY.get(spec.world.sky, _SKY["day"])
    size = spec.world.size_m
    g = spec.world.ground_color

    ext = ['[ext_resource type="Script" path="res://player.gd" id="pgd"]',
           '[ext_resource type="Script" path="res://npc.gd" id="ngd"]',
           '[ext_resource type="Script" path="res://mission.gd" id="mgd"]']
    for i, (res_id, fname) in enumerate(assets):
        ext.append(f'[ext_resource type="PackedScene" path="res://assets/{fname}" id="{res_id}"]')

    # STYLE approximation (Phase 46): the web runtime's post pack becomes
    # Godot environment color adjustments — same mood, engine-native means
    _STYLE_ADJ = {
        "cartoon": (1.05, 1.35), "anime": (1.08, 1.18), "horror": (0.45, 0.5),
        "pixel": (1.0, 1.12), "lowpoly": (1.02, 1.15),
    }
    adj = _STYLE_ADJ.get(spec.style)
    env_extra = ""
    if adj:
        env_extra = (f"adjustment_enabled = true\n"
                     f"adjustment_brightness = {adj[0]}\n"
                     f"adjustment_saturation = {adj[1]}\n")
    if spec.style == "horror":
        env_extra += "fog_enabled = true\nfog_density = 0.03\nfog_light_color = Color(0.08, 0.09, 0.12, 1)\n"

    subs = f"""[sub_resource type="ProceduralSkyMaterial" id="skym"]
sky_top_color = Color({sky_rgb}, 1)
sky_horizon_color = Color({sky_rgb}, 1)

[sub_resource type="Sky" id="sky"]
sky_material = SubResource("skym")

[sub_resource type="Environment" id="env"]
background_mode = 2
sky = SubResource("sky")
{env_extra}
[sub_resource type="PlaneMesh" id="gmesh"]
size = Vector2({size}, {size})

[sub_resource type="StandardMaterial3D" id="gmat"]
albedo_color = Color({g[0]}, {g[1]}, {g[2]}, 1)
roughness = 1.0

[sub_resource type="BoxShape3D" id="gshape"]
size = Vector3({size}, 0.1, {size})

[sub_resource type="CapsuleShape3D" id="pcap"]
height = {spec.player.height_m:.2f}
radius = 0.35
"""
    # mission payload: same verbs as the web runtime (race → reach, noted in guide)
    steps = []
    for ob in spec.objectives:
        kind = "reach" if ob.kind == "race" else ob.kind
        steps.append({"kind": kind, "label": ob.label, "count": ob.count})
    if not steps:
        steps = [{"kind": "reach", "label": "the beacon", "count": 1}]
    steps_json = json.dumps(steps).replace('"', '\\"')
    # placed items ride along with their honored rules (Phase 46 parity)
    placed = [{"kind": it.kind, "name": it.name or it.kind, "x": it.x, "z": it.z,
               "yaw_deg": it.yaw_deg, "collide": it.collide,
               "interact": it.interact, "rules": it.rules}
              for it in spec.world.placed_items]
    placed_json = json.dumps(placed).replace('"', '\\"')
    intro = (spec.intro or "").replace('"', "'")
    win_text = (spec.win_text or "Mission complete!").replace('"', "'")
    reward = (spec.reward or "").replace('"', "'")

    nodes = [f'[node name="Main" type="Node3D"]',
             '',
             '[node name="Env" type="WorldEnvironment" parent="."]',
             'environment = SubResource("env")',
             '',
             '[node name="Sun" type="DirectionalLight3D" parent="."]',
             'transform = Transform3D(0.866, -0.354, 0.354, 0, 0.707, 0.707, -0.5, -0.612, 0.612, 0, 25, 0)',
             f'light_energy = {sun_e}',
             'shadow_enabled = true',
             '',
             '[node name="Mission" type="Node" parent="."]',
             'script = ExtResource("mgd")',
             f'steps_json = "{steps_json}"',
             f'placed_json = "{placed_json}"',
             f'intro = "{intro}"',
             f'win_text = "{win_text}"',
             f'reward = "{reward}"',
             f'player_hp = {spec.player.hp}',
             f'world_size = {size}',
             f'seed = {spec.seed}',
             '',
             '[node name="Ground" type="StaticBody3D" parent="."]',
             '[node name="GMesh" type="MeshInstance3D" parent="Ground"]',
             'mesh = SubResource("gmesh")',
             'surface_material_override/0 = SubResource("gmat")',
             '[node name="GCol" type="CollisionShape3D" parent="Ground"]',
             'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.05, 0)',
             'shape = SubResource("gshape")',
             '',
             '[node name="Player" type="CharacterBody3D" parent="." groups=["player"]]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {spec.player.height_m/2:.2f}, 0)',
             'script = ExtResource("pgd")',
             '[node name="PCol" type="CollisionShape3D" parent="Player"]',
             'shape = SubResource("pcap")',
             f'[node name="Model" parent="Player" instance=ExtResource("player_glb")]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {-spec.player.height_m/2:.2f}, 0)',
             '[node name="Arm" type="SpringArm3D" parent="Player"]',
             f'spring_length = {spec.camera.distance_m:.1f}',
             '[node name="Cam" type="Camera3D" parent="Player/Arm"]',
             f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {spec.camera.height_m*0.4:.2f}, {spec.camera.distance_m:.1f})',
             f'fov = {spec.camera.fov_deg:.0f}']

    # NPCs (one node per instance) + scatter (deterministic seeded ring)
    import random
    rng = random.Random(spec.seed)
    ni = 0
    for ent, (res_id, _f) in zip(spec.entities, assets[1:1 + len(spec.entities)]):
        grp = ' groups=["hostile"]' if ent.behavior == "hostile" else ""
        for c in range(ent.count):
            ni += 1
            spread = 0.55 if ent.behavior == "hostile" else 0.3
            x = (rng.random() - 0.5) * size * spread
            z = (rng.random() - 0.5) * size * spread
            nodes += [f'[node name="NPC{ni}" type="Node3D" parent="."{grp} instance=ExtResource("{res_id}")]',
                      f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {x:.2f}, 0, {z:.2f})',
                      'script = ExtResource("ngd")',
                      f'behavior = "{ent.behavior}"',
                      f'speed = {ent.speed:.2f}',
                      f'roam = {size * 0.3:.1f}',
                      f'hp = {getattr(ent, "hp", 3)}']
    si = 0
    scatter_assets = assets[1 + len(spec.entities):]
    for sct, (res_id, _f) in zip(spec.world.scatter, scatter_assets):
        for c in range(sct.count):
            si += 1
            import math
            ang = rng.random() * 6.283
            dist = 11.0 + rng.random() * (size * 0.4 - 11.0)
            s = 1 + (rng.random() - 0.5) * 2 * sct.scale_jitter
            x, z = math.cos(ang) * dist, math.sin(ang) * dist
            nodes += [f'[node name="Prop{si}" parent="." instance=ExtResource("{res_id}")]',
                      f'transform = Transform3D({s:.2f}, 0, 0, 0, {s:.2f}, 0, 0, 0, {s:.2f}, {x:.2f}, 0, {z:.2f})']

    load_steps = len(ext) + 8
    header = f"[gd_scene load_steps={load_steps} format=3]\n"
    return header + "\n" + "\n".join(ext) + "\n\n" + subs + "\n" + "\n".join(nodes) + "\n"


def export_godot_game(spec: GameSpec, out_dir: str | Path, verbose: bool = True) -> Path:
    """Emit a Godot 4 project. Returns the project dir."""
    proj = Path(out_dir) / "godot"
    assets_dir = proj / "assets"
    if assets_dir.exists():
        shutil.rmtree(assets_dir)
    assets_dir.mkdir(parents=True, exist_ok=True)

    # copy assets; assign ext_resource ids: player first, then entities, then scatter
    pairs: list[tuple[str, str]] = []

    def bring(src: str, res_id: str) -> None:
        srcp = Path(src)
        if not srcp.exists():
            raise FileNotFoundError(f"asset missing: {src}")
        shutil.copy2(srcp, assets_dir / srcp.name)
        pairs.append((res_id, srcp.name))

    bring(spec.player.asset, "player_glb")
    for i, ent in enumerate(spec.entities):
        bring(ent.asset, f"ent{i}")
    for i, sct in enumerate(spec.world.scatter):
        bring(sct.asset, f"sct{i}")

    (proj / "project.godot").write_text(
        _PROJECT.replace("__TITLE__", spec.title.replace('"', "'")), encoding="utf-8")
    (proj / "player.gd").write_text(
        _PLAYER_GD.replace("__WALK__", f"{spec.player.walk_speed:.2f}")
                  .replace("__RUN__", f"{spec.player.run_speed:.2f}")
                  .replace("__VIEW__", spec.view), encoding="utf-8")
    (proj / "npc.gd").write_text(_NPC_GD, encoding="utf-8")
    (proj / "mission.gd").write_text(_MISSION_GD, encoding="utf-8")
    (proj / "STEAM_GUIDE.md").write_text(_STEAM_GUIDE, encoding="utf-8")
    (proj / "MULTIPLAYER_GUIDE.md").write_text(_MULTIPLAYER_GUIDE, encoding="utf-8")
    (proj / "main.tscn").write_text(_tscn(spec, pairs), encoding="utf-8")
    (proj / "icon.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">'
        '<rect width="128" height="128" fill="#1a2b4a"/></svg>', encoding="utf-8")

    # structural verification: every placeholder resolved, every ext id used
    tscn = (proj / "main.tscn").read_text(encoding="utf-8")
    for f in ("player.gd", "npc.gd", "mission.gd"):
        body = (proj / f).read_text(encoding="utf-8")
        if "__" in body:
            raise RuntimeError(f"godot export: unresolved placeholder in {f}")
    if "__" in tscn:
        raise RuntimeError("godot export: unresolved placeholder in main.tscn")

    if verbose:
        n = sum(1 for _ in proj.rglob("*") if _.is_file())
        print(f"[game] godot project '{spec.title}' -> {proj} ({n} files, missions+guide)")
    return proj
