// GENERATED FILE — do not edit.
//
// Built from backend/app/game_export/runtime/factory.js.tpl by
// backend/tools/flagship_build.py. The standalone demo is the studio's
// own output with a fixed spec, so the two cannot drift apart. Edit the
// template and re-run the builder.
// FACTORY RUNTIME — the automation genre, generated by Fantasy Studio.
//
// A second runtime beside main.js.tpl. The adventure runtime renders a spec as
// a world you walk through; this one renders a spec as a world you BUILD in.
// They share the vendored three.js, the export pipeline, the verification gate
// and the asset library — everything except the game.
//
// Every constant below is derived from the injected spec, so the same
// generator that produces an adventure produces an island whose size, ore
// density and palette come from the prompt.
const SPEC = {"title": "Crystal Works", "genre": "factory", "style": "lowpoly", "world": {"name": "a floating worldlet of six mining faces", "size_m": 200, "palette": {"sky": "#0b0d18", "fog": "#0b0d18", "accent": "#39e6ff"}}, "objectives": [{"kind": "produce", "text": "automate an alloy line across two faces"}]};
window.__SPEC = SPEC;

const _sz = Math.max(60, Math.min(480, +(SPEC.world && SPEC.world.size_m) || 150));
const _pal = (SPEC.world && SPEC.world.palette) || {};
const _hex = (v, d) => {
  if (typeof v !== 'string' || v[0] !== '#' || v.length !== 7) return d;
  return parseInt(v.slice(1), 16);
};
const SKY_COL = _hex(_pal.sky, 0x0b0d18);
const FOG_COL = _hex(_pal.fog, SKY_COL);
const ACCENT = _hex(_pal.accent, 0x39e6ff);

// CRYSTAL WORKS — 3D incremental automation, core-loop prototype.
//
// The hook of this genre is one conversion: chaotic manual clicking becomes a
// machine that runs without you. So this builds exactly that loop and nothing
// else — mine, move, deliver. If it is not satisfying inside thirty seconds no
// upgrade tree will save it, and the brief is right that this is the thing to
// prove before writing thousands of lines.
//
// Performance shape: items on belts are NOT meshes. ONE InstancedMesh carries
// every crystal in the world and the tick writes matrices into it, so a
// thousand items across a hundred belts cost a single draw call.
import * as THREE from 'three';

// grid resolution follows the prompt's world size: a bigger island is a
// bigger factory, not the same factory further apart
const T = 2;
const N = Math.max(12, Math.min(40, Math.round(_sz / 6)));
const HALF = (N * T) / 2;

// ── THE CUBE (2026-09-07) ──────────────────────────────────────────────────
// The factory does not sit on a plane; it wraps a cube. A belt that runs off
// the top face keeps running down the side, and a player who walks over an
// edge finds gravity rotate under them. Every flat-ground competitor in this
// genre would have to rebuild their spatial core to copy it.
//
// This math is verified on its own in flagship/cubegrid.test.mjs — nineteen
// properties, including all 192 edge crossings of an 8-cube — because a wrong
// wrap does not crash. Items just quietly arrive on the wrong face, three
// hours into somebody's save.
const FACES = [
  { name: 'top',   u: [1, 0, 0],  v: [0, 0, -1] },
  { name: 'bot',   u: [1, 0, 0],  v: [0, 0, 1] },
  { name: 'east',  u: [0, 0, -1], v: [0, -1, 0] },
  { name: 'west',  u: [0, 0, 1],  v: [0, -1, 0] },
  { name: 'south', u: [1, 0, 0],  v: [0, -1, 0] },
  { name: 'north', u: [-1, 0, 0], v: [0, -1, 0] },
];
const _cr = (a, b) => [a[1] * b[2] - a[2] * b[1],
                       a[2] * b[0] - a[0] * b[2],
                       a[0] * b[1] - a[1] * b[0]];
const _dt3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const _ng = a => [-a[0], -a[1], -a[2]];
const _eqv = (a, b) => Math.abs(a[0] - b[0]) < 1e-9 &&
                       Math.abs(a[1] - b[1]) < 1e-9 && Math.abs(a[2] - b[2]) < 1e-9;
for (const f of FACES) f.n = _cr(f.u, f.v);      // right-handed: u x v = n

const dirVec = (face, d) => [FACES[face].u, FACES[face].v,
                             _ng(FACES[face].u), _ng(FACES[face].v)][d & 3];

/** World-space centre of tile [face,i,j], on the cube surface. */
function tileWorld(face, i, j) {
  const f = FACES[face];
  const a = (i + 0.5 - N / 2) * T, b = (j + 0.5 - N / 2) * T;
  return [f.n[0] * HALF + f.u[0] * a + f.v[0] * b,
          f.n[1] * HALF + f.u[1] * a + f.v[1] * b,
          f.n[2] * HALF + f.u[2] * a + f.v[2] * b];
}

/**
 * One tile along heading d. Inside a face this is arithmetic; crossing an edge
 * is the whole feature. The destination is the face whose normal matches the
 * way you walked off, and your heading there becomes the OLD face's inward
 * normal. The indices come from projecting the tile you left onto the new
 * basis — which is how twenty-four hand-written edge cases, one of them
 * inevitably wrong, are avoided.
 */
function stepTile(face, i, j, d) {
  const ni = i + [1, 0, -1, 0][d & 3];
  const nj = j + [0, 1, 0, -1][d & 3];
  if (ni >= 0 && nj >= 0 && ni < N && nj < N) return { face, i: ni, j: nj, d };

  const walk = dirVec(face, d), oldN = FACES[face].n;
  let dst = -1;
  for (let k = 0; k < 6; k++) if (_eqv(FACES[k].n, walk)) { dst = k; break; }
  if (dst < 0) return null;
  const want = _ng(oldN);
  let nd = -1;
  for (let k = 0; k < 4; k++) if (_eqv(dirVec(dst, k), want)) { nd = k; break; }
  if (nd < 0) return null;

  const o = FACES[face], g = FACES[dst];
  const a = i + 0.5 - N / 2, b = j + 0.5 - N / 2;   // unit tiles: indices only
  const w = [o.n[0] * (N / 2) + o.u[0] * a + o.v[0] * b,
             o.n[1] * (N / 2) + o.u[1] * a + o.v[1] * b,
             o.n[2] * (N / 2) + o.u[2] * a + o.v[2] * b];
  const ri = Math.max(0, Math.min(N - 1, Math.round(_dt3(w, g.u) + N / 2 - 0.5)));
  const rj = Math.max(0, Math.min(N - 1, Math.round(_dt3(w, g.v) + N / 2 - 0.5)));
  return { face: dst, i: ri, j: rj, d: nd, wrapped: true };
}

/** Which face a world point belongs to: the one whose normal it is furthest along. */
function faceOfPoint(px, py, pz) {
  let best = 0, bestD = -Infinity;
  for (let k = 0; k < 6; k++) {
    const n = FACES[k].n, d = px * n[0] + py * n[1] + pz * n[2];
    if (d > bestD) { bestD = d; best = k; }
  }
  return best;
}

const BASE_TICK = 0.42;
let TICK = BASE_TICK;
const EMPTY = 0, MINER = 1, BELT = 2, HUB = 3, NODE = 4, SMELTER = 5,
      SPLITTER = 6, FORGE = 7, FILTER = 8, RIFT = 9;
const DIRS = [[1, 0], [0, 1], [-1, 0], [0, -1]];        // E S W N

// Items now have a TYPE, and that is the whole point of the smelter. Until
// now a belt only ever solved "the node is far from the hub" — a distance
// problem, which is a chore rather than a puzzle. A recipe makes belts solve
// "these things have to MEET", which is where this genre's actual decisions
// live: where to put the smelter, how to feed it from two nodes, what to do
// with the surplus when one input runs dry.
// ── WHAT THE CUBE IS FOR (2026-09-07) ──────────────────────────────────────
// Every face used to grow the same crystal, which made the other five faces
// scenery: a factory that never left the top was optimal, and the mechanic
// the whole build is named for was a gimmick you could ignore. Three minerals,
// one per opposite pair of faces, and an alloy that cannot be made from any
// single face's ore. Now a belt HAS to go over an edge.
const CRYSTAL = 1, EMBER = 2, SALT = 3;
const MINERALS = [CRYSTAL, EMBER, SALT];
const INGOT = 4, INGOT_E = 5, INGOT_S = 6, ALLOY = 7;
const INGOT_OF = { [CRYSTAL]: INGOT, [EMBER]: INGOT_E, [SALT]: INGOT_S };
const IS_MINERAL = t => t === CRYSTAL || t === EMBER || t === SALT;
const IS_INGOT = t => t === INGOT || t === INGOT_E || t === INGOT_S;
// FACES is [top, bot, east, west, south, north]; opposite faces share a
// mineral so that whichever way you walk off the top, the ore changes.
const MINERAL_OF_FACE = [CRYSTAL, CRYSTAL, EMBER, EMBER, SALT, SALT];
const MINERAL_NAME = { [CRYSTAL]: 'crystal', [EMBER]: 'ember', [SALT]: 'salt' };
const TYPE_NAME = { 1: 'miner', 2: 'belt', 3: 'hub', 4: 'ore node',
                    5: 'smelter', 6: 'splitter', 7: 'forge', 8: 'filter',
                    9: 'chronos rift' };

const VALUE = { [CRYSTAL]: 1, [INGOT]: 6 };   // an ingot is worth the detour
const SMELT_IN = 2;                            // ore of one kind per ingot
let SMELT_TICKS = 3;                           // and it takes time
let FORGE_TICKS = 4;                           // an alloy takes longer still

// ── UPGRADES ───────────────────────────────────────────────────────────────
// The loop this genre runs on is: build something, watch the number climb,
// spend the number to make it climb faster. Each of these has to be VISIBLE
// when bought — a purchase that only changes a hidden coefficient feels like
// nothing, and feeling like something is the entire product.
// ── PRESTIGE ───────────────────────────────────────────────────────────────
// Everything on the cube is destroyed and you keep a number. It is the oldest
// trick in the incremental genre and it works because the second run is
// visibly faster than the first — the factory you rebuild is the same one,
// and it earns nearly half again as much per crystal.
let cores = 0;
let runValue = 0;                       // banked THIS run; cores are priced off it
const MELT_MIN = 400;
const coresFor = v => Math.floor(Math.sqrt(v / 220));

const UPGRADES = {
  tick:  { lvl: 0, cap: 6, cost: 60,  mult: 2.3,
           label: 'OVERCLOCK', note: 'everything runs faster' },
  yield: { lvl: 0, cap: 6, cost: 90,  mult: 2.5,
           label: 'RICH SEAMS', note: 'crystals are worth more' },
  smelt: { lvl: 0, cap: 4, cost: 150, mult: 2.8,
           label: 'HOT FURNACE', note: 'smelters cook quicker' },
};
const costOf = u => Math.round(u.cost * Math.pow(u.mult, u.lvl));

function applyUpgrades() {
  TICK = BASE_TICK * Math.pow(0.86, UPGRADES.tick.lvl);
  SMELT_TICKS = Math.max(1, 3 - UPGRADES.smelt.lvl);
  // A CORE IS WORTH MORE THAN THE FACTORY IT COST. The multiplier has to be
  // steep enough that melting down a good factory beats keeping it, or the
  // prestige is a button nobody presses twice.
  const y = (1 + UPGRADES.yield.lvl) * (1 + 0.45 * cores);
  for (const m of MINERALS) { VALUE[m] = y; VALUE[INGOT_OF[m]] = 6 * y; }
  // An alloy is worth more than the three ingots it displaces, because it
  // costs a belt run across a face boundary and the risk of getting it wrong.
  VALUE[ALLOY] = 26 * y;
  FORGE_TICKS = Math.max(2, 4 - UPGRADES.smelt.lvl);
}

function buy(key) {
  const u = UPGRADES[key];
  if (!u || u.lvl >= u.cap) return false;
  const c = costOf(u);
  if (ore < c) return false;
  ore -= c;
  u.lvl++;
  applyUpgrades();
  renderUpgrades();
  return true;
}

function renderUpgrades() {
  const box = document.getElementById('ups');
  if (!box) return;
  box.innerHTML = '';
  for (const key of Object.keys(UPGRADES)) {
    const u = UPGRADES[key];
    const maxed = u.lvl >= u.cap;
    const c = costOf(u);
    const el = document.createElement('div');
    el.className = 'up' + (maxed ? ' maxed' : (ore >= c ? ' can' : ''));
    el.innerHTML = '<b>' + u.label + ' <span>' + u.lvl + '/' + u.cap + '</span></b>' +
      '<small>' + u.note + '</small>' +
      '<i>' + (maxed ? 'MAX' : c + ' value') + '</i>';
    if (!maxed) el.addEventListener('pointerdown', ev => { ev.stopPropagation(); buy(key); });
    box.appendChild(el);
  }
}

// Six faces of N x N. Nothing else in the simulation knows the shape of the
// world: it asks stepTile what is next to a tile, and stepTile is the only
// place an edge exists.
const cells = [];
for (let f = 0; f < 6; f++) {
  cells[f] = [];
  for (let i = 0; i < N; i++) {
    cells[f][i] = [];
    for (let j = 0; j < N; j++)
      cells[f][i][j] = { t: EMPTY, d: 0, item: 0, buf: 0, bt: 0,
                         fa: 0, fb: 0, cook: 0, rr: 0, min: 0,
                         filt: CRYSTAL, mrr: 0,
                         dbt: 0, dmin: 0, emit: 0, left: 0, cool: 0 };
  }
}
const cellOf = t => (t ? cells[t.face][t.i][t.j] : null);
/** Every tile on the cube, once. */
function eachTile(fn) {
  for (let f = 0; f < 6; f++)
    for (let i = 0; i < N; i++)
      for (let j = 0; j < N; j++) fn(cells[f][i][j], f, i, j);
}

// ── scene ──────────────────────────────────────────────────────────────────
const scene = new THREE.Scene();
scene.background = new THREE.Color(SKY_COL);
const worldFog = new THREE.Fog(FOG_COL, HALF * 1.6, HALF * 4.0);
scene.fog = worldFog;
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, 0.1, 500);
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.06;
document.body.appendChild(renderer.domElement);

scene.add(new THREE.HemisphereLight(0x9fc4ff, 0x1b2038, 1.1));
const sun = new THREE.DirectionalLight(0xfff0d8, 2.2);
sun.position.set(30, 46, 20);
sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048);
sun.shadow.camera.left = -HALF * 1.5;
sun.shadow.camera.right = HALF * 1.5;
sun.shadow.camera.top = HALF * 1.5;
sun.shadow.camera.bottom = -HALF * 1.5;
sun.shadow.camera.near = 1;
sun.shadow.camera.far = 170;
sun.shadow.camera.updateProjectionMatrix();
scene.add(sun);

// ONE SUN LIGHTS ONE SIDE OF A CUBE (2026-09-07). On a flat island a single
// directional light was enough. On a worldlet the faces facing away from it
// fall to pure hemisphere ambient and read as unlit black — you walk around
// the corner into a game that looks broken. A dimmer fill from the opposite
// quadrant keeps every face legible without flattening the key light.
const fill = new THREE.DirectionalLight(0xb9d2ff, 0.85);
fill.position.set(-34, -40, -26);
scene.add(fill);

// ── the sky ────────────────────────────────────────────────────────────────
// A floating worldlet against flat black reads as a bug. Stars cost one draw
// call and give the cube something to be floating IN — and when you walk over
// an edge and the world rotates, they are what makes the rotation legible.
{
  const n = 1600, pos = new Float32Array(n * 3), col = new Float32Array(n * 3);
  const c = new THREE.Color();
  let seed = 90210;
  const rr = () => (seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296;
  for (let k = 0; k < n; k++) {
    // even over the sphere: acos keeps them off the poles, which a naive
    // lat/long scatter clumps at
    // INSIDE THE FAR PLANE (2026-09-08). The first pass put the field at 900
    // with the camera's far at 500, so every star was clipped and the sky
    // stayed exactly as black as it had been.
    const u = rr() * 2 - 1, th = rr() * Math.PI * 2, r = 400;
    const sp = Math.sqrt(1 - u * u);
    pos[k * 3] = Math.cos(th) * sp * r;
    pos[k * 3 + 1] = u * r;
    pos[k * 3 + 2] = Math.sin(th) * sp * r;
    // a few warm and a few blue ones; an all-white field looks printed
    c.setHSL(rr() < 0.75 ? 0.58 + rr() * 0.06 : 0.08 + rr() * 0.05,
             0.35 + rr() * 0.4, 0.55 + rr() * 0.4);
    col[k * 3] = c.r; col[k * 3 + 1] = c.g; col[k * 3 + 2] = c.b;
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
  const stars = new THREE.Points(g, new THREE.PointsMaterial({
    size: 2.1, sizeAttenuation: false, vertexColors: true,
    transparent: true, opacity: 0.95, depthWrite: false, fog: false }));
  stars.frustumCulled = false;
  scene.add(stars);
}

// ── the worldlet: a cube you can walk all the way around ───────────────────
// PLATING, drawn at boot like the tread. A flat colour over 6400 square metres
// reads as a placeholder no matter what colour it is; panel seams and a little
// grain give the light something to catch as you walk.
function plateTexture() {
  const c = document.createElement('canvas');
  c.width = c.height = 128;
  const g = c.getContext('2d');
  // LOW CONTRAST ON PURPOSE (2026-09-08). The first pass drew hard dark seams
  // twenty times per face, which on top of the tile grid read as a wireframe
  // mesh rather than as a surface. Plating should be something you notice
  // underfoot, not a second grid competing with the one that means something.
  g.fillStyle = '#8792c4'; g.fillRect(0, 0, 128, 128);
  g.strokeStyle = '#7a85b8'; g.lineWidth = 2;
  g.strokeRect(1, 1, 126, 126);
  const d = g.getImageData(0, 0, 128, 128);
  for (let k = 0; k < d.data.length; k += 4) {
    const v = (Math.random() - 0.5) * 22;
    d.data[k] += v; d.data[k + 1] += v; d.data[k + 2] += v;
  }
  g.putImageData(d, 0, 0);
  const t = new THREE.CanvasTexture(c);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.repeat.set(N / 5, N / 5);      // panels bigger than tiles, so they read as panels
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}
const cube = new THREE.Mesh(
  new THREE.BoxGeometry(N * T, N * T, N * T),
  new THREE.MeshStandardMaterial({ color: 0x3c4470, roughness: 0.94,
    metalness: 0.12, map: plateTexture() }));
cube.receiveShadow = true;
scene.add(cube);
{
  // grid lines on all six faces, lifted a hair off the surface. Without them
  // the underside of the world is an unreadable dark field and you cannot
  // tell where a belt will land.
  const pts = [];
  const E = HALF + 0.02;
  for (const f of FACES) {
    for (let k = 0; k <= N; k++) {
      const q = -HALF + k * T;
      for (const [a, b, c, d] of [[q, -HALF, q, HALF], [-HALF, q, HALF, q]]) {
        pts.push(f.n[0] * E + f.u[0] * a + f.v[0] * b,
                 f.n[1] * E + f.u[1] * a + f.v[1] * b,
                 f.n[2] * E + f.u[2] * a + f.v[2] * b,
                 f.n[0] * E + f.u[0] * c + f.v[0] * d,
                 f.n[1] * E + f.u[1] * c + f.v[1] * d,
                 f.n[2] * E + f.u[2] * c + f.v[2] * d);
      }
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3));
  scene.add(new THREE.LineSegments(g, new THREE.LineBasicMaterial(
    // fainter than it was: forty lines a face is a placement aid up close and
    // a moire pattern from orbit
    { color: 0x46527d, transparent: true, opacity: 0.14 })));
}

// SEATING. Everything that stands on the cube shares one rule: local +Y
// becomes the face normal and local +X the heading. Written once, so a belt
// arrow, a smelter and the build ghost cannot disagree about which way is up
// on the underside of the world.
const _mx = new THREE.Matrix4();
const _bx = new THREE.Vector3(), _by = new THREE.Vector3(), _bz = new THREE.Vector3();

// ONE MACHINE, ONE GEOMETRY. A smelter drawn as a body plus a chimney plus a
// rim is three draw calls every frame forever; merged at boot it is one. The
// parts are still authored separately because that is the only sane way to
// describe a shape, they just do not survive as separate objects.
const _pm = new THREE.Matrix4();
const _pq = new THREE.Quaternion();
const _pe = new THREE.Euler();
const _pv = new THREE.Vector3();
const _ps = new THREE.Vector3(1, 1, 1);
function mergeParts(parts) {
  const pos = [], nor = [], uvs = [];
  for (const p of parts) {
    const g = p.g.clone().toNonIndexed();
    _pe.set(p.rx || 0, p.ry || 0, p.rz || 0);
    _pq.setFromEuler(_pe);
    _pv.set(p.x || 0, p.y || 0, p.z || 0);
    _pm.compose(_pv, _pq, _ps);
    g.applyMatrix4(_pm);
    const a = g.attributes;
    for (let k = 0; k < a.position.array.length; k++) pos.push(a.position.array[k]);
    for (let k = 0; k < a.normal.array.length; k++) nor.push(a.normal.array[k]);
    if (a.uv) for (let k = 0; k < a.uv.array.length; k++) uvs.push(a.uv.array[k]);
    g.dispose();
  }
  const out = new THREE.BufferGeometry();
  out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  out.setAttribute('normal', new THREE.Float32BufferAttribute(nor, 3));
  if (uvs.length === (pos.length / 3) * 2)
    out.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2));
  out.computeBoundingSphere();
  return out;
}

/** The seating transform as a matrix, for machines drawn as instances. */
function seatMatrix(face, i, j, dir, up, out) {
  const f = FACES[face], w = tileWorld(face, i, j), dv = dirVec(face, dir || 0);
  _bx.set(dv[0], dv[1], dv[2]);
  _by.set(f.n[0], f.n[1], f.n[2]);
  _bz.crossVectors(_bx, _by);
  out.makeBasis(_bx, _by, _bz);
  const h = up || 0;
  out.setPosition(w[0] + f.n[0] * h, w[1] + f.n[1] * h, w[2] + f.n[2] * h);
  return out;
}

function seat(obj, face, i, j, dir, up) {
  seatMatrix(face, i, j, dir, up, _mx);
  obj.position.setFromMatrixPosition(_mx);
  obj.quaternion.setFromRotationMatrix(_mx);
}

// ── crystal nodes: the only tiles a miner can stand on ─────────────────────
// The player's first read of "this face is different" is the colour of the
// ore standing on it, from across the worldlet, before they have walked there.
const MIN_COL = { [CRYSTAL]: ACCENT, [EMBER]: 0xff8a3d, [SALT]: 0xe8f0ff };
const nodeMats = {};
for (const m of MINERALS) nodeMats[m] = new THREE.MeshStandardMaterial({
  color: MIN_COL[m], emissive: MIN_COL[m], emissiveIntensity: 0.55,
  roughness: 0.25, flatShading: true });
const nodeMat = nodeMats[CRYSTAL];
const nodeGeo = new THREE.OctahedronGeometry(0.62, 0);
let rngState = 1337;
const rnd = () => (rngState = (rngState * 1664525 + 1013904223) % 4294967296) / 4294967296;
const NODE_COUNT = Math.max(6, Math.min(40, Math.round(N * N * 0.028)));
for (let k = 0; k < NODE_COUNT; k++) {
  const f = Math.floor(rnd() * 6);
  const i = 2 + Math.floor(rnd() * (N - 4));
  const j = 2 + Math.floor(rnd() * (N - 4));
  const c = cells[f][i][j];
  if (c.t !== EMPTY) continue;
  c.t = NODE;
  c.min = MINERAL_OF_FACE[f];
  const m = new THREE.Mesh(nodeGeo, nodeMats[c.min]);
  seat(m, f, i, j, 0, 0.7);
  m.userData.fsTag = { type: 'ore', name: MINERAL_NAME[c.min] + ' seam',
                       detail: FACES[f].name + ' face · tile ' + i + ',' + j,
                       face: f, i, j };
  m.castShadow = true;
  m.userData.spin = 0.4 + rnd() * 0.6;
  m.userData.axis = FACES[f].n;      // spin about the face's up, not the world's
  scene.add(m);
  c.mesh = m;
}

// ── the tread, drawn rather than loaded ────────────────────────────────────
// A conveyor that does not visibly move is a green plank. Slats and chevrons
// on a 64px canvas, scrolled by the tick clock: one shared material animates
// every belt on the worldlet, and the direction reads without an arrow
// hovering over each tile.
function treadTexture() {
  const c = document.createElement('canvas');
  c.width = 64; c.height = 64;
  const g = c.getContext('2d');
  g.fillStyle = '#16362e'; g.fillRect(0, 0, 64, 64);
  g.fillStyle = '#1f4f43';
  for (let x = 0; x < 64; x += 16) g.fillRect(x, 0, 10, 64);   // slats across
  g.strokeStyle = '#57e0b0'; g.lineWidth = 4; g.lineCap = 'round';
  g.lineJoin = 'round';
  for (let x = 4; x < 64; x += 16) {                            // chevrons -> +u
    g.beginPath();
    g.moveTo(x, 18); g.lineTo(x + 8, 32); g.lineTo(x, 46);
    g.stroke();
  }
  const t = new THREE.CanvasTexture(c);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}
const TREAD = treadTexture();

// ── build meshes ───────────────────────────────────────────────────────────
const MAT = {
  miner: new THREE.MeshStandardMaterial({ color: 0xff5d73, roughness: 0.4, metalness: 0.35 }),
  belt: new THREE.MeshStandardMaterial({ color: 0x3ad39a, roughness: 0.6, metalness: 0.2 }),
  beltFrame: new THREE.MeshStandardMaterial({ color: 0x2b7f68, roughness: 0.45,
    metalness: 0.6, flatShading: true }),
  beltDeck: new THREE.MeshStandardMaterial({ map: TREAD, roughness: 0.85,
    metalness: 0.05 }),
  hub: new THREE.MeshStandardMaterial({ color: 0xffc75a, roughness: 0.35, metalness: 0.45,
    emissive: 0x6b4a00, emissiveIntensity: 0.6 }),
  forge: new THREE.MeshStandardMaterial({ color: 0xd94fb0, roughness: 0.34,
    metalness: 0.55, flatShading: true }),
  filt: new THREE.MeshStandardMaterial({ color: 0x2f8f7d, roughness: 0.55,
    metalness: 0.25 }),
  rift: new THREE.MeshStandardMaterial({ color: 0x6a3cff, emissive: 0x3a1c9c,
    emissiveIntensity: 0.8, roughness: 0.3, metalness: 0.5, flatShading: true }),
  smelt: new THREE.MeshStandardMaterial({ color: 0x8c6bff, roughness: 0.42, metalness: 0.4,
    emissive: 0x2a1470, emissiveIntensity: 0.5 }),
  split: new THREE.MeshStandardMaterial({ color: 0x4bb5ff, roughness: 0.45, metalness: 0.35,
    emissive: 0x0d3f66, emissiveIntensity: 0.45 }),
};
// Each machine is authored as parts and merged into one geometry. Local +X is
// the heading and local +Y is up off the face, which is what seat() promises.
const _box = (w, h, d) => new THREE.BoxGeometry(w, h, d);
const _cyl = (rt, rb, h, n) => new THREE.CylinderGeometry(rt, rb, h, n);

const GEO = {
  // A CONVEYOR, not a plank: side rails, an end roller at each end, a base
  // plate, and a separate deck that carries the moving tread.
  beltFrame: mergeParts([
    { g: _box(T * 0.96, 0.05, T * 0.82), y: 0.03 },
    { g: _box(T * 0.96, 0.14, 0.09), y: 0.15, z: T * 0.37 },
    { g: _box(T * 0.96, 0.14, 0.09), y: 0.15, z: -T * 0.37 },
    { g: _cyl(0.105, 0.105, T * 0.70, 8), y: 0.13, x: T * 0.41, rx: Math.PI / 2 },
    { g: _cyl(0.105, 0.105, T * 0.70, 8), y: 0.13, x: -T * 0.41, rx: Math.PI / 2 },
  ]),
  beltDeck: _box(T * 0.86, 0.06, T * 0.60),

  // a rig with legs and a bit that turns, so a miner reads as MINING
  miner: mergeParts([
    { g: _box(T * 0.78, 0.30, T * 0.78), y: 0.15 },
    { g: _box(0.13, 0.95, 0.13), y: 0.62, x: T * 0.28, z: T * 0.28 },
    { g: _box(0.13, 0.95, 0.13), y: 0.62, x: -T * 0.28, z: T * 0.28 },
    { g: _box(0.13, 0.95, 0.13), y: 0.62, x: T * 0.28, z: -T * 0.28 },
    { g: _box(0.13, 0.95, 0.13), y: 0.62, x: -T * 0.28, z: -T * 0.28 },
    { g: _box(T * 0.70, 0.14, T * 0.70), y: 1.14 },
    { g: _cyl(0.10, 0.10, 0.80, 6), y: 0.72 },
  ]),
  minerBit: _cyl(0.02, 0.28, 0.5, 6),

  arrow: new THREE.ConeGeometry(0.2, 0.5, 4),

  // a landing pad with a mast, so the place everything is going to looks like
  // a destination instead of another box
  hub: mergeParts([
    { g: _cyl(T * 0.56, T * 0.62, 0.30, 12), y: 0.15 },
    { g: new THREE.TorusGeometry(T * 0.46, 0.06, 6, 18), y: 0.36, rx: Math.PI / 2 },
    { g: _cyl(0.09, 0.09, 0.85, 6), y: 0.74 },
  ]),

  // a furnace: body, rim, and a flue offset to one corner
  smelt: mergeParts([
    { g: _box(T * 0.80, 1.00, T * 0.80), y: 0.52 },
    { g: _box(T * 0.90, 0.11, T * 0.90), y: 1.06 },
    { g: _cyl(0.13, 0.17, 0.60, 6), y: 1.40, x: T * 0.22, z: -T * 0.22 },
  ]),

  split: mergeParts([
    { g: _cyl(T * 0.42, T * 0.42, 0.30, 4), y: 0.15, ry: Math.PI / 4 },
    { g: _box(T * 0.88, 0.15, 0.20), y: 0.36 },
    { g: _box(T * 0.88, 0.15, 0.20), y: 0.36, ry: Math.PI / 2 },
  ]),

  // taller and eight-sided, so a forge is not mistaken for a smelter
  // from across the worldlet
  forge: mergeParts([
    { g: _cyl(T * 0.44, T * 0.50, 1.30, 8), y: 0.65 },
    { g: new THREE.TorusGeometry(T * 0.40, 0.08, 6, 16), y: 1.28, rx: Math.PI / 2 },
  ]),
  rift: new THREE.TorusGeometry(T * 0.38, 0.16, 6, 12),
  riftBase: _cyl(T * 0.46, T * 0.5, 0.18, 8),
  riftCore: new THREE.OctahedronGeometry(0.34, 0),
  filter: mergeParts([
    { g: _box(T * 0.92, 0.24, T * 0.92), y: 0.12 },
    { g: _box(T * 0.16, 0.34, T * 0.66), y: 0.34, x: T * 0.34 },
  ]),
  filterGate: new THREE.BoxGeometry(T * 0.16, 0.5, T * 0.62),
};

function refreshCounts() {
  let m = 0, b = 0, sm = 0;
  eachTile(c => {
    if (c.t === MINER) m++;
    else if (c.t === BELT) b++;
    else if (c.t === SMELTER) sm++;
  });
  document.getElementById('nmine').textContent = m;
  document.getElementById('nbelt').textContent = b;
  document.getElementById('nsmelt').textContent = sm;
}

function removeAt(face, i, j) {
  const c = cells[face][i][j];
  if (c.t === BELT) beltsDirty = true;
  if (c.build) { scene.remove(c.build); c.build = null; }
  c.t = c.mesh ? NODE : EMPTY;               // a node outlives its miner
  c.item = 0;
  refreshCounts();
}

function place(face, i, j, type, dir) {
  const c = cells[face][i][j];
  if (type === MINER && c.t !== NODE && c.t !== MINER) return false;
  // REFUSE A TYPE THIS FACTORY DOES NOT BUILD (2026-09-07). place() used to
  // fall off the end of its if-chain for an unrecognised type and set
  // c.t = undefined: an invisible machine that no rule matched and no counter
  // saw. Nothing threw; the tile just quietly stopped being part of the game.
  if (!TYPE_NAME[type]) return false;
  c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0;
  if (type !== MINER && c.t === NODE) return false;      // keep nodes clear
  if (c.build) { scene.remove(c.build); c.build = null; }
  const g = new THREE.Group();
  if (type === MINER) {
    const b = new THREE.Mesh(GEO.miner, MAT.miner);
    b.castShadow = true; g.add(b);
    // the bit turns while the rig is on a seam: the only moving part on a
    // machine that otherwise just sits there
    const bit = new THREE.Mesh(GEO.minerBit, MAT.miner);
    bit.position.y = 0.42; bit.name = 'bit'; g.add(bit);
  } else if (type === BELT) {
    // belts are drawn as instances, not as objects — see rebuildBelts()
  } else if (type === HUB) {
    const b = new THREE.Mesh(GEO.hub, MAT.hub);
    b.castShadow = true; g.add(b);
    const beacon = new THREE.Mesh(new THREE.SphereGeometry(0.15, 8, 6),
      new THREE.MeshBasicMaterial({ color: 0xffd479 }));
    beacon.position.y = 1.22; beacon.name = 'lamp'; g.add(beacon);
  } else if (type === SPLITTER) {
    // a cross, so what it does is visible from across the worldlet rather than
    // being a box you have to remember the meaning of
    const b = new THREE.Mesh(GEO.split, MAT.split);
    b.castShadow = true; b.receiveShadow = true; g.add(b);
  } else if (type === RIFT) {
    const ring = new THREE.Mesh(GEO.rift, MAT.rift);
    ring.position.y = 0.95; ring.rotation.x = Math.PI / 2;
    ring.castShadow = true; ring.name = 'ring'; g.add(ring);
    const core = new THREE.Mesh(GEO.riftCore,
      new THREE.MeshBasicMaterial({ color: 0x2a2050 }));
    core.position.y = 0.95; core.name = 'lamp'; g.add(core);
    const base = new THREE.Mesh(GEO.riftBase, MAT.rift);
    base.position.y = 0.11; base.receiveShadow = true; g.add(base);
  } else if (type === FILTER) {
    const b = new THREE.Mesh(GEO.filter, MAT.filt);
    b.castShadow = true; b.receiveShadow = true; g.add(b);
    // the gate is coloured with the ore that passes, so a filter's setting is
    // readable from across the face instead of from a tooltip
    const gate = new THREE.Mesh(GEO.filterGate,
      new THREE.MeshStandardMaterial({ color: MIN_COL[c.filt] || 0x7df9ff,
        emissive: MIN_COL[c.filt] || 0x7df9ff, emissiveIntensity: 0.5,
        roughness: 0.3, flatShading: true }));
    gate.position.set(0.36, 0.42, 0);
    gate.name = 'gate';
    g.add(gate);
    const r = new THREE.Mesh(GEO.arrow, MAT.filt);   // reject: out the side
    r.position.set(0, 0.42, 0.74); r.rotation.x = Math.PI / 2; g.add(r);
  } else if (type === FORGE) {
    const b = new THREE.Mesh(GEO.forge, MAT.forge);
    b.castShadow = true; g.add(b);
    const lamp = new THREE.Mesh(new THREE.SphereGeometry(0.17, 8, 6),
      new THREE.MeshBasicMaterial({ color: 0xff5ad9 }));
    lamp.position.set(0, 1.5, 0);
    lamp.name = 'lamp';
    g.add(lamp);
  } else if (type === SMELTER) {
    const b = new THREE.Mesh(GEO.smelt, MAT.smelt);
    b.castShadow = true; g.add(b);
    // a lamp that lights while it is cooking: a factory you can read at a
    // glance from across the island is the whole appeal of the genre
    const lamp = new THREE.Mesh(new THREE.SphereGeometry(0.17, 8, 6),
      new THREE.MeshBasicMaterial({ color: 0xffb04a }));
    lamp.position.set(0, 1.34, 0);
    lamp.name = 'lamp';
    g.add(lamp);
  }
  seat(g, face, i, j, dir, 0);
  // what the studio's inspector reads when you click this. Same shape the
  // adventure runtime uses, so one panel renders picks from either genre.
  g.userData.fsTag = { type: 'machine', name: TYPE_NAME[type] || 'machine',
                       detail: FACES[face].name + ' face · tile ' + i + ',' + j,
                       face, i, j };
  if (type === BELT) beltsDirty = true;      // drawn as an instance instead
  else scene.add(g);
  c.build = type === BELT ? null : g;
  c.t = type;
  c.d = dir;
  c.item = 0;
  refreshCounts();
  return true;
}

// ── belts: ONE InstancedMesh pair, however many you build ──────────────────
// 241 belts cost 482 draw calls as individual groups, before any detail was
// added. As instances they cost two, and the art pass became affordable.
const MAX_BELTS = 6000;
const beltFrames = new THREE.InstancedMesh(GEO.beltFrame, MAT.beltFrame, MAX_BELTS);
const beltDecks = new THREE.InstancedMesh(GEO.beltDeck, MAT.beltDeck, MAX_BELTS);
const beltIndex = [];                 // instance -> tile, so Inspect can name one
for (const m of [beltFrames, beltDecks]) {
  m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
  m.frustumCulled = false;
  m.castShadow = true; m.receiveShadow = true;
  m.count = 0;
  scene.add(m);
}
let beltsDirty = true;

function rebuildBelts() {
  let n = 0;
  beltIndex.length = 0;
  eachTile((c, f, i, j) => {
    if (c.t !== BELT || n >= MAX_BELTS) return;
    seatMatrix(f, i, j, c.d, 0, _mx);
    beltFrames.setMatrixAt(n, _mx);
    seatMatrix(f, i, j, c.d, 0.155, _mx);
    beltDecks.setMatrixAt(n, _mx);
    beltIndex[n] = { face: f, i, j };
    n++;
  });
  beltFrames.count = n; beltDecks.count = n;
  beltFrames.instanceMatrix.needsUpdate = true;
  beltDecks.instanceMatrix.needsUpdate = true;
  beltsDirty = false;
}

/** A throwable stand-in for a machine that is drawn as an instance. */
function pieceFor(face, i, j, c) {
  if (c.build) return c.build;
  if (c.t !== BELT) return null;
  const g = new THREE.Mesh(GEO.beltFrame, MAT.beltFrame);
  seat(g, face, i, j, c.d, 0);
  scene.add(g);
  return g;
}

// ── items: one InstancedMesh for every crystal in transit ──────────────────
const MAX_ITEMS = 4000;
const items = new THREE.InstancedMesh(
  new THREE.OctahedronGeometry(0.26, 0),
  new THREE.MeshStandardMaterial({ color: 0x7df9ff, emissive: 0x2aa6c4,
    emissiveIntensity: 1.4, roughness: 0.3, flatShading: true }),
  MAX_ITEMS);
items.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
items.frustumCulled = false;
items.count = 0;
// One mesh still, but two products: instanceColor is what lets a single draw
// call carry both. Reading a belt at a glance — "that line is running ingots,
// that one is still raw" — is most of what makes a factory legible.
items.instanceColor = new THREE.InstancedBufferAttribute(
  new Float32Array(MAX_ITEMS * 3), 3);
items.instanceColor.setUsage(THREE.DynamicDrawUsage);
scene.add(items);
const ITEM_COL = {
  [CRYSTAL]: new THREE.Color(0x7df9ff),
  [EMBER]: new THREE.Color(0xff8a3d),
  [SALT]: new THREE.Color(0xe8f0ff),
  [INGOT]: new THREE.Color(0x9fd6ff),
  [INGOT_E]: new THREE.Color(0xffae4d),
  [INGOT_S]: new THREE.Color(0xd8e2f5),
  [ALLOY]: new THREE.Color(0xff5ad9),
};

const _m = new THREE.Matrix4();
const _p = new THREE.Vector3();
const _q = new THREE.Quaternion();
const _s = new THREE.Vector3(1, 1, 1);
const _up = new THREE.Vector3(0, 1, 0);   // reused per item: the face normal

// ── the tick: belts advance, miners feed, the hub banks ────────────────────
let ore = 0;
let ingots = 0;
let alloys = 0;

// ── THE MARKET ─────────────────────────────────────────────────────────────
// A price per traded good, drifting on a mean-reverting random walk. The hub
// pays the live rate, so "which ingot should this line be making" becomes a
// question with an answer that changes — which is the thing a single-recipe
// factory can never have. The filter tile is how you act on it.
const TRADED = [INGOT, INGOT_E, INGOT_S, ALLOY];
const TRADE_NAME = { [INGOT]: 'crystal', [INGOT_E]: 'ember',
                     [INGOT_S]: 'salt', [ALLOY]: 'alloy' };
const TRADE_COL = { [INGOT]: '#9fd6ff', [INGOT_E]: '#ffae4d',
                    [INGOT_S]: '#d8e2f5', [ALLOY]: '#ff5ad9' };
const PRICE = {}, LAST_PRICE = {};
for (const t of TRADED) { PRICE[t] = 1; LAST_PRICE[t] = 1; }
const PRICE_MIN = 0.55, PRICE_MAX = 1.85;
let priceClock = 0;

function stepMarket(dt) {
  priceClock += dt;
  if (priceClock < 3.5) return;
  priceClock = 0;
  for (const t of TRADED) {
    LAST_PRICE[t] = PRICE[t];
    // mean reversion keeps a long session from parking every price at a rail,
    // which would quietly turn the market back off
    const drift = (1 - PRICE[t]) * 0.12;
    const shock = (Math.random() - 0.5) * 0.34;
    PRICE[t] = Math.max(PRICE_MIN, Math.min(PRICE_MAX, PRICE[t] + drift + shock));
  }
  renderTicker();
}

function renderTicker() {
  const box = document.getElementById('tick');
  if (!box) return;
  let html = '';
  for (const t of TRADED) {
    const up = PRICE[t] >= LAST_PRICE[t];
    html += '<div class="tr"><span style="color:' + TRADE_COL[t] + '">' +
      TRADE_NAME[t] + '</span><span class="' + (up ? 'u' : 'd') + '">' +
      PRICE[t].toFixed(2) + (up ? ' \u25b2' : ' \u25bc') + '</span></div>';
  }
  box.innerHTML = html;
}
let sinceTick = 0;
let minedWindow = 0;
let rateWindow = 0;
const rateBuckets = [];
let lastOreShown = -1;

function bank(type) {
  // the market only prices refined goods; raw ore always sells for its base
  const v = (VALUE[type] || 1) * (PRICE[type] || 1);
  ore += v; runValue += v;
  if (IS_INGOT(type)) ingots++;
  if (type === ALLOY) alloys++;
}

// One acceptance rule, asked by belts, miners and splitters alike. Having each
// of them decide separately is how a factory sim ends up with items that can
// enter a machine one way and not another for no reason the player can see.
function accepts(dst, type) {
  if (!dst) return false;
  if (dst.t === HUB) return true;
  if (dst.t === BELT || dst.t === SPLITTER || dst.t === FILTER) return !dst.item;
  // A smelter refines ONE kind at a time — mixing two ores in it would make
  // the alloy free, and the alloy is supposed to cost a trip across an edge.
  if (dst.t === SMELTER)
    return IS_MINERAL(type) && dst.buf < SMELT_IN * 2 &&
           (dst.buf === 0 || dst.bt === type);
  // A forge is the opposite rule: it wants two DIFFERENT minerals, so it
  // cannot be fed from a single face.
  if (dst.t === FORGE)
    return IS_MINERAL(type) && dst.cook === 0 &&
           (dst.fa === 0 || (dst.fb === 0 && type !== dst.fa));
  // a rift only takes back exactly what it lent — anything else rides past it,
  // which is what makes the filter tile the tool for repaying one
  if (dst.t === RIFT) return dst.dbt > 0 && type === dst.dmin;
  return false;
}
function deliver(dst, dx, dz, type) {
  if (dst.t === HUB) bank(type);
  else if (dst.t === SMELTER) { dst.buf++; dst.bt = type; }
  else if (dst.t === FORGE) { if (dst.fa === 0) dst.fa = type; else dst.fb = type; }
  else if (dst.t === RIFT) { if (--dst.dbt <= 0) riftSettle(dst, true); }
  else dst.item = type;
}

function step() {
  // Smelters run FIRST so a finished ingot leaves before the belts feeding
  // this smelter get their turn — otherwise a full input belt would block the
  // machine that is about to free it, and lines deadlock at exactly the
  // moment they start working.
  eachTile((c, f, i, j) => {
    if (c.t !== SMELTER && c.t !== FORGE) return;
    if (c.cook > 0) {
      c.cook--;
      if (c.cook === 0) {
        const out = c.t === FORGE ? ALLOY : (INGOT_OF[c.bt] || INGOT);
        const dst = cellOf(stepTile(f, i, j, c.d));
        if (dst && dst.t === HUB) bank(out);
        else if (dst && dst.t === BELT && !dst.item) dst.item = out;
        else c.cook = 1;                  // output blocked: hold it, retry
      }
    }
    if (c.t === SMELTER) {
      if (c.cook === 0 && c.buf >= SMELT_IN) { c.buf -= SMELT_IN; c.cook = SMELT_TICKS; }
    } else if (c.cook === 0 && c.fa && c.fb) {
      c.fa = 0; c.fb = 0; c.cook = FORGE_TICKS;
    }
    const lamp = c.build && c.build.getObjectByName('lamp');
    if (lamp) lamp.material.color.setHex(c.cook > 0 ? 0xffb04a : 0x3a2f5e);
  });

  // Collect first, THEN commit. Moving in place would let one item ride the
  // whole line in a single tick depending on iteration order.
  const moves = [];
  eachTile((c, f, i, j) => {
    // A SPLITTER IS A BELT THAT CHOOSES. It sends each item out of a
    // different side in turn, so one miner can feed two smelters without
    // the player hand-balancing anything. The round-robin cursor advances
    // only when an item actually LEAVES — advancing on a failed attempt
    // would silently starve whichever output happened to be busy.
    if (c.t === SPLITTER && c.item) {
      for (let k = 0; k < 4; k++) {
        const dir = (c.rr + k) % 4;
        const to = stepTile(f, i, j, dir);
        if (!to || !accepts(cellOf(to), c.item)) continue;
        moves.push([c, 'to', to]);
        c.rr = (dir + 1) % 4;
        break;
      }
      return;
    }
    // A FILTER IS A BELT THAT SORTS. Matching ore carries straight on;
    // anything else leaves out of the side. Crucially it does NOT fall back to
    // the other output when the chosen one is full — an item that took the
    // wrong exit because the right one was busy is a filter that silently
    // stops filtering, and the player would have no way to see it happen.
    if (c.t === FILTER && c.item) {
      const dir = c.item === c.filt ? c.d : (c.d + 1) % 4;
      const to = stepTile(f, i, j, dir);
      const dst = cellOf(to);
      if (!dst) return;
      if (dst.t === HUB) moves.push([c, 'bank']);
      else if (accepts(dst, c.item)) moves.push([c, 'to', to]);
      return;
    }
    if (c.t !== BELT || !c.item) return;
    const to = stepTile(f, i, j, c.d);
    const dst = cellOf(to);
    if (!dst) return;
    if (dst.t === HUB) moves.push([c, 'bank']);
    // a smelter only accepts CRYSTALS, and only while it has room. An ingot
    // arriving at a smelter simply waits, which is the correct answer and
    // also a visible one — the belt backs up and you can see the mistake.
    else if (accepts(dst, c.item)) moves.push([c, 'to', to]);
  });
  // ── TWO BELTS INTO ONE (2026-09-08) ───────────────────────────────────
  // Acceptance was decided while COLLECTING, against the state at the start of
  // the tick, and the commit trusted it. Two belts feeding the same tile both
  // passed, and the second deliver overwrote the first: a merge silently
  // DESTROYED one item every tick. In a game about throughput that is the
  // worst shape a bug can take — the line looks correct and the number is just
  // quietly lower than it should be, which reads as the game being balanced
  // that way.
  //
  // Re-checking at commit stops the loss. Rotating who goes first stops the
  // unfairness that would replace it: otherwise the winner is whoever eachTile
  // reached first, which is fixed by grid order, so one input starves forever.
  const byDst = new Map();
  for (const mv of moves) {
    if (mv[1] === 'bank') continue;
    const d = cellOf(mv[2]);
    const g = byDst.get(d);
    if (g) g.push(mv); else byDst.set(d, [mv]);
  }
  for (const [d, g] of byDst) {
    if (g.length < 2) continue;
    const k = (d.mrr | 0) % g.length;
    g.push(...g.splice(0, k));            // rotate: a different input leads
    d.mrr = (k + 1) % g.length;
  }
  const order = moves.filter(mv => mv[1] === 'bank');
  for (const g of byDst.values()) order.push(...g);
  for (const mv of order) {
    const c = mv[0];
    if (!c.item) continue;
    if (mv[1] === 'bank') { bank(c.item); c.item = 0; continue; }
    const dst = cellOf(mv[2]);
    if (!accepts(dst, c.item)) continue;   // another input reached it first
    deliver(dst, 0, 0, c.item);
    c.item = 0;
  }
  // a rift pays out the ore it lent one tile at a time, like a miner, so the
  // loan arrives on your belts instead of appearing in a counter
  eachTile((c, f, i, j) => {
    if (c.t !== RIFT || c.emit <= 0) return;
    const dst = cellOf(stepTile(f, i, j, c.d));
    if (accepts(dst, c.dmin)) { deliver(dst, 0, 0, c.dmin); c.emit--; }
  });
  eachTile((c, f, i, j) => {
    if (c.t !== MINER) return;
    // a miner digs whatever the seam under it is, which is the face's mineral
    const m = c.min || MINERAL_OF_FACE[f];
    const dst = cellOf(stepTile(f, i, j, c.d));
    if (accepts(dst, m)) deliver(dst, 0, 0, m);
  });
}

// Items are drawn BETWEEN their tile and the next, so the motion reads smooth
// even though the simulation is a discrete grid step. A blocked item sits
// still, which is what makes a jam legible.
function drawItems(alpha) {
  let n = 0;
  const spin = performance.now() * 0.002;
  eachTile((c, f, i, j) => {
    if (n >= MAX_ITEMS || !c.item) return;
    if (c.t !== BELT && c.t !== FILTER && c.t !== SPLITTER) return;
    // A splitter's next hop is not decided until the tick, and a filter's
    // depends on what it is holding. Items on a splitter therefore sit in the
    // middle of the tile — before this they were not drawn at all, so a
    // backed-up splitter looked empty.
    const dir = c.t === SPLITTER ? c.d
      : c.t === FILTER ? (c.item === c.filt ? c.d : (c.d + 1) % 4)
      : c.d;
    const to = c.t === SPLITTER ? null : stepTile(f, i, j, dir);
    const ahead = cellOf(to);
    const free = ahead && (ahead.t === HUB ||
      ((ahead.t === BELT || ahead.t === FILTER) && !ahead.item));
    const a = free ? alpha : 0;
    // Interpolating between the two tiles' world centres carries an item
    // around an edge on its own: across a corner the two centres are on
    // different faces, so the crystal cuts the corner instead of flying off
    // into space. That the tiles are never more than one diagonal apart is
    // one of the properties the cube-grid test pins down.
    const A = tileWorld(f, i, j), nrm = FACES[f].n;
    const B = ahead ? tileWorld(to.face, to.i, to.j) : A;
    _p.set(A[0] + (B[0] - A[0]) * a + nrm[0] * 0.42,
           A[1] + (B[1] - A[1]) * a + nrm[1] * 0.42,
           A[2] + (B[2] - A[2]) * a + nrm[2] * 0.42);
    _up.set(nrm[0], nrm[1], nrm[2]);
    _q.setFromAxisAngle(_up, spin);
    _m.compose(_p, _q, _s);
    items.setColorAt(n, ITEM_COL[c.item] || ITEM_COL[CRYSTAL]);
    items.setMatrixAt(n++, _m);
  });
  items.count = n;
  items.instanceMatrix.needsUpdate = true;
  if (items.instanceColor) items.instanceColor.needsUpdate = true;
  return n;
}

// ── input: raycast the ground plane, drag to draw belts ────────────────────
const ray = new THREE.Raycaster();
const ndc = new THREE.Vector2();
const hitPt = new THREE.Vector3();

/** The tile a world point sits over, or null if it is off the cube. */
function tileOfPoint(p) {
  const face = faceOfPoint(p.x, p.y, p.z), f = FACES[face];
  const a = p.x * f.u[0] + p.y * f.u[1] + p.z * f.u[2];
  const b = p.x * f.v[0] + p.y * f.v[1] + p.z * f.v[2];
  const i = Math.floor(a / T + N / 2), j = Math.floor(b / T + N / 2);
  if (i < 0 || j < 0 || i >= N || j >= N) return null;
  return { face, i, j };
}
let tool = 'miner';
let drawing = false;
let lastCell = null;

// In first person you aim with the CROSSHAIR, not the cursor — the pointer is
// locked and has no position. Overhead keeps the cursor. Reach is limited on
// foot for the obvious reason: a build game where you can place a machine on
// the far side of the island from where you stand is a board game again.
function cellUnder(ev) {
  if (overhead && ev) {
    ndc.set((ev.clientX / innerWidth) * 2 - 1, -(ev.clientY / innerHeight) * 2 + 1);
  } else {
    ndc.set(0, 0);
  }
  ray.setFromCamera(ndc, camera);
  // AIM AT THE SOLID, NOT AT A PLANE. The ground used to be the y=0 plane,
  // which on a cube would let you place machines on a face you are standing
  // inside of. Raycasting the cube itself means you build on the surface you
  // are actually looking at, whichever of the six it is.
  const hit = ray.intersectObject(cube, false)[0];
  if (!hit) return null;
  hitPt.copy(hit.point);
  if (!overhead && hitPt.distanceTo(camera.position) > REACH) return null;
  return tileOfPoint(hitPt);
}

// the ghost: what you are about to build, where you are about to build it
const ghost = new THREE.Mesh(
  new THREE.BoxGeometry(T * 0.92, 0.5, T * 0.92),
  new THREE.MeshBasicMaterial({ color: 0x6cf5d0, transparent: true, opacity: 0.28,
    depthWrite: false }));
ghost.visible = false;
scene.add(ghost);
const ghostEdge = new THREE.LineSegments(
  new THREE.EdgesGeometry(new THREE.BoxGeometry(T * 0.92, 0.5, T * 0.92)),
  new THREE.LineBasicMaterial({ color: 0x9dffe8, transparent: true, opacity: 0.85 }));
ghost.add(ghostEdge);

function updateGhost() {
  const t = cellUnder(null);
  if (!t) { ghost.visible = false; return; }
  const c = cellOf(t);
  const legal = tool === 'erase' ? (c.t !== EMPTY && c.t !== NODE)
    : tool === 'miner' ? c.t === NODE
    : c.t !== NODE;
  ghost.visible = true;
  seat(ghost, t.face, t.i, t.j, 0, 0.26);
  ghost.material.color.setHex(legal ? 0x6cf5d0 : 0xff6b7d);
  ghostEdge.material.color.setHex(legal ? 0x9dffe8 : 0xffa8b4);
}

// WHICH WAY DID THE DRAG GO. On a flat grid this was a subtraction of indices.
// Across an edge the two tiles are not in the same coordinate system at all,
// so the question is asked the only way that stays true: try each of the four
// headings and see which one actually steps from a to b.
function dirBetween(a, b) {
  for (let d = 0; d < 4; d++) {
    const s = stepTile(a.face, a.i, a.j, d);
    if (s && s.face === b.face && s.i === b.i && s.j === b.j) return d;
  }
  return null;
}

function apply(t, dir) {
  if (!UNLOCKED[tool]) return;      // hotkeys and drags go through here too
  const d = dir == null ? 0 : dir;
  if (tool === 'erase') { removeAt(t.face, t.i, t.j); return; }
  if (tool === 'miner') { place(t.face, t.i, t.j, MINER, d); return; }
  if (tool === 'hub') { place(t.face, t.i, t.j, HUB, 0); return; }
  if (tool === 'smelter') { place(t.face, t.i, t.j, SMELTER, d); return; }
  if (tool === 'splitter') { place(t.face, t.i, t.j, SPLITTER, 0); return; }
  if (tool === 'forge') { place(t.face, t.i, t.j, FORGE, d); return; }
  if (tool === 'filter') { place(t.face, t.i, t.j, FILTER, d); return; }
  if (tool === 'rift') { place(t.face, t.i, t.j, RIFT, d); return; }
  if (tool === 'belt') { place(t.face, t.i, t.j, BELT, d); }
}

renderer.domElement.addEventListener('pointerdown', e => {
  if (e.button !== 0) return;
  // INSPECTING IS LOOKING, NOT BUILDING (2026-09-07). The studio arms Inspect
  // to let someone click things and read what they are; with the build path
  // still live, every one of those clicks dropped a machine on the world they
  // were trying to examine.
  if (inspectOn) return;
  const c = cellUnder(e);
  if (!c) return;
  drawing = true;
  lastCell = c;
  apply(c, null);
});
renderer.domElement.addEventListener('pointermove', e => {
  if (inspectOn || !drawing || !lastCell) return;
  const c = cellUnder(e);
  if (!c || (c.face === lastCell.face && c.i === lastCell.i && c.j === lastCell.j)) return;
  const d = dirBetween(lastCell, c);
  if (d == null) { lastCell = c; return; }
  // the tile we just left now points at the one we moved to
  const prev = cellOf(lastCell);
  if (prev.t === BELT || prev.t === MINER) {
    prev.d = d;
    if (prev.t === BELT) beltsDirty = true;
    else if (prev.build) seat(prev.build, lastCell.face, lastCell.i, lastCell.j, d, 0);
  }
  // the drag arrives on the new tile heading the same way it left the old one,
  // which across an edge is NOT the direction the mouse moved
  const sd = stepTile(lastCell.face, lastCell.i, lastCell.j, d);
  apply(c, sd ? sd.d : d);
  lastCell = c;
});
addEventListener('pointerup', () => { drawing = false; lastCell = null; });

// Point at a filter and press F. A short cycle rather than a text box: the
// same decision space as a script, with nothing to parse, nothing to corrupt a
// shared save, and no typing in a first-person game.
function cycleFilter() {
  const t = cellUnder(null);
  if (!t) return;
  const c = cellOf(t);
  if (c.t !== FILTER) return;
  const k = MINERALS.indexOf(c.filt);
  c.filt = MINERALS[(k + 1) % MINERALS.length];
  const gate = c.build && c.build.getObjectByName('gate');
  if (gate) {
    gate.material.color.setHex(MIN_COL[c.filt]);
    gate.material.emissive.setHex(MIN_COL[c.filt]);
  }
}

function pickTool(name) {
  if (!UNLOCKED[name]) {
    // say WHY, rather than ignoring the click. A control that does nothing and
    // explains nothing is indistinguishable from a broken one.
    const el = document.querySelector('.tool[data-tool="' + name + '"]');
    if (el) { el.classList.add('deny'); setTimeout(() => el.classList.remove('deny'), 320); }
    const t = document.getElementById('toast');
    if (t && goalIdx < GOALS.length) {
      t.textContent = 'locked — ' + GOALS[goalIdx].text;
      t.classList.add('on'); toastAt = 2.2;
    }
    return;
  }
  tool = name;
  document.querySelectorAll('.tool').forEach(o =>
    o.classList.toggle('on', o.dataset.tool === name));
}
document.querySelectorAll('.tool').forEach(el => {
  el.addEventListener('pointerdown', ev => { ev.stopPropagation(); pickTool(el.dataset.tool); });
});
addEventListener('keydown', e => {
  const k = { '1': 'miner', '2': 'belt', '3': 'smelter', '4': 'splitter',
              '5': 'hub', '6': 'forge', '7': 'filter', '8': 'rift',
              '9': 'erase' }[e.key];
  if (k) pickTool(k);
  if (e.code === 'KeyF') cycleFilter();
  const u = { 'KeyZ': 'tick', 'KeyX': 'yield', 'KeyC': 'smelt' }[e.code];
  if (u) buy(u);
});

// ── YOU ARE ON THE ISLAND ───────────────────────────────────────────────────
// Arranging a factory on a board and STANDING IN ONE are different games. The
// second is the one people lose evenings to, because a belt you walked beside
// is yours in a way a belt you dragged on a grid is not. First person is the
// default; the overhead view stays on Tab because routing a junction from eye
// level is genuinely worse than seeing it from above, and a build game needs
// both.
const EYE = 1.68, REACH = 12;
const player = {
  pos: new THREE.Vector3(0, HALF + EYE, 0),
  face: 0,
  // The heading is a WORLD vector tangent to the current face, not a yaw
  // angle. A yaw needs a reference direction per face, and the six of them
  // cannot be made to agree along every edge — one seam always ends up with
  // the player spinning as they cross it.
  fwd: new THREE.Vector3(0, 0, -1),
  up: new THREE.Vector3(0, 1, 0),
  h: 0, vy: 0,
  // starts looking DOWN at the ground. Level-eyed, the surface is metres
  // beyond arm's reach and the build ghost simply never appears — you would
  // be standing in a build game with no way to tell why nothing can be placed.
  pitch: -0.38, onGround: true,
};
// the camera's up lags the player's by a few frames, so crossing an edge
// ROLLS the world over instead of snapping it. This is the shot the whole
// mechanic exists for; a hard cut throws it away.
const camUp = new THREE.Vector3(0, 1, 0);
let overhead = false;
// FRAMED FOR A CUBE, NOT A SLAB (2026-09-07). A fixed 46m orbit was outside a
// flat island and INSIDE a worldlet — Tab showed you a dark field of grid
// lines and nothing else. Every distance here is a multiple of the world.
let orbYaw = 0.72, orbPitch = 0.62, orbDist = HALF * 4.4;

const keys = Object.create(null);
addEventListener('keydown', e => {
  keys[e.code] = true;
  if (e.code === 'Tab') { e.preventDefault(); overhead = !overhead; }
});
addEventListener('keyup', e => { keys[e.code] = false; });
addEventListener('contextmenu', e => e.preventDefault());

// pointer lock is what makes it feel embodied rather than operated
renderer.domElement.addEventListener('click', () => {
  if (!overhead && document.pointerLockElement !== renderer.domElement) {
    renderer.domElement.requestPointerLock();
  }
});
addEventListener('mousemove', e => {
  if (document.pointerLockElement !== renderer.domElement) return;
  // turning is a rotation about whichever way is up HERE
  player.fwd.applyAxisAngle(player.up, -e.movementX * 0.0022).normalize();
  player.pitch = Math.max(-1.45, Math.min(1.35, player.pitch - e.movementY * 0.0022));
});
addEventListener('wheel', e => {
  if (overhead) orbDist = Math.max(HALF * 1.5, Math.min(HALF * 6, orbDist * (1 + Math.sign(e.deltaY) * 0.09)));
}, { passive: true });
addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

// Belts and filters are ankle-high and you walk over them; everything else on
// the grid is something you walk around. An ore seam counts — it is a metre of
// crystal standing out of the ground, and phasing through one looked worse
// than phasing through a machine.
const SOLID_T = { 1: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 9: 1 };
const PLAYER_R = 0.4;

/** Is the player's circle, at face-local (a,b), overlapping a solid tile? */
function solidAt(face, a, b) {
  const lo = PLAYER_R + T / 2;
  const ci = Math.floor(a / T + N / 2), cj = Math.floor(b / T + N / 2);
  for (let i = ci - 1; i <= ci + 1; i++) {
    for (let j = cj - 1; j <= cj + 1; j++) {
      if (i < 0 || j < 0 || i >= N || j >= N) continue;   // an edge is not a wall
      if (!SOLID_T[cells[face][i][j].t]) continue;
      const cx = (i + 0.5 - N / 2) * T, cz = (j + 0.5 - N / 2) * T;
      if (Math.abs(a - cx) < lo && Math.abs(b - cz) < lo) return true;
    }
  }
  return false;
}

const _rt = new THREE.Vector3(), _wish = new THREE.Vector3();
const _n3 = new THREE.Vector3(), _oldN = new THREE.Vector3();
const _qr = new THREE.Quaternion();
const faceNormal = (face, out) => {
  const n = FACES[face].n; return out.set(n[0], n[1], n[2]);
};

function movePlayer(dt) {
  faceNormal(player.face, _n3);
  player.up.copy(_n3);
  // keep the heading tangent to the face actually underfoot
  player.fwd.addScaledVector(_n3, -player.fwd.dot(_n3));
  if (player.fwd.lengthSq() < 1e-8) {
    const u = FACES[player.face].u; player.fwd.set(u[0], u[1], u[2]);
  }
  player.fwd.normalize();
  _rt.crossVectors(player.fwd, _n3).normalize();

  _wish.set(0, 0, 0);
  if (keys['KeyW']) _wish.add(player.fwd);
  if (keys['KeyS']) _wish.sub(player.fwd);
  if (keys['KeyD']) _wish.add(_rt);
  if (keys['KeyA']) _wish.sub(_rt);
  if (_wish.lengthSq() > 0) _wish.normalize();
  const speed = keys['ShiftLeft'] ? 11 : 6.2;

  // gravity points at the face you are on, so "down" is a different world
  // direction depending on where you are standing
  if (keys['Space'] && player.onGround) { player.vy = 6.4; player.onGround = false; }
  player.vy -= 19 * dt;
  player.h += player.vy * dt;
  if (player.h <= 0) { player.h = 0; player.vy = 0; player.onGround = true; }

  // ── WALKING INTO THINGS (2026-09-08) ──────────────────────────────────
  // You could walk through your own factory, which reads as the machines not
  // being there. Resolved in FACE-LOCAL coordinates rather than world ones:
  // on the underside of the cube "x" and "z" mean nothing, but the face's own
  // u and v axes always mean along-the-tiles.
  //
  // Each axis is tried on its own so a shoulder against a smelter slides along
  // it instead of stopping dead — a factory is a corridor maze and stopping
  // dead in one is miserable.
  const fc = FACES[player.face];
  let pa = player.pos.x * fc.u[0] + player.pos.y * fc.u[1] + player.pos.z * fc.u[2];
  let pb = player.pos.x * fc.v[0] + player.pos.y * fc.v[1] + player.pos.z * fc.v[2];
  const da = (_wish.x * fc.u[0] + _wish.y * fc.u[1] + _wish.z * fc.u[2]) * speed * dt;
  const db = (_wish.x * fc.v[0] + _wish.y * fc.v[1] + _wish.z * fc.v[2]) * speed * dt;
  // If you are ALREADY inside something — a machine placed on top of you, a
  // save restored under a smelter — collision is skipped entirely this frame.
  // A player who cannot move is a bug report; a player who can walk out of a
  // wall is a shrug.
  const stuck = solidAt(player.face, pa, pb);
  if (!stuck) {
    if (!solidAt(player.face, pa + da, pb)) pa += da;
    if (!solidAt(player.face, pa, pb + db)) pb += db;
  } else { pa += da; pb += db; }
  const ph = HALF + EYE + player.h;
  player.pos.set(fc.n[0] * ph + fc.u[0] * pa + fc.v[0] * pb,
                 fc.n[1] * ph + fc.u[1] * pa + fc.v[1] * pb,
                 fc.n[2] * ph + fc.u[2] * pa + fc.v[2] * pb);

  // WALKING OFF AN EDGE. Two passes, because a corner crosses two edges in a
  // single frame at a run. The heading is carried across by the rotation that
  // takes the old normal onto the new one — a projection cannot do it: walk
  // straight off an edge and your forward direction IS the new face's normal,
  // which projects to nothing.
  for (let pass = 0; pass < 2; pass++) {
    const f = FACES[player.face];
    const a = player.pos.dot(_rt.set(f.u[0], f.u[1], f.u[2]));
    const b = player.pos.dot(_rt.set(f.v[0], f.v[1], f.v[2]));
    let over = null;
    if (a > HALF) over = f.u;
    else if (a < -HALF) over = _ng(f.u);
    else if (b > HALF) over = f.v;
    else if (b < -HALF) over = _ng(f.v);
    if (!over) break;
    let nf = -1;
    for (let k = 0; k < 6; k++) if (_eqv(FACES[k].n, over)) { nf = k; break; }
    if (nf < 0) break;
    _oldN.copy(player.up);
    faceNormal(nf, _n3);
    _qr.setFromUnitVectors(_oldN, _n3);
    player.fwd.applyQuaternion(_qr).normalize();
    player.face = nf;
    player.up.copy(_n3);
    player.h = 0; player.vy = 0; player.onGround = true;
    // RE-SEAT IMMEDIATELY, not after the loop (2026-09-07). Left until the
    // end, the second pass read a position that was still measured against
    // the OLD face: standing eye-height above the top face reads as 1.68m
    // off the side face's edge, so the player crossed straight back and the
    // net effect was a wall you could not walk over. The two passes exist for
    // corners; they only mean anything once each one lands.
    seatPlayer();
  }
  seatPlayer();
}

// Sit exactly eye-height (plus any jump) above the current face, inside its
// square. This is the only place the player's world position is written from
// face coordinates, which is why crossing an edge is a change of two numbers
// rather than a special case for each of the twelve edges.
function seatPlayer() {
  const f = FACES[player.face];
  const lim = HALF - 0.05;
  const a = Math.max(-lim, Math.min(lim,
    player.pos.x * f.u[0] + player.pos.y * f.u[1] + player.pos.z * f.u[2]));
  const b = Math.max(-lim, Math.min(lim,
    player.pos.x * f.v[0] + player.pos.y * f.v[1] + player.pos.z * f.v[2]));
  const up = HALF + EYE + player.h;
  player.pos.set(f.n[0] * up + f.u[0] * a + f.v[0] * b,
                 f.n[1] * up + f.u[1] * a + f.v[1] * b,
                 f.n[2] * up + f.u[2] * a + f.v[2] * b);
}

// ── a starter line, so the loop is legible the moment it loads ─────────────
// Called again after every meltdown: a prestige that drops you onto an empty
// cube with no line running is indistinguishable from having lost.
function seedLine(placePlayer) {
  // Pick a node with a CLEAR run east of it. The first version just took the
  // first node it found and drew six tiles east regardless — a second node
  // sitting in that line silently refused two placements, so the demo line
  // ended in mid-air with no hub and delivered nothing. A starter line that
  // does not complete the loop teaches the player the wrong thing.
  // On the top face, so the game opens on the orientation people expect —
  // the other five are discovered by walking there.
  const RUN = 6, F = 0;
  let found = null;
  for (let i = 2; i < N - RUN - 1 && !found; i++) {
    for (let j = 2; j < N - 2 && !found; j++) {
      if (cells[F][i][j].t !== NODE) continue;
      let clear = true;
      for (let k = 1; k <= RUN && clear; k++) clear = cells[F][i + k][j].t === EMPTY;
      if (clear) found = [i, j];
    }
  }
  if (!found) return;
  const x = found[0], z = found[1];
  place(F, x, z, MINER, 0);
  place(F, x + 1, z, BELT, 0);
  place(F, x + 2, z, BELT, 0);
  place(F, x + 3, z, SMELTER, 0);     // two crystals in, one ingot out
  place(F, x + 4, z, BELT, 0);
  place(F, x + 5, z, BELT, 0);
  place(F, x + RUN, z, HUB, 0);

  // STAND WHERE THE LOOP IS (2026-09-07). A fixed spawn on the south edge left
  // the whole starter line behind the player on a large grid: the game was
  // running perfectly and the first frame showed bare ground. Put the camera
  // just south of the middle of the line, looking along it, so the first thing
  // anyone sees — player or screenshot gate — is ore actually moving.
  // BEHIND the line, not past the edge. The top face's v axis is -Z, so the
  // tile "in front of" the player is j+1; standing at j+4 put the spawn four
  // tiles PAST the line and, on a line near the far edge, off the face
  // entirely — where the clamp pinned it and W did nothing at all.
  const w = tileWorld(F, x + RUN / 2, Math.max(1, Math.min(N - 2, z - 4)));
  player.pos.set(w[0], HALF + EYE, w[2]);
  player.face = F;
  player.up.set(0, 1, 0);
  camUp.set(0, 1, 0);
  // FACES[0].v is -Z, so the line we just built lies that way
  if (!placePlayer) return;
  player.fwd.set(0, 0, -1);
}
seedLine(true);

// ── THE CHRONOS RIFT ───────────────────────────────────────────────────────
// A rift lends you ore and names its price on the HUD: this much of THAT ore,
// back through the same ring, before the clock runs out. Pay and it settles at
// triple the market rate. Miss and it throws every machine near it into the
// sky — the meltdown's debris path, aimed at you rather than chosen by you.
//
// The borrowed ore is deliberately whichever one the market currently pays
// most for, so a rift is a bet on a price you can see moving, and the filter
// tile is how you route the repayment back without unpicking your line.
const RIFT_COUNT = 6;        // ore lent per opening
const RIFT_WINDOW = 45;      // seconds to pay it back
const RIFT_COOL = 22;        // seconds shut afterwards
const RIFT_BLAST = 3;        // tiles of factory it takes when it is not paid

function riftOpen(c) {
  // borrow against the best price on the board
  let best = MINERALS[0];
  for (const m of MINERALS) if (PRICE[INGOT_OF[m]] > PRICE[INGOT_OF[best]]) best = m;
  c.dmin = best;
  c.dbt = RIFT_COUNT;
  c.emit = RIFT_COUNT;
  c.left = RIFT_WINDOW;
  c.cool = 0;
}

function riftSettle(c, paid) {
  if (paid) {
    const v = (VALUE[INGOT_OF[c.dmin]] || 6) * (PRICE[INGOT_OF[c.dmin]] || 1)
              * RIFT_COUNT * 0.5;
    ore += v; runValue += v;
  }
  c.dbt = 0; c.emit = 0; c.left = 0; c.dmin = 0;
  c.cool = RIFT_COOL;
}

// The storm. Everything within RIFT_BLAST tiles ON THE SAME FACE is thrown —
// same face because a blast that reached around an edge would be impossible to
// read, and the player has to be able to see what they are risking.
function riftStorm(f, i, j) {
  beltsDirty = true;
  for (let a = Math.max(0, i - RIFT_BLAST); a <= Math.min(N - 1, i + RIFT_BLAST); a++) {
    for (let b = Math.max(0, j - RIFT_BLAST); b <= Math.min(N - 1, j + RIFT_BLAST); b++) {
      const c = cells[f][a][b];
      if (c.t === EMPTY || c.t === NODE || c.t === RIFT) continue;
      const piece = pieceFor(f, a, b, c);
      if (piece) { throwPiece(piece); c.build = null; }
      c.t = c.mesh ? NODE : EMPTY;
      c.item = 0; c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0;
    }
  }
  melting = Math.max(melting, 1.2);
  refreshCounts();
}

function stepRifts(dt) {
  eachTile((c, f, i, j) => {
    if (c.t !== RIFT) return;
    if (c.cool > 0) {
      c.cool -= dt;
      if (c.cool <= 0) riftOpen(c);
    } else if (c.left > 0) {
      // THE CLOCK STARTS WHEN THE LOAN LANDS (2026-09-07). Counting down while
      // the rift still had ore to pay out meant a rift with a blocked output
      // demanded repayment of something it had never handed over, and then
      // blew up the factory for not returning it.
      if (c.emit === 0) c.left -= dt;
      if (c.left <= 0) { riftStorm(f, i, j); riftSettle(c, false); }
    } else if (c.dbt === 0 && c.emit === 0) {
      riftOpen(c);                     // a freshly placed rift opens at once
    }
    const lamp = c.build && c.build.getObjectByName('lamp');
    if (lamp) lamp.material.color.setHex(
      c.dbt > 0 ? (MIN_COL[c.dmin] || 0xff5ad9) : 0x2a2050);
    const ring = c.build && c.build.getObjectByName('ring');
    if (ring) ring.rotation.z += dt * (c.dbt > 0 ? 2.4 : 0.4);
  });
}

// ── the meltdown itself ────────────────────────────────────────────────────
// The machines are not deleted, they are THROWN. Every build group is detached
// from its tile, given an outward velocity off the cube and a tumble, and left
// to shrink into nothing over a couple of seconds. The engine side of this
// project has shipped physics-driven destruction before; here it is two lines
// of integration per frame, and it is the only moment in the game that is
// worth filming.
const debris = [];
let melting = 0;

// ONE PLACE THAT THROWS A MACHINE. The meltdown chooses to do this and the
// rift storm does it to you, and the two looking different would read as a
// bug rather than as two causes of the same event.
function throwPiece(g) {
  const p = g.position;
  const r = Math.max(1e-3, Math.hypot(p.x, p.y, p.z));
  debris.push({
    o: g,
    // SLOW ENOUGH TO WATCH (2026-09-07). The first pass threw everything at
    // 9-25 m/s and the entire factory was out of frame inside 300ms — the one
    // moment in the game worth filming, over before a screenshot could catch
    // it. Pieces arc out and fall back toward the cube.
    v: new THREE.Vector3(
      p.x / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4,
      p.y / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4,
      p.z / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4),
    w: new THREE.Vector3((Math.random() - 0.5) * 9,
                         (Math.random() - 0.5) * 9,
                         (Math.random() - 0.5) * 9),
  });
}

function meltdown() {
  if (ore < MELT_MIN || melting > 0) return;
  const won = Math.max(1, coresFor(runValue));
  cores += won;

  eachTile((c, f, i, j) => {
    const piece = pieceFor(f, i, j, c);
    if (piece) {
      throwPiece(piece);
      c.build = null;
    }
    // a node outlives the factory built on it, exactly as it does for ERASE
    c.t = c.mesh ? NODE : EMPTY;
    c.item = 0; c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0; c.rr = 0;
  });

  ore = 0; ingots = 0; runValue = 0;
  beltsDirty = true;
  for (const k in UPGRADES) UPGRADES[k].lvl = 0;
  applyUpgrades();
  renderUpgrades();
  items.count = 0;
  melting = 2.4;
  refreshCounts();
  document.getElementById('tok').textContent = cores;
}

function stepDebris(dt) {
  for (let k = debris.length - 1; k >= 0; k--) {
    const d = debris[k];
    // the worldlet still pulls: pieces arc out and come back, which reads as
    // a collapse rather than as a scene being deleted
    const p = d.o.position;
    const r = Math.max(1e-3, Math.hypot(p.x, p.y, p.z));
    d.v.addScaledVector(_bx.set(p.x / r, p.y / r, p.z / r), -7 * dt);
    p.addScaledVector(d.v, dt);
    d.o.rotateX(d.w.x * dt); d.o.rotateY(d.w.y * dt); d.o.rotateZ(d.w.z * dt);
    const sc = Math.max(0, d.o.scale.x - dt * 0.42);
    d.o.scale.setScalar(sc);
    if (sc <= 0.02) { scene.remove(d.o); debris.splice(k, 1); }
  }
}

{
  const btn = document.getElementById('melt');
  if (btn) btn.addEventListener('pointerdown', ev => { ev.stopPropagation(); meltdown(); });
}

// ── PROGRESSION ────────────────────────────────────────────────────────────
// Ordered so each unlock lands when the previous one has made it mean
// something: routing before sorting, and the FORGE only after you have stood
// on a second face and seen that the ore there is a different colour. A player
// who never walks over an edge never learns the thing this game is for, so it
// is a goal rather than a hope.
const visitedFaces = new Set();
const START_TOOLS = ['miner', 'belt', 'smelter', 'hub', 'erase'];
const UNLOCKED = {};
for (const k of START_TOOLS) UNLOCKED[k] = 1;
let goalIdx = 0;

const GOALS = [
  { text: 'bank 40 value', unlock: 'splitter',
    tip: 'the hub buys anything that reaches it',
    got: 'SPLITTER — one line can feed two machines',
    done: () => ore >= 40 },
  { text: 'stand on a second face', unlock: 'forge',
    tip: 'walk over an edge; the world turns under you',
    got: 'FORGE — two different ores in, one alloy out',
    done: () => visitedFaces.size >= 2 },
  { text: 'forge one alloy', unlock: 'filter',
    tip: 'no single face grows two ores, so a belt has to cross',
    got: 'FILTER — point at it and press F to sort by ore',
    done: () => alloys >= 1 },
  { text: 'bank 250 value', unlock: 'rift',
    tip: 'the market moves; make whatever it is paying for',
    got: 'CHRONOS RIFT — borrowed ore, on a deadline',
    done: () => ore >= 250 },
  { text: 'bank ' + MELT_MIN + ' value', unlock: 'meltdown',
    tip: 'enough of a factory to be worth destroying',
    got: 'MELTDOWN — collapse it all for a permanent core',
    done: () => ore >= MELT_MIN },
];

function renderGoal() {
  const el = document.getElementById('goal');
  if (el) {
    if (goalIdx >= GOALS.length) {
      el.innerHTML = '<b>ALL SYSTEMS ONLINE</b><small>the worldlet is yours</small>';
    } else {
      const g = GOALS[goalIdx];
      el.innerHTML = '<b>' + g.text.toUpperCase() + '</b><small>' + g.tip + '</small>';
    }
  }
  // the locked tools stay VISIBLE, dimmed. A tool you can see and cannot use
  // yet is a reason to keep playing; a tool that appears from nowhere is a
  // surprise you have to re-read the bar to notice.
  document.querySelectorAll('.tool').forEach(o =>
    o.classList.toggle('locked', !UNLOCKED[o.dataset.tool]));
}

let toastAt = 0;
function stepGoals(dt) {
  while (goalIdx < GOALS.length && GOALS[goalIdx].done()) {
    const g = GOALS[goalIdx];
    UNLOCKED[g.unlock] = 1;
    goalIdx++;
    const t = document.getElementById('toast');
    if (t) { t.textContent = g.got; t.classList.add('on'); toastAt = 3.5; }
    renderGoal();
  }
  if (toastAt > 0) {
    toastAt -= dt;
    if (toastAt <= 0) {
      const t = document.getElementById('toast');
      if (t) t.classList.remove('on');
    }
  }
}

// ── SAVE / LOAD ────────────────────────────────────────────────────────────
// One key per title, so two games exported from the studio do not overwrite
// each other's worlds. Every access is wrapped: storage throws outright in
// some privacy modes, and a game that will not start because it could not read
// a save is worse than a game that forgets.
const SAVE_KEY = 'fs-factory-' +
  String(SPEC.title || 'untitled').toLowerCase().replace(/[^a-z0-9]+/g, '-');
// v2 adds the progression. A v1 save still loads: the goal chain re-derives
// itself from what you have banked on the next frame, so an old world comes
// back with its unlocks intact rather than being refused.
const SAVE_V = 2;

function clearFactory() {
  beltsDirty = true;
  eachTile(c => {
    if (c.build) { scene.remove(c.build); c.build = null; }
    c.t = c.mesh ? NODE : EMPTY;
    c.item = 0; c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0; c.rr = 0;
    c.dbt = 0; c.dmin = 0; c.emit = 0; c.left = 0; c.cool = 0;
  });
  items.count = 0;
}

function saveState() {
  const m = [];
  eachTile((c, f, i, j) => {
    if (c.t === EMPTY || c.t === NODE) return;
    m.push([f, i, j, c.t, c.d, c.item | 0, c.buf | 0, c.bt | 0, c.fa | 0,
            c.fb | 0, c.cook | 0, c.rr | 0, c.filt | 0, c.dbt | 0, c.dmin | 0,
            c.emit | 0, Math.round(c.left || 0), Math.round(c.cool || 0)]);
  });
  return {
    v: SAVE_V, n: N, ore, ingots, alloys, cores, runValue,
    up: { tick: UPGRADES.tick.lvl, yield: UPGRADES.yield.lvl,
          smelt: UPGRADES.smelt.lvl },
    price: TRADED.map(t => PRICE[t]),
    p: { face: player.face, pos: player.pos.toArray(),
         fwd: player.fwd.toArray(), pitch: player.pitch },
    g: goalIdx, u: Object.keys(UNLOCKED), vf: [...visitedFaces],
    m,
  };
}

function loadState(d) {
  // A SAVE FROM A DIFFERENT WORLD IS NOT A SAVE. The ore seams are generated
  // from a seeded RNG keyed to the grid size; restoring machines onto a
  // different N would put miners on empty ground and leave seams buried under
  // belts, with nothing to indicate why the factory had stopped earning.
  if (!d || !(d.v >= 1 && d.v <= SAVE_V) || d.n !== N) return false;
  clearFactory();
  for (const r of d.m) {
    const [f, i, j, t, dir] = r;
    if (f < 0 || f > 5 || i < 0 || j < 0 || i >= N || j >= N) continue;
    if (!place(f, i, j, t, dir)) continue;
    const c = cells[f][i][j];
    c.item = r[5]; c.buf = r[6]; c.bt = r[7]; c.fa = r[8]; c.fb = r[9];
    c.cook = r[10]; c.rr = r[11]; c.filt = r[12] || CRYSTAL;
    c.dbt = r[13]; c.dmin = r[14]; c.emit = r[15];
    c.left = r[16]; c.cool = r[17];
    const gate = c.build && c.build.getObjectByName('gate');
    if (gate) { gate.material.color.setHex(MIN_COL[c.filt]);
                gate.material.emissive.setHex(MIN_COL[c.filt]); }
  }
  ore = +d.ore || 0; ingots = d.ingots | 0; alloys = d.alloys | 0;
  cores = d.cores | 0; runValue = +d.runValue || 0;
  if (d.up) for (const k in UPGRADES)
    UPGRADES[k].lvl = Math.max(0, Math.min(UPGRADES[k].cap, d.up[k] | 0));
  if (d.price) TRADED.forEach((t, k) => {
    const v = +d.price[k];
    if (isFinite(v)) PRICE[t] = LAST_PRICE[t] =
      Math.max(PRICE_MIN, Math.min(PRICE_MAX, v));
  });
  if (d.p) {
    player.face = d.p.face | 0;
    if (d.p.pos) player.pos.fromArray(d.p.pos);
    if (d.p.fwd) player.fwd.fromArray(d.p.fwd);
    player.pitch = +d.p.pitch || 0;
    faceNormal(player.face, player.up);
    camUp.copy(player.up);
  }
  goalIdx = Math.max(0, Math.min(GOALS.length, d.g | 0));
  if (Array.isArray(d.u)) for (const k of d.u) UNLOCKED[k] = 1;
  visitedFaces.clear();
  if (Array.isArray(d.vf)) for (const f of d.vf) visitedFaces.add(f | 0);
  visitedFaces.add(player.face);
  applyUpgrades(); renderUpgrades(); renderTicker(); refreshCounts(); renderGoal();
  document.getElementById('tok').textContent = cores;
  return true;
}

function save() {
  try { localStorage.setItem(SAVE_KEY, JSON.stringify(saveState())); return true; }
  catch (e) { return false; }
}
function load() {
  try {
    const raw = localStorage.getItem(SAVE_KEY);
    return raw ? loadState(JSON.parse(raw)) : false;
  } catch (e) { return false; }
}
function wipe() {
  try { localStorage.removeItem(SAVE_KEY); } catch (e) {}
  clearFactory();
  ore = 0; ingots = 0; alloys = 0; cores = 0; runValue = 0;
  for (const k in UPGRADES) UPGRADES[k].lvl = 0;
  goalIdx = 0;
  for (const k in UNLOCKED) if (!START_TOOLS.includes(k)) delete UNLOCKED[k];
  visitedFaces.clear();
  applyUpgrades(); renderUpgrades(); renderGoal();
  seedLine(true);
  refreshCounts();
  document.getElementById('tok').textContent = cores;
}

// A LINK THAT STARTS A NEW WORLD. Useful to a player who wants to hand someone
// a clean copy, and the only reliable way for a test to get a fresh boot: a
// harness that clears storage from inside the page has it written straight back
// by the beforeunload save that the next navigation fires.
const FRESH = /[?&](fresh|new)=1/.test(location.search);
if (FRESH) { try { localStorage.removeItem(SAVE_KEY); } catch (e) {} }
// the starter line is what a NEW world looks like; a save replaces it whole
const restored = FRESH ? false : load();

let saveClock = 0;
// beforeunload is not reliable on mobile or when a tab is discarded, so the
// periodic write is the real save and this is only the tidy case
addEventListener('beforeunload', save);
addEventListener('visibilitychange', () => { if (document.hidden) save(); });

{
  const h = document.querySelector('#hud h1');
  if (h) h.textContent = (SPEC.title || 'FACTORY').toUpperCase();
  const w = document.getElementById('wipe');
  if (w) w.addEventListener('pointerdown', ev => {
    ev.stopPropagation();
    // a wipe is not undoable, so it asks once — but only once, because a
    // confirm on every click is its own kind of hostile
    if (w.dataset.armed) { wipe(); save(); w.dataset.armed = ''; w.textContent = 'new world'; }
    else { w.dataset.armed = '1'; w.textContent = 'wipe this world?'; }
  });
}
applyUpgrades();
renderUpgrades();
renderTicker();
renderGoal();

// ── frame ──────────────────────────────────────────────────────────────────
let last = performance.now();
renderer.setAnimationLoop(() => {
  const now = performance.now();
  const dt = Math.min(0.1, (now - last) / 1000);
  last = now;

  stepMarket(dt);
  visitedFaces.add(player.face);
  stepGoals(dt);
  if (!melting) stepRifts(dt);
  saveClock += dt;
  if (saveClock >= 10) { saveClock = 0; save(); }
  if (melting > 0) {
    melting = Math.max(0, melting - dt);
    // the replacement line arrives when the old one has finished falling, not
    // while it is still in the air — otherwise the collapse and the rebuild
    // are the same frame and neither reads
    if (melting === 0) { seedLine(false); refreshCounts(); }
  }
  stepDebris(dt);

  sinceTick += dt;
  rateWindow += dt;
  const before = ore;
  // the tick stops while the factory is still in the air — a meltdown that
  // kept banking value would read as though nothing had been given up
  while (sinceTick >= TICK) { sinceTick -= TICK; if (!melting) step(); }
  minedWindow += ore - before;
  if (rateWindow >= 1) {
    // AVERAGE OVER LONGER THAN THE SLOWEST MACHINE (2026-09-06). This sampled
    // a one-second window, and a smelter emits once every three ticks — 1.26s.
    // So the readout sat at 0 for whole seconds while value was visibly
    // climbing, which reads as a broken game rather than as a bursty one. In
    // a genre whose entire hook is watching a number go up, the number has to
    // be trustworthy. Six one-second buckets, reported as their sum.
    rateBuckets.push(minedWindow / rateWindow);
    if (rateBuckets.length > 6) rateBuckets.shift();
    const perSec = rateBuckets.reduce((a, b) => a + b, 0) / rateBuckets.length;
    document.getElementById('rate').textContent = Math.round(perSec * 60);
    minedWindow = 0;
    rateWindow = 0;
  }
  // market prices are fractional, so the banked total is too; nobody wants to
  // read "47.870509893495935" as their score
  document.getElementById('ore').textContent = Math.floor(ore);
  document.getElementById('ingot').textContent = ingots;
  document.getElementById('alloy').textContent = alloys;
  // the buttons light up the moment you can afford them — the whole point of
  // the number climbing is watching it cross a threshold
  if (Math.floor(ore) !== lastOreShown) { lastOreShown = Math.floor(ore); renderUpgrades(); }
  // !! IS LOAD-BEARING (2026-09-08). classList.toggle(name, force) TOGGLES when
  // force is undefined, and UNLOCKED.meltdown is undefined until it is earned —
  // so a locked meltdown button flipped on and off every single frame, which
  // renders as permanently visible and let you prestige before it was unlocked.
  document.getElementById('melt').classList.toggle('on',
    !!(UNLOCKED.meltdown && ore >= MELT_MIN && !melting));
  {
    // the debt and the clock, in words, because a rift you have to remember is
    // a rift you will be surprised by
    let owed = null;
    eachTile(c => { if (c.t === RIFT && c.dbt > 0 && !owed) owed = c; });
    const el = document.getElementById('rift');
    if (el) {
      el.classList.toggle('on', !!owed);
      if (owed) el.innerHTML = '<b>RIFT DEBT</b><small>' + owed.dbt + ' \u00d7 '
        + MINERAL_NAME[owed.dmin] + ' \u00b7 ' + Math.ceil(owed.left) + 's</small>';
    }
  }
  document.getElementById('nitem').textContent = drawItems(sinceTick / TICK);

  if (beltsDirty) rebuildBelts();
  // the tread scrolls at the speed items actually travel: one tile per tick.
  // A belt whose surface moves at a speed unrelated to its throughput is worse
  // than one that does not move at all.
  if (!melting) TREAD.offset.x -= dt / TICK;
  // drill bits turn while their rig is on a seam
  eachTile(c => {
    if (c.t !== MINER || !c.build) return;
    const bit = c.build.getObjectByName('bit');
    if (bit) bit.rotation.y += dt * 7;
  });

  // a crystal on the west face spins about the west face's up
  scene.traverse(o => {
    if (!o.userData.spin) return;
    const ax = o.userData.axis;
    if (ax) o.rotateOnAxis(_bx.set(0, 1, 0), dt * o.userData.spin);
    else o.rotation.y += dt * o.userData.spin;
  });

  if (overhead || inspectOn) {
    camera.position.set(
      Math.sin(orbYaw) * Math.cos(orbPitch) * orbDist,
      Math.sin(orbPitch) * orbDist,
      Math.cos(orbYaw) * Math.cos(orbPitch) * orbDist);
    camera.lookAt(0, 0, 0);
    // fog is tuned for standing ON the surface; from an orbit it erases the
    // whole worldlet, which is the one view that has to read at a glance
    scene.fog = null;
    ghost.visible = false;
  } else {
    if (!scene.fog) scene.fog = worldFog;
    movePlayer(dt);
    camera.position.copy(player.pos);
    // Built from a basis, not from Euler angles: there is no global "up" left
    // to write a yaw against once the player can be standing on the underside
    // of the world. camUp trails the true up so an edge crossing rolls.
    camUp.lerp(player.up, Math.min(1, dt * 7)).normalize();
    _bz.copy(player.fwd).addScaledVector(camUp, -player.fwd.dot(camUp));
    if (_bz.lengthSq() < 1e-8) _bz.copy(player.fwd);
    _bz.normalize();
    _bx.crossVectors(_bz, camUp).normalize();     // right
    _by.crossVectors(_bx, _bz).normalize();       // orthonormal up
    _mx.makeBasis(_bx, _by, _bz.negate());        // a camera looks down -Z
    camera.quaternion.setFromRotationMatrix(_mx);
    camera.rotateX(player.pitch);
    updateGhost();
  }
  document.body.classList.toggle('overhead', overhead);
  renderer.render(scene, camera);
});

// ── STUDIO INSPECTOR BRIDGE ────────────────────────────────────────────────
// Standalone (itch.io, the flagship demo, a shared zip) this is inert: nothing
// is listening and window.parent is the window itself. Inside the studio it is
// how Inspect, drag-to-place and the property panel reach the running game.
let inspectOn = false;
let overheadBefore = false;
let lastPick = null;                     // the tile the studio last asked about

function setInspectOn(on) {
  if (on === inspectOn) return;
  inspectOn = on;
  if (on) {
    overheadBefore = overhead;
    overhead = true;                     // inspecting is a camera you can aim
    if (document.pointerLockElement === renderer.domElement) document.exitPointerLock();
  } else {
    overhead = overheadBefore;
  }
  document.body.classList.toggle('inspect', on);
}

{
  const rc = new THREE.Raycaster();
  const nv = new THREE.Vector2();
  const send = m => { try { window.parent.postMessage(m, '*'); } catch (e) {} };

  function pickAt(cx, cy, kindEv) {
    nv.set((cx / innerWidth) * 2 - 1, -(cy / innerHeight) * 2 + 1);
    rc.setFromCamera(nv, camera);
    for (const h of rc.intersectObjects(scene.children, true)) {
      if (h.object.isLine || h.object === ghost || ghost.children.indexOf(h.object) >= 0)
        continue;                        // grid lines and the build ghost are not things
      let o = h.object, tag = null;
      // an instanced belt has no object of its own, so the instance id is the
      // only way back to the tile it came from
      if ((h.object === beltFrames || h.object === beltDecks) &&
          h.instanceId != null && beltIndex[h.instanceId]) {
        const t2 = beltIndex[h.instanceId];
        tag = { type: 'machine', name: 'belt',
                detail: FACES[t2.face].name + ' face · tile ' + t2.i + ',' + t2.j,
                face: t2.face, i: t2.i, j: t2.j };
      }
      while (!tag && o) { if (o.userData && o.userData.fsTag) { tag = o.userData.fsTag; break; }
                          o = o.parent; }
      const t = tag && tag.face !== undefined
        ? { face: tag.face, i: tag.i, j: tag.j } : tileOfPoint(h.point);
      lastPick = t;
      send({ type: 'fs-pick', kind: kindEv,
             x: +h.point.x.toFixed(2), y: +h.point.y.toFixed(2), z: +h.point.z.toFixed(2),
             tile: t,
             target: tag || (t
               ? { type: 'ground', name: FACES[t.face].name + ' face',
                   detail: 'tile ' + t.i + ',' + t.j + ' · '
                           + MINERAL_NAME[MINERAL_OF_FACE[t.face]] + ' country' }
               : { type: 'ground', name: 'ground', detail: 'off the worldlet' }) });
      return true;
    }
    // A DROP ALWAYS LANDS, or says why it did not. Aimed past the cube there is
    // no ground plane to fall back on — a worldlet is surrounded by space — so
    // the honest answer is dropfail rather than a silent nothing, which the
    // studio would sit and wait on forever.
    if (kindEv === 'drop') send({ type: 'fs-pick', kind: 'dropfail' });
    return false;
  }

  // A SPAWN NEEDS A FACE, AND x/z CANNOT CARRY ONE. The studio sends the world
  // coordinates its own drop reported, which on a flat map is enough and on a
  // cube is not: (x,z) names a column through the world, not a tile. So a spawn
  // lands on the tile the pick that preceded it resolved.
  const SPAWN_KIND = {
    miner: MINER, drill: MINER, mine: MINER,
    belt: BELT, conveyor: BELT, conveyer: BELT,
    smelter: SMELTER, furnace: SMELTER, kiln: SMELTER,
    splitter: SPLITTER, split: SPLITTER,
    hub: HUB, depot: HUB, base: HUB,
    forge: FORGE, alloy: FORGE,
    filter: FILTER, sorter: FILTER,
    rift: RIFT, chronos: RIFT, portal: RIFT,
  };

  addEventListener('message', e => {
    const d = e.data;
    if (!d || !d.type) return;
    if (d.type === 'fs-inspect') { setInspectOn(!!d.on); return; }
    if (d.type === 'fs-dropat') { pickAt(d.cx, d.cy, 'drop'); return; }
    if (d.type === 'fs-spawn') {
      const kind = String(d.kind || '').toLowerCase().replace(/[^a-z]/g, '');
      const type = SPAWN_KIND[kind];
      if (!type) {
        send({ type: 'fs-spawned', ok: false, kind: d.kind,
               err: 'a factory builds machines — try miner, belt, smelter, '
                    + 'splitter, hub, forge or filter' });
        return;
      }
      const t = (d.tile && d.tile.face !== undefined) ? d.tile : lastPick;
      if (!t) { send({ type: 'fs-spawned', ok: false, kind: d.kind,
                       err: 'nothing picked yet — click a tile first' }); return; }
      const ok = place(t.face, t.i, t.j, type, 0) !== false;
      send({ type: 'fs-spawned', ok, kind: d.kind,
             err: ok ? undefined : 'a miner only goes on an ore seam' });
      return;
    }
  });

  // hover picks, so the studio's panel updates as you move over the world.
  // Throttled: an unthrottled raycast per mousemove is a scene traversal per
  // pixel of travel, and this runs beside a simulation.
  let hoverAt = 0;
  renderer.domElement.addEventListener('mousemove', e => {
    if (!inspectOn) return;
    const now = performance.now();
    if (now - hoverAt < 90) return;
    hoverAt = now;
    pickAt(e.clientX, e.clientY, 'hover');
  });
  renderer.domElement.addEventListener('click', e => {
    if (inspectOn) pickAt(e.clientX, e.clientY, 'click');
  });
  window.__pickAt = pickAt;
}

// ORBIT BY DRAGGING. The overhead camera could only be zoomed, which is fine
// as a glance at your own factory and useless as an inspector: half the world
// is on faces you cannot bring into view.
{
  let drag = null;
  renderer.domElement.addEventListener('pointerdown', e => {
    if (!overhead && !inspectOn) return;
    // Right-drag orbits, because in the overhead view LEFT-drag already draws
    // belts and taking that away to spin the camera would be a worse trade.
    // While inspecting there is no drawing, so left-drag orbits too.
    if (e.button !== 2 && !(inspectOn && e.button === 0)) return;
    drag = { x: e.clientX, y: e.clientY };
  });
  addEventListener('pointermove', e => {
    if (!drag) return;
    orbYaw -= (e.clientX - drag.x) * 0.006;
    orbPitch = Math.max(-1.45, Math.min(1.45, orbPitch + (e.clientY - drag.y) * 0.005));
    drag.x = e.clientX; drag.y = e.clientY;
  });
  addEventListener('pointerup', () => { drag = null; });
}

// The shot gate, the scene audit and the brief check all talk to window.__game.
// A second genre that invented its own interface would need a second gate, and
// then only one of them would stay honest.
window.__game = {
  ready: true,
  pos: () => player.pos.toArray(),
  keys: {},
  pick: (cx, cy) => window.__pickAt(cx, cy, 'click'),
  inspect: on => setInspectOn(on),
  get inspecting() { return inspectOn; },
  stats: () => ({ calls: renderer.info.render.calls,
                  tris: renderer.info.render.triangles,
                  programs: renderer.info.programs ? renderer.info.programs.length : -1,
                  textures: renderer.info.memory.textures,
                  geometries: renderer.info.memory.geometries }),
  facts: () => ({
    genre: 'factory',
    style: SPEC.style || 'default',
    grid: N,
    nodes: NODE_COUNT,
    value: ore,
    ingots,
    machines: (() => { let n = 0;
      eachTile(c => { if (c.t !== EMPTY && c.t !== NODE) n++; });
      return n; })(),
    items_on_belts: items.count,
    alloys,
    prices: TRADED.map(t => +PRICE[t].toFixed(3)),
    restored,
    goal: goalIdx < GOALS.length ? GOALS[goalIdx].text : null,
    goal_index: goalIdx,
    unlocked: Object.keys(UNLOCKED),
    faces_visited: visitedFaces.size,
    rift: (() => { let r = null;
      eachTile(c => { if (c.t === RIFT && !r) r = { debt: c.dbt,
        ore: MINERAL_NAME[c.dmin] || null, left: +c.left.toFixed(1),
        cool: +c.cool.toFixed(1), emit: c.emit }; });
      return r; })(),
    best: TRADE_NAME[TRADED.reduce((a, b) => PRICE[a] > PRICE[b] ? a : b)],
    minerals: MINERAL_OF_FACE.map(m => MINERAL_NAME[m]),
    cores,
    run_value: +runValue.toFixed(1),
    melting: +melting.toFixed(2),
    debris: debris.length,
    faces: 6,
    player_face: FACES[player.face].name,
    player_up: player.up.toArray().map(v => +v.toFixed(2)),
    player_y: +player.pos.y.toFixed(2),
  }),
};
window.__scene = scene;
window.__renderer = renderer;
window.__camera = camera;

window.__factory = {
  cells, items, N, T, player, HALF, FACES,
  stepTile, tileWorld, faceOfPoint,
  TYPES: { EMPTY, MINER, BELT, HUB, NODE, SMELTER, SPLITTER, FORGE, FILTER,
           RIFT, CRYSTAL, EMBER, SALT, INGOT, INGOT_E, INGOT_S, ALLOY },
  MINERAL_OF_FACE, get alloys() { return alloys; }, cycleFilter,
  riftOpen, riftStorm, RIFT_COUNT, RIFT_WINDOW,
  save, load, wipe, saveState, SAVE_KEY, TREAD, beltFrames, beltDecks,
  GOALS, UNLOCKED, get goalIdx() { return goalIdx; }, visitedFaces,
  PRICE, TRADED, stepMarket,
  UPGRADES, buy, costOf, get tick() { return TICK; },
  meltdown, MELT_MIN, get cores() { return cores; },
  addValue: n => { ore += n; },
  get ingots() { return ingots; },
  get ore() { return ore; },
  place, removeAt,
  camPos: () => camera.position.toArray(),
  ghostVisible: () => ghost.visible,
};
