// FACTORY RUNTIME — the automation genre, generated by Fantasy Studio.
//
// A second runtime beside main.js.tpl. The adventure runtime renders a spec as
// a world you walk through; this one renders a spec as a world you BUILD in.
// They share the vendored three.js, the export pipeline, the verification gate
// and the asset library — everything except the game.
//
// Every constant below is derived from the injected spec, so the same
// generator that produces an adventure produces an island whose size, ore
// density and palette come from the prompt.
const SPEC = __GAME_SPEC__;
window.__SPEC = SPEC;

const _sz = Math.max(60, Math.min(480, +(SPEC.world && SPEC.world.size_m) || 150));
const _pal = (SPEC.world && SPEC.world.palette) || {};
const _hex = (v, d) => {
  if (typeof v !== 'string' || v[0] !== '#' || v.length !== 7) return d;
  return parseInt(v.slice(1), 16);
};
const SKY_COL = _hex(_pal.sky, 0x0b0d18);
const FOG_COL = _hex(_pal.fog, SKY_COL);
const ACCENT = _hex(_pal.accent, 0x39e6ff);

// CRYSTAL WORKS — 3D incremental automation, core-loop prototype.
//
// The hook of this genre is one conversion: chaotic manual clicking becomes a
// machine that runs without you. So this builds exactly that loop and nothing
// else — mine, move, deliver. If it is not satisfying inside thirty seconds no
// upgrade tree will save it, and the brief is right that this is the thing to
// prove before writing thousands of lines.
//
// Performance shape: items on belts are NOT meshes. ONE InstancedMesh carries
// every crystal in the world and the tick writes matrices into it, so a
// thousand items across a hundred belts cost a single draw call.
import * as THREE from 'three';

// grid resolution follows the prompt's world size: a bigger island is a
// bigger factory, not the same factory further apart
const T = 2;
const N = Math.max(12, Math.min(40, Math.round(_sz / 6)));
const HALF = (N * T) / 2;

// ── THE CUBE (2026-09-07) ──────────────────────────────────────────────────
// The factory does not sit on a plane; it wraps a cube. A belt that runs off
// the top face keeps running down the side, and a player who walks over an
// edge finds gravity rotate under them. Every flat-ground competitor in this
// genre would have to rebuild their spatial core to copy it.
//
// This math is verified on its own in flagship/cubegrid.test.mjs — nineteen
// properties, including all 192 edge crossings of an 8-cube — because a wrong
// wrap does not crash. Items just quietly arrive on the wrong face, three
// hours into somebody's save.
const FACES = [
  { name: 'top',   u: [1, 0, 0],  v: [0, 0, -1] },
  { name: 'bot',   u: [1, 0, 0],  v: [0, 0, 1] },
  { name: 'east',  u: [0, 0, -1], v: [0, -1, 0] },
  { name: 'west',  u: [0, 0, 1],  v: [0, -1, 0] },
  { name: 'south', u: [1, 0, 0],  v: [0, -1, 0] },
  { name: 'north', u: [-1, 0, 0], v: [0, -1, 0] },
];
const _cr = (a, b) => [a[1] * b[2] - a[2] * b[1],
                       a[2] * b[0] - a[0] * b[2],
                       a[0] * b[1] - a[1] * b[0]];
const _dt3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const _ng = a => [-a[0], -a[1], -a[2]];
const _eqv = (a, b) => Math.abs(a[0] - b[0]) < 1e-9 &&
                       Math.abs(a[1] - b[1]) < 1e-9 && Math.abs(a[2] - b[2]) < 1e-9;
for (const f of FACES) f.n = _cr(f.u, f.v);      // right-handed: u x v = n

const dirVec = (face, d) => [FACES[face].u, FACES[face].v,
                             _ng(FACES[face].u), _ng(FACES[face].v)][d & 3];

/** World-space centre of tile [face,i,j], on the cube surface. */
function tileWorld(face, i, j) {
  const f = FACES[face];
  const a = (i + 0.5 - N / 2) * T, b = (j + 0.5 - N / 2) * T;
  return [f.n[0] * HALF + f.u[0] * a + f.v[0] * b,
          f.n[1] * HALF + f.u[1] * a + f.v[1] * b,
          f.n[2] * HALF + f.u[2] * a + f.v[2] * b];
}

/**
 * One tile along heading d. Inside a face this is arithmetic; crossing an edge
 * is the whole feature. The destination is the face whose normal matches the
 * way you walked off, and your heading there becomes the OLD face's inward
 * normal. The indices come from projecting the tile you left onto the new
 * basis — which is how twenty-four hand-written edge cases, one of them
 * inevitably wrong, are avoided.
 */
function stepTile(face, i, j, d) {
  const ni = i + [1, 0, -1, 0][d & 3];
  const nj = j + [0, 1, 0, -1][d & 3];
  if (ni >= 0 && nj >= 0 && ni < N && nj < N) return { face, i: ni, j: nj, d };

  const walk = dirVec(face, d), oldN = FACES[face].n;
  let dst = -1;
  for (let k = 0; k < 6; k++) if (_eqv(FACES[k].n, walk)) { dst = k; break; }
  if (dst < 0) return null;
  const want = _ng(oldN);
  let nd = -1;
  for (let k = 0; k < 4; k++) if (_eqv(dirVec(dst, k), want)) { nd = k; break; }
  if (nd < 0) return null;

  const o = FACES[face], g = FACES[dst];
  const a = i + 0.5 - N / 2, b = j + 0.5 - N / 2;   // unit tiles: indices only
  const w = [o.n[0] * (N / 2) + o.u[0] * a + o.v[0] * b,
             o.n[1] * (N / 2) + o.u[1] * a + o.v[1] * b,
             o.n[2] * (N / 2) + o.u[2] * a + o.v[2] * b];
  const ri = Math.max(0, Math.min(N - 1, Math.round(_dt3(w, g.u) + N / 2 - 0.5)));
  const rj = Math.max(0, Math.min(N - 1, Math.round(_dt3(w, g.v) + N / 2 - 0.5)));
  return { face: dst, i: ri, j: rj, d: nd, wrapped: true };
}

/** Which face a world point belongs to: the one whose normal it is furthest along. */
function faceOfPoint(px, py, pz) {
  let best = 0, bestD = -Infinity;
  for (let k = 0; k < 6; k++) {
    const n = FACES[k].n, d = px * n[0] + py * n[1] + pz * n[2];
    if (d > bestD) { bestD = d; best = k; }
  }
  return best;
}

const BASE_TICK = 0.42;
let TICK = BASE_TICK;
const EMPTY = 0, MINER = 1, BELT = 2, HUB = 3, NODE = 4, SMELTER = 5,
      SPLITTER = 6, FORGE = 7;
const DIRS = [[1, 0], [0, 1], [-1, 0], [0, -1]];        // E S W N

// Items now have a TYPE, and that is the whole point of the smelter. Until
// now a belt only ever solved "the node is far from the hub" — a distance
// problem, which is a chore rather than a puzzle. A recipe makes belts solve
// "these things have to MEET", which is where this genre's actual decisions
// live: where to put the smelter, how to feed it from two nodes, what to do
// with the surplus when one input runs dry.
// ── WHAT THE CUBE IS FOR (2026-09-07) ──────────────────────────────────────
// Every face used to grow the same crystal, which made the other five faces
// scenery: a factory that never left the top was optimal, and the mechanic
// the whole build is named for was a gimmick you could ignore. Three minerals,
// one per opposite pair of faces, and an alloy that cannot be made from any
// single face's ore. Now a belt HAS to go over an edge.
const CRYSTAL = 1, EMBER = 2, SALT = 3;
const MINERALS = [CRYSTAL, EMBER, SALT];
const INGOT = 4, INGOT_E = 5, INGOT_S = 6, ALLOY = 7;
const INGOT_OF = { [CRYSTAL]: INGOT, [EMBER]: INGOT_E, [SALT]: INGOT_S };
const IS_MINERAL = t => t === CRYSTAL || t === EMBER || t === SALT;
const IS_INGOT = t => t === INGOT || t === INGOT_E || t === INGOT_S;
// FACES is [top, bot, east, west, south, north]; opposite faces share a
// mineral so that whichever way you walk off the top, the ore changes.
const MINERAL_OF_FACE = [CRYSTAL, CRYSTAL, EMBER, EMBER, SALT, SALT];
const MINERAL_NAME = { [CRYSTAL]: 'crystal', [EMBER]: 'ember', [SALT]: 'salt' };

const VALUE = { [CRYSTAL]: 1, [INGOT]: 6 };   // an ingot is worth the detour
const SMELT_IN = 2;                            // ore of one kind per ingot
let SMELT_TICKS = 3;                           // and it takes time
let FORGE_TICKS = 4;                           // an alloy takes longer still

// ── UPGRADES ───────────────────────────────────────────────────────────────
// The loop this genre runs on is: build something, watch the number climb,
// spend the number to make it climb faster. Each of these has to be VISIBLE
// when bought — a purchase that only changes a hidden coefficient feels like
// nothing, and feeling like something is the entire product.
// ── PRESTIGE ───────────────────────────────────────────────────────────────
// Everything on the cube is destroyed and you keep a number. It is the oldest
// trick in the incremental genre and it works because the second run is
// visibly faster than the first — the factory you rebuild is the same one,
// and it earns nearly half again as much per crystal.
let cores = 0;
let runValue = 0;                       // banked THIS run; cores are priced off it
const MELT_MIN = 400;
const coresFor = v => Math.floor(Math.sqrt(v / 220));

const UPGRADES = {
  tick:  { lvl: 0, cap: 6, cost: 60,  mult: 2.3,
           label: 'OVERCLOCK', note: 'everything runs faster' },
  yield: { lvl: 0, cap: 6, cost: 90,  mult: 2.5,
           label: 'RICH SEAMS', note: 'crystals are worth more' },
  smelt: { lvl: 0, cap: 4, cost: 150, mult: 2.8,
           label: 'HOT FURNACE', note: 'smelters cook quicker' },
};
const costOf = u => Math.round(u.cost * Math.pow(u.mult, u.lvl));

function applyUpgrades() {
  TICK = BASE_TICK * Math.pow(0.86, UPGRADES.tick.lvl);
  SMELT_TICKS = Math.max(1, 3 - UPGRADES.smelt.lvl);
  // A CORE IS WORTH MORE THAN THE FACTORY IT COST. The multiplier has to be
  // steep enough that melting down a good factory beats keeping it, or the
  // prestige is a button nobody presses twice.
  const y = (1 + UPGRADES.yield.lvl) * (1 + 0.45 * cores);
  for (const m of MINERALS) { VALUE[m] = y; VALUE[INGOT_OF[m]] = 6 * y; }
  // An alloy is worth more than the three ingots it displaces, because it
  // costs a belt run across a face boundary and the risk of getting it wrong.
  VALUE[ALLOY] = 26 * y;
  FORGE_TICKS = Math.max(2, 4 - UPGRADES.smelt.lvl);
}

function buy(key) {
  const u = UPGRADES[key];
  if (!u || u.lvl >= u.cap) return false;
  const c = costOf(u);
  if (ore < c) return false;
  ore -= c;
  u.lvl++;
  applyUpgrades();
  renderUpgrades();
  return true;
}

function renderUpgrades() {
  const box = document.getElementById('ups');
  if (!box) return;
  box.innerHTML = '';
  for (const key of Object.keys(UPGRADES)) {
    const u = UPGRADES[key];
    const maxed = u.lvl >= u.cap;
    const c = costOf(u);
    const el = document.createElement('div');
    el.className = 'up' + (maxed ? ' maxed' : (ore >= c ? ' can' : ''));
    el.innerHTML = '<b>' + u.label + ' <span>' + u.lvl + '/' + u.cap + '</span></b>' +
      '<small>' + u.note + '</small>' +
      '<i>' + (maxed ? 'MAX' : c + ' value') + '</i>';
    if (!maxed) el.addEventListener('pointerdown', ev => { ev.stopPropagation(); buy(key); });
    box.appendChild(el);
  }
}

// Six faces of N x N. Nothing else in the simulation knows the shape of the
// world: it asks stepTile what is next to a tile, and stepTile is the only
// place an edge exists.
const cells = [];
for (let f = 0; f < 6; f++) {
  cells[f] = [];
  for (let i = 0; i < N; i++) {
    cells[f][i] = [];
    for (let j = 0; j < N; j++)
      cells[f][i][j] = { t: EMPTY, d: 0, item: 0, buf: 0, bt: 0,
                         fa: 0, fb: 0, cook: 0, rr: 0, min: 0 };
  }
}
const cellOf = t => (t ? cells[t.face][t.i][t.j] : null);
/** Every tile on the cube, once. */
function eachTile(fn) {
  for (let f = 0; f < 6; f++)
    for (let i = 0; i < N; i++)
      for (let j = 0; j < N; j++) fn(cells[f][i][j], f, i, j);
}

// ── scene ──────────────────────────────────────────────────────────────────
const scene = new THREE.Scene();
scene.background = new THREE.Color(SKY_COL);
const worldFog = new THREE.Fog(FOG_COL, HALF * 1.6, HALF * 4.0);
scene.fog = worldFog;
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, 0.1, 500);
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.06;
document.body.appendChild(renderer.domElement);

scene.add(new THREE.HemisphereLight(0x9fc4ff, 0x1b2038, 1.1));
const sun = new THREE.DirectionalLight(0xfff0d8, 2.2);
sun.position.set(30, 46, 20);
sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048);
sun.shadow.camera.left = -HALF * 1.5;
sun.shadow.camera.right = HALF * 1.5;
sun.shadow.camera.top = HALF * 1.5;
sun.shadow.camera.bottom = -HALF * 1.5;
sun.shadow.camera.near = 1;
sun.shadow.camera.far = 170;
sun.shadow.camera.updateProjectionMatrix();
scene.add(sun);

// ONE SUN LIGHTS ONE SIDE OF A CUBE (2026-09-07). On a flat island a single
// directional light was enough. On a worldlet the faces facing away from it
// fall to pure hemisphere ambient and read as unlit black — you walk around
// the corner into a game that looks broken. A dimmer fill from the opposite
// quadrant keeps every face legible without flattening the key light.
const fill = new THREE.DirectionalLight(0xb9d2ff, 0.85);
fill.position.set(-34, -40, -26);
scene.add(fill);

// ── the worldlet: a cube you can walk all the way around ───────────────────
const cube = new THREE.Mesh(
  new THREE.BoxGeometry(N * T, N * T, N * T),
  new THREE.MeshStandardMaterial({ color: 0x2b3252, roughness: 0.96 }));
cube.receiveShadow = true;
scene.add(cube);
{
  // grid lines on all six faces, lifted a hair off the surface. Without them
  // the underside of the world is an unreadable dark field and you cannot
  // tell where a belt will land.
  const pts = [];
  const E = HALF + 0.02;
  for (const f of FACES) {
    for (let k = 0; k <= N; k++) {
      const q = -HALF + k * T;
      for (const [a, b, c, d] of [[q, -HALF, q, HALF], [-HALF, q, HALF, q]]) {
        pts.push(f.n[0] * E + f.u[0] * a + f.v[0] * b,
                 f.n[1] * E + f.u[1] * a + f.v[1] * b,
                 f.n[2] * E + f.u[2] * a + f.v[2] * b,
                 f.n[0] * E + f.u[0] * c + f.v[0] * d,
                 f.n[1] * E + f.u[1] * c + f.v[1] * d,
                 f.n[2] * E + f.u[2] * c + f.v[2] * d);
      }
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3));
  scene.add(new THREE.LineSegments(g, new THREE.LineBasicMaterial(
    { color: 0x46527d, transparent: true, opacity: 0.22 })));
}

// SEATING. Everything that stands on the cube shares one rule: local +Y
// becomes the face normal and local +X the heading. Written once, so a belt
// arrow, a smelter and the build ghost cannot disagree about which way is up
// on the underside of the world.
const _mx = new THREE.Matrix4();
const _bx = new THREE.Vector3(), _by = new THREE.Vector3(), _bz = new THREE.Vector3();
function seat(obj, face, i, j, dir, up) {
  const f = FACES[face], w = tileWorld(face, i, j), dv = dirVec(face, dir || 0);
  _bx.set(dv[0], dv[1], dv[2]);
  _by.set(f.n[0], f.n[1], f.n[2]);
  _bz.crossVectors(_bx, _by);
  _mx.makeBasis(_bx, _by, _bz);
  obj.quaternion.setFromRotationMatrix(_mx);
  const h = up || 0;
  obj.position.set(w[0] + f.n[0] * h, w[1] + f.n[1] * h, w[2] + f.n[2] * h);
}

// ── crystal nodes: the only tiles a miner can stand on ─────────────────────
// The player's first read of "this face is different" is the colour of the
// ore standing on it, from across the worldlet, before they have walked there.
const MIN_COL = { [CRYSTAL]: ACCENT, [EMBER]: 0xff8a3d, [SALT]: 0xe8f0ff };
const nodeMats = {};
for (const m of MINERALS) nodeMats[m] = new THREE.MeshStandardMaterial({
  color: MIN_COL[m], emissive: MIN_COL[m], emissiveIntensity: 0.55,
  roughness: 0.25, flatShading: true });
const nodeMat = nodeMats[CRYSTAL];
const nodeGeo = new THREE.OctahedronGeometry(0.62, 0);
let rngState = 1337;
const rnd = () => (rngState = (rngState * 1664525 + 1013904223) % 4294967296) / 4294967296;
const NODE_COUNT = Math.max(6, Math.min(40, Math.round(N * N * 0.028)));
for (let k = 0; k < NODE_COUNT; k++) {
  const f = Math.floor(rnd() * 6);
  const i = 2 + Math.floor(rnd() * (N - 4));
  const j = 2 + Math.floor(rnd() * (N - 4));
  const c = cells[f][i][j];
  if (c.t !== EMPTY) continue;
  c.t = NODE;
  c.min = MINERAL_OF_FACE[f];
  const m = new THREE.Mesh(nodeGeo, nodeMats[c.min]);
  seat(m, f, i, j, 0, 0.7);
  m.castShadow = true;
  m.userData.spin = 0.4 + rnd() * 0.6;
  m.userData.axis = FACES[f].n;      // spin about the face's up, not the world's
  scene.add(m);
  c.mesh = m;
}

// ── build meshes ───────────────────────────────────────────────────────────
const MAT = {
  miner: new THREE.MeshStandardMaterial({ color: 0xff5d73, roughness: 0.4, metalness: 0.35 }),
  belt: new THREE.MeshStandardMaterial({ color: 0x3ad39a, roughness: 0.6, metalness: 0.2 }),
  hub: new THREE.MeshStandardMaterial({ color: 0xffc75a, roughness: 0.35, metalness: 0.45,
    emissive: 0x6b4a00, emissiveIntensity: 0.6 }),
  forge: new THREE.MeshStandardMaterial({ color: 0xd94fb0, roughness: 0.34,
    metalness: 0.55, flatShading: true }),
  smelt: new THREE.MeshStandardMaterial({ color: 0x8c6bff, roughness: 0.42, metalness: 0.4,
    emissive: 0x2a1470, emissiveIntensity: 0.5 }),
  split: new THREE.MeshStandardMaterial({ color: 0x4bb5ff, roughness: 0.45, metalness: 0.35,
    emissive: 0x0d3f66, emissiveIntensity: 0.45 }),
};
const GEO = {
  miner: new THREE.BoxGeometry(T * 0.74, 1.5, T * 0.74),
  belt: new THREE.BoxGeometry(T * 0.9, 0.22, T * 0.9),
  arrow: new THREE.ConeGeometry(0.2, 0.5, 4),
  hub: new THREE.CylinderGeometry(T * 0.5, T * 0.58, 1.1, 8),
  smelt: new THREE.BoxGeometry(T * 0.82, 1.25, T * 0.82),
  split: new THREE.CylinderGeometry(T * 0.42, T * 0.42, 0.34, 4),
  splitArm: new THREE.BoxGeometry(T * 0.86, 0.16, 0.22),
  // taller and eight-sided, so a forge is not mistaken for a smelter
  // from across the worldlet
  forge: new THREE.CylinderGeometry(T * 0.44, T * 0.5, 1.4, 8),
};

function refreshCounts() {
  let m = 0, b = 0, sm = 0;
  eachTile(c => {
    if (c.t === MINER) m++;
    else if (c.t === BELT) b++;
    else if (c.t === SMELTER) sm++;
  });
  document.getElementById('nmine').textContent = m;
  document.getElementById('nbelt').textContent = b;
  document.getElementById('nsmelt').textContent = sm;
}

function removeAt(face, i, j) {
  const c = cells[face][i][j];
  if (c.build) { scene.remove(c.build); c.build = null; }
  c.t = c.mesh ? NODE : EMPTY;               // a node outlives its miner
  c.item = 0;
  refreshCounts();
}

function place(face, i, j, type, dir) {
  const c = cells[face][i][j];
  if (type === MINER && c.t !== NODE && c.t !== MINER) return false;
  c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0;
  if (type !== MINER && c.t === NODE) return false;      // keep nodes clear
  if (c.build) { scene.remove(c.build); c.build = null; }
  const g = new THREE.Group();
  if (type === MINER) {
    const b = new THREE.Mesh(GEO.miner, MAT.miner);
    b.position.y = 0.75; b.castShadow = true; g.add(b);
  } else if (type === BELT) {
    const b = new THREE.Mesh(GEO.belt, MAT.belt);
    b.position.y = 0.11; b.castShadow = true; b.receiveShadow = true; g.add(b);
    const a = new THREE.Mesh(GEO.arrow, MAT.belt);
    a.position.set(0.55, 0.3, 0);
    a.rotation.z = -Math.PI / 2;
    g.add(a);
    // the heading is baked into the seating basis now, not into a Y rotation:
    // on the east face there is no such thing as "rotate about world up"
  } else if (type === HUB) {
    const b = new THREE.Mesh(GEO.hub, MAT.hub);
    b.position.y = 0.55; b.castShadow = true; g.add(b);
  } else if (type === SPLITTER) {
    const b = new THREE.Mesh(GEO.split, MAT.split);
    b.position.y = 0.18; b.rotation.y = Math.PI / 4;
    b.castShadow = true; b.receiveShadow = true; g.add(b);
    // a cross, so what it does is visible from across the island rather than
    // being a box you have to remember the meaning of
    for (const r of [0, Math.PI / 2]) {
      const arm = new THREE.Mesh(GEO.splitArm, MAT.split);
      arm.position.y = 0.4; arm.rotation.y = r; g.add(arm);
    }
  } else if (type === FORGE) {
    const b = new THREE.Mesh(GEO.forge, MAT.forge);
    b.position.y = 0.7; b.castShadow = true; g.add(b);
    const lamp = new THREE.Mesh(new THREE.SphereGeometry(0.17, 8, 6),
      new THREE.MeshBasicMaterial({ color: 0xff5ad9 }));
    lamp.position.set(0, 1.5, 0);
    lamp.name = 'lamp';
    g.add(lamp);
  } else if (type === SMELTER) {
    const b = new THREE.Mesh(GEO.smelt, MAT.smelt);
    b.position.y = 0.63; b.castShadow = true; g.add(b);
    // a lamp that lights while it is cooking: a factory you can read at a
    // glance from across the island is the whole appeal of the genre
    const lamp = new THREE.Mesh(new THREE.SphereGeometry(0.17, 8, 6),
      new THREE.MeshBasicMaterial({ color: 0xffb04a }));
    lamp.position.set(0, 1.34, 0);
    lamp.name = 'lamp';
    g.add(lamp);
  }
  seat(g, face, i, j, dir, 0);
  scene.add(g);
  c.build = g;
  c.t = type;
  c.d = dir;
  c.item = 0;
  refreshCounts();
  return true;
}

// ── items: one InstancedMesh for every crystal in transit ──────────────────
const MAX_ITEMS = 4000;
const items = new THREE.InstancedMesh(
  new THREE.OctahedronGeometry(0.26, 0),
  new THREE.MeshStandardMaterial({ color: 0x7df9ff, emissive: 0x2aa6c4,
    emissiveIntensity: 1.4, roughness: 0.3, flatShading: true }),
  MAX_ITEMS);
items.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
items.frustumCulled = false;
items.count = 0;
// One mesh still, but two products: instanceColor is what lets a single draw
// call carry both. Reading a belt at a glance — "that line is running ingots,
// that one is still raw" — is most of what makes a factory legible.
items.instanceColor = new THREE.InstancedBufferAttribute(
  new Float32Array(MAX_ITEMS * 3), 3);
items.instanceColor.setUsage(THREE.DynamicDrawUsage);
scene.add(items);
const ITEM_COL = {
  [CRYSTAL]: new THREE.Color(0x7df9ff),
  [EMBER]: new THREE.Color(0xff8a3d),
  [SALT]: new THREE.Color(0xe8f0ff),
  [INGOT]: new THREE.Color(0x9fd6ff),
  [INGOT_E]: new THREE.Color(0xffae4d),
  [INGOT_S]: new THREE.Color(0xd8e2f5),
  [ALLOY]: new THREE.Color(0xff5ad9),
};

const _m = new THREE.Matrix4();
const _p = new THREE.Vector3();
const _q = new THREE.Quaternion();
const _s = new THREE.Vector3(1, 1, 1);
const _up = new THREE.Vector3(0, 1, 0);   // reused per item: the face normal

// ── the tick: belts advance, miners feed, the hub banks ────────────────────
let ore = 0;
let ingots = 0;
let alloys = 0;
let sinceTick = 0;
let minedWindow = 0;
let rateWindow = 0;
const rateBuckets = [];
let lastOreShown = -1;

function bank(type) {
  const v = VALUE[type] || 1;
  ore += v; runValue += v;
  if (IS_INGOT(type)) ingots++;
  if (type === ALLOY) alloys++;
}

// One acceptance rule, asked by belts, miners and splitters alike. Having each
// of them decide separately is how a factory sim ends up with items that can
// enter a machine one way and not another for no reason the player can see.
function accepts(dst, type) {
  if (!dst) return false;
  if (dst.t === HUB) return true;
  if (dst.t === BELT || dst.t === SPLITTER) return !dst.item;
  // A smelter refines ONE kind at a time — mixing two ores in it would make
  // the alloy free, and the alloy is supposed to cost a trip across an edge.
  if (dst.t === SMELTER)
    return IS_MINERAL(type) && dst.buf < SMELT_IN * 2 &&
           (dst.buf === 0 || dst.bt === type);
  // A forge is the opposite rule: it wants two DIFFERENT minerals, so it
  // cannot be fed from a single face.
  if (dst.t === FORGE)
    return IS_MINERAL(type) && dst.cook === 0 &&
           (dst.fa === 0 || (dst.fb === 0 && type !== dst.fa));
  return false;
}
function deliver(dst, dx, dz, type) {
  if (dst.t === HUB) bank(type);
  else if (dst.t === SMELTER) { dst.buf++; dst.bt = type; }
  else if (dst.t === FORGE) { if (dst.fa === 0) dst.fa = type; else dst.fb = type; }
  else dst.item = type;
}

function step() {
  // Smelters run FIRST so a finished ingot leaves before the belts feeding
  // this smelter get their turn — otherwise a full input belt would block the
  // machine that is about to free it, and lines deadlock at exactly the
  // moment they start working.
  eachTile((c, f, i, j) => {
    if (c.t !== SMELTER && c.t !== FORGE) return;
    if (c.cook > 0) {
      c.cook--;
      if (c.cook === 0) {
        const out = c.t === FORGE ? ALLOY : (INGOT_OF[c.bt] || INGOT);
        const dst = cellOf(stepTile(f, i, j, c.d));
        if (dst && dst.t === HUB) bank(out);
        else if (dst && dst.t === BELT && !dst.item) dst.item = out;
        else c.cook = 1;                  // output blocked: hold it, retry
      }
    }
    if (c.t === SMELTER) {
      if (c.cook === 0 && c.buf >= SMELT_IN) { c.buf -= SMELT_IN; c.cook = SMELT_TICKS; }
    } else if (c.cook === 0 && c.fa && c.fb) {
      c.fa = 0; c.fb = 0; c.cook = FORGE_TICKS;
    }
    const lamp = c.build && c.build.getObjectByName('lamp');
    if (lamp) lamp.material.color.setHex(c.cook > 0 ? 0xffb04a : 0x3a2f5e);
  });

  // Collect first, THEN commit. Moving in place would let one item ride the
  // whole line in a single tick depending on iteration order.
  const moves = [];
  eachTile((c, f, i, j) => {
    // A SPLITTER IS A BELT THAT CHOOSES. It sends each item out of a
    // different side in turn, so one miner can feed two smelters without
    // the player hand-balancing anything. The round-robin cursor advances
    // only when an item actually LEAVES — advancing on a failed attempt
    // would silently starve whichever output happened to be busy.
    if (c.t === SPLITTER && c.item) {
      for (let k = 0; k < 4; k++) {
        const dir = (c.rr + k) % 4;
        const to = stepTile(f, i, j, dir);
        if (!to || !accepts(cellOf(to), c.item)) continue;
        moves.push([c, 'to', to]);
        c.rr = (dir + 1) % 4;
        break;
      }
      return;
    }
    if (c.t !== BELT || !c.item) return;
    const to = stepTile(f, i, j, c.d);
    const dst = cellOf(to);
    if (!dst) return;
    if (dst.t === HUB) moves.push([c, 'bank']);
    // a smelter only accepts CRYSTALS, and only while it has room. An ingot
    // arriving at a smelter simply waits, which is the correct answer and
    // also a visible one — the belt backs up and you can see the mistake.
    else if (accepts(dst, c.item)) moves.push([c, 'to', to]);
  });
  for (const mv of moves) {
    const c = mv[0];
    if (mv[1] === 'bank') bank(c.item);
    else deliver(cellOf(mv[2]), 0, 0, c.item);
    c.item = 0;
  }
  eachTile((c, f, i, j) => {
    if (c.t !== MINER) return;
    // a miner digs whatever the seam under it is, which is the face's mineral
    const m = c.min || MINERAL_OF_FACE[f];
    const dst = cellOf(stepTile(f, i, j, c.d));
    if (accepts(dst, m)) deliver(dst, 0, 0, m);
  });
}

// Items are drawn BETWEEN their tile and the next, so the motion reads smooth
// even though the simulation is a discrete grid step. A blocked item sits
// still, which is what makes a jam legible.
function drawItems(alpha) {
  let n = 0;
  const spin = performance.now() * 0.002;
  eachTile((c, f, i, j) => {
    if (n >= MAX_ITEMS || c.t !== BELT || !c.item) return;
    const to = stepTile(f, i, j, c.d);
    const ahead = cellOf(to);
    const free = ahead && (ahead.t === HUB || (ahead.t === BELT && !ahead.item));
    const a = free ? alpha : 0;
    // Interpolating between the two tiles' world centres carries an item
    // around an edge on its own: across a corner the two centres are on
    // different faces, so the crystal cuts the corner instead of flying off
    // into space. That the tiles are never more than one diagonal apart is
    // one of the properties the cube-grid test pins down.
    const A = tileWorld(f, i, j), nrm = FACES[f].n;
    const B = ahead ? tileWorld(to.face, to.i, to.j) : A;
    _p.set(A[0] + (B[0] - A[0]) * a + nrm[0] * 0.42,
           A[1] + (B[1] - A[1]) * a + nrm[1] * 0.42,
           A[2] + (B[2] - A[2]) * a + nrm[2] * 0.42);
    _up.set(nrm[0], nrm[1], nrm[2]);
    _q.setFromAxisAngle(_up, spin);
    _m.compose(_p, _q, _s);
    items.setColorAt(n, ITEM_COL[c.item] || ITEM_COL[CRYSTAL]);
    items.setMatrixAt(n++, _m);
  });
  items.count = n;
  items.instanceMatrix.needsUpdate = true;
  if (items.instanceColor) items.instanceColor.needsUpdate = true;
  return n;
}

// ── input: raycast the ground plane, drag to draw belts ────────────────────
const ray = new THREE.Raycaster();
const ndc = new THREE.Vector2();
const hitPt = new THREE.Vector3();

/** The tile a world point sits over, or null if it is off the cube. */
function tileOfPoint(p) {
  const face = faceOfPoint(p.x, p.y, p.z), f = FACES[face];
  const a = p.x * f.u[0] + p.y * f.u[1] + p.z * f.u[2];
  const b = p.x * f.v[0] + p.y * f.v[1] + p.z * f.v[2];
  const i = Math.floor(a / T + N / 2), j = Math.floor(b / T + N / 2);
  if (i < 0 || j < 0 || i >= N || j >= N) return null;
  return { face, i, j };
}
let tool = 'miner';
let drawing = false;
let lastCell = null;

// In first person you aim with the CROSSHAIR, not the cursor — the pointer is
// locked and has no position. Overhead keeps the cursor. Reach is limited on
// foot for the obvious reason: a build game where you can place a machine on
// the far side of the island from where you stand is a board game again.
function cellUnder(ev) {
  if (overhead && ev) {
    ndc.set((ev.clientX / innerWidth) * 2 - 1, -(ev.clientY / innerHeight) * 2 + 1);
  } else {
    ndc.set(0, 0);
  }
  ray.setFromCamera(ndc, camera);
  // AIM AT THE SOLID, NOT AT A PLANE. The ground used to be the y=0 plane,
  // which on a cube would let you place machines on a face you are standing
  // inside of. Raycasting the cube itself means you build on the surface you
  // are actually looking at, whichever of the six it is.
  const hit = ray.intersectObject(cube, false)[0];
  if (!hit) return null;
  hitPt.copy(hit.point);
  if (!overhead && hitPt.distanceTo(camera.position) > REACH) return null;
  return tileOfPoint(hitPt);
}

// the ghost: what you are about to build, where you are about to build it
const ghost = new THREE.Mesh(
  new THREE.BoxGeometry(T * 0.92, 0.5, T * 0.92),
  new THREE.MeshBasicMaterial({ color: 0x6cf5d0, transparent: true, opacity: 0.28,
    depthWrite: false }));
ghost.visible = false;
scene.add(ghost);
const ghostEdge = new THREE.LineSegments(
  new THREE.EdgesGeometry(new THREE.BoxGeometry(T * 0.92, 0.5, T * 0.92)),
  new THREE.LineBasicMaterial({ color: 0x9dffe8, transparent: true, opacity: 0.85 }));
ghost.add(ghostEdge);

function updateGhost() {
  const t = cellUnder(null);
  if (!t) { ghost.visible = false; return; }
  const c = cellOf(t);
  const legal = tool === 'erase' ? (c.t !== EMPTY && c.t !== NODE)
    : tool === 'miner' ? c.t === NODE
    : c.t !== NODE;
  ghost.visible = true;
  seat(ghost, t.face, t.i, t.j, 0, 0.26);
  ghost.material.color.setHex(legal ? 0x6cf5d0 : 0xff6b7d);
  ghostEdge.material.color.setHex(legal ? 0x9dffe8 : 0xffa8b4);
}

// WHICH WAY DID THE DRAG GO. On a flat grid this was a subtraction of indices.
// Across an edge the two tiles are not in the same coordinate system at all,
// so the question is asked the only way that stays true: try each of the four
// headings and see which one actually steps from a to b.
function dirBetween(a, b) {
  for (let d = 0; d < 4; d++) {
    const s = stepTile(a.face, a.i, a.j, d);
    if (s && s.face === b.face && s.i === b.i && s.j === b.j) return d;
  }
  return null;
}

function apply(t, dir) {
  const d = dir == null ? 0 : dir;
  if (tool === 'erase') { removeAt(t.face, t.i, t.j); return; }
  if (tool === 'miner') { place(t.face, t.i, t.j, MINER, d); return; }
  if (tool === 'hub') { place(t.face, t.i, t.j, HUB, 0); return; }
  if (tool === 'smelter') { place(t.face, t.i, t.j, SMELTER, d); return; }
  if (tool === 'splitter') { place(t.face, t.i, t.j, SPLITTER, 0); return; }
  if (tool === 'forge') { place(t.face, t.i, t.j, FORGE, d); return; }
  if (tool === 'belt') { place(t.face, t.i, t.j, BELT, d); }
}

renderer.domElement.addEventListener('pointerdown', e => {
  if (e.button !== 0) return;
  const c = cellUnder(e);
  if (!c) return;
  drawing = true;
  lastCell = c;
  apply(c, null);
});
renderer.domElement.addEventListener('pointermove', e => {
  if (!drawing || !lastCell) return;
  const c = cellUnder(e);
  if (!c || (c.face === lastCell.face && c.i === lastCell.i && c.j === lastCell.j)) return;
  const d = dirBetween(lastCell, c);
  if (d == null) { lastCell = c; return; }
  // the tile we just left now points at the one we moved to
  const prev = cellOf(lastCell);
  if (prev.t === BELT || prev.t === MINER) {
    prev.d = d;
    if (prev.build) seat(prev.build, lastCell.face, lastCell.i, lastCell.j, d, 0);
  }
  // the drag arrives on the new tile heading the same way it left the old one,
  // which across an edge is NOT the direction the mouse moved
  const sd = stepTile(lastCell.face, lastCell.i, lastCell.j, d);
  apply(c, sd ? sd.d : d);
  lastCell = c;
});
addEventListener('pointerup', () => { drawing = false; lastCell = null; });

function pickTool(name) {
  tool = name;
  document.querySelectorAll('.tool').forEach(o =>
    o.classList.toggle('on', o.dataset.tool === name));
}
document.querySelectorAll('.tool').forEach(el => {
  el.addEventListener('pointerdown', ev => { ev.stopPropagation(); pickTool(el.dataset.tool); });
});
addEventListener('keydown', e => {
  const k = { '1': 'miner', '2': 'belt', '3': 'smelter', '4': 'splitter',
              '5': 'hub', '6': 'forge', '7': 'erase' }[e.key];
  if (k) pickTool(k);
  const u = { 'KeyZ': 'tick', 'KeyX': 'yield', 'KeyC': 'smelt' }[e.code];
  if (u) buy(u);
});

// ── YOU ARE ON THE ISLAND ───────────────────────────────────────────────────
// Arranging a factory on a board and STANDING IN ONE are different games. The
// second is the one people lose evenings to, because a belt you walked beside
// is yours in a way a belt you dragged on a grid is not. First person is the
// default; the overhead view stays on Tab because routing a junction from eye
// level is genuinely worse than seeing it from above, and a build game needs
// both.
const EYE = 1.68, REACH = 12;
const player = {
  pos: new THREE.Vector3(0, HALF + EYE, 0),
  face: 0,
  // The heading is a WORLD vector tangent to the current face, not a yaw
  // angle. A yaw needs a reference direction per face, and the six of them
  // cannot be made to agree along every edge — one seam always ends up with
  // the player spinning as they cross it.
  fwd: new THREE.Vector3(0, 0, -1),
  up: new THREE.Vector3(0, 1, 0),
  h: 0, vy: 0,
  // starts looking DOWN at the ground. Level-eyed, the surface is metres
  // beyond arm's reach and the build ghost simply never appears — you would
  // be standing in a build game with no way to tell why nothing can be placed.
  pitch: -0.38, onGround: true,
};
// the camera's up lags the player's by a few frames, so crossing an edge
// ROLLS the world over instead of snapping it. This is the shot the whole
// mechanic exists for; a hard cut throws it away.
const camUp = new THREE.Vector3(0, 1, 0);
let overhead = false;
// FRAMED FOR A CUBE, NOT A SLAB (2026-09-07). A fixed 46m orbit was outside a
// flat island and INSIDE a worldlet — Tab showed you a dark field of grid
// lines and nothing else. Every distance here is a multiple of the world.
let orbYaw = 0.72, orbPitch = 0.62, orbDist = HALF * 4.4;

const keys = Object.create(null);
addEventListener('keydown', e => {
  keys[e.code] = true;
  if (e.code === 'Tab') { e.preventDefault(); overhead = !overhead; }
});
addEventListener('keyup', e => { keys[e.code] = false; });
addEventListener('contextmenu', e => e.preventDefault());

// pointer lock is what makes it feel embodied rather than operated
renderer.domElement.addEventListener('click', () => {
  if (!overhead && document.pointerLockElement !== renderer.domElement) {
    renderer.domElement.requestPointerLock();
  }
});
addEventListener('mousemove', e => {
  if (document.pointerLockElement !== renderer.domElement) return;
  // turning is a rotation about whichever way is up HERE
  player.fwd.applyAxisAngle(player.up, -e.movementX * 0.0022).normalize();
  player.pitch = Math.max(-1.45, Math.min(1.35, player.pitch - e.movementY * 0.0022));
});
addEventListener('wheel', e => {
  if (overhead) orbDist = Math.max(HALF * 1.5, Math.min(HALF * 6, orbDist * (1 + Math.sign(e.deltaY) * 0.09)));
}, { passive: true });
addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

const _rt = new THREE.Vector3(), _wish = new THREE.Vector3();
const _n3 = new THREE.Vector3(), _oldN = new THREE.Vector3();
const _qr = new THREE.Quaternion();
const faceNormal = (face, out) => {
  const n = FACES[face].n; return out.set(n[0], n[1], n[2]);
};

function movePlayer(dt) {
  faceNormal(player.face, _n3);
  player.up.copy(_n3);
  // keep the heading tangent to the face actually underfoot
  player.fwd.addScaledVector(_n3, -player.fwd.dot(_n3));
  if (player.fwd.lengthSq() < 1e-8) {
    const u = FACES[player.face].u; player.fwd.set(u[0], u[1], u[2]);
  }
  player.fwd.normalize();
  _rt.crossVectors(player.fwd, _n3).normalize();

  _wish.set(0, 0, 0);
  if (keys['KeyW']) _wish.add(player.fwd);
  if (keys['KeyS']) _wish.sub(player.fwd);
  if (keys['KeyD']) _wish.add(_rt);
  if (keys['KeyA']) _wish.sub(_rt);
  if (_wish.lengthSq() > 0) _wish.normalize();
  const speed = keys['ShiftLeft'] ? 11 : 6.2;

  // gravity points at the face you are on, so "down" is a different world
  // direction depending on where you are standing
  if (keys['Space'] && player.onGround) { player.vy = 6.4; player.onGround = false; }
  player.vy -= 19 * dt;
  player.h += player.vy * dt;
  if (player.h <= 0) { player.h = 0; player.vy = 0; player.onGround = true; }

  player.pos.addScaledVector(_wish, speed * dt);

  // WALKING OFF AN EDGE. Two passes, because a corner crosses two edges in a
  // single frame at a run. The heading is carried across by the rotation that
  // takes the old normal onto the new one — a projection cannot do it: walk
  // straight off an edge and your forward direction IS the new face's normal,
  // which projects to nothing.
  for (let pass = 0; pass < 2; pass++) {
    const f = FACES[player.face];
    const a = player.pos.dot(_rt.set(f.u[0], f.u[1], f.u[2]));
    const b = player.pos.dot(_rt.set(f.v[0], f.v[1], f.v[2]));
    let over = null;
    if (a > HALF) over = f.u;
    else if (a < -HALF) over = _ng(f.u);
    else if (b > HALF) over = f.v;
    else if (b < -HALF) over = _ng(f.v);
    if (!over) break;
    let nf = -1;
    for (let k = 0; k < 6; k++) if (_eqv(FACES[k].n, over)) { nf = k; break; }
    if (nf < 0) break;
    _oldN.copy(player.up);
    faceNormal(nf, _n3);
    _qr.setFromUnitVectors(_oldN, _n3);
    player.fwd.applyQuaternion(_qr).normalize();
    player.face = nf;
    player.up.copy(_n3);
    player.h = 0; player.vy = 0; player.onGround = true;
    // RE-SEAT IMMEDIATELY, not after the loop (2026-09-07). Left until the
    // end, the second pass read a position that was still measured against
    // the OLD face: standing eye-height above the top face reads as 1.68m
    // off the side face's edge, so the player crossed straight back and the
    // net effect was a wall you could not walk over. The two passes exist for
    // corners; they only mean anything once each one lands.
    seatPlayer();
  }
  seatPlayer();
}

// Sit exactly eye-height (plus any jump) above the current face, inside its
// square. This is the only place the player's world position is written from
// face coordinates, which is why crossing an edge is a change of two numbers
// rather than a special case for each of the twelve edges.
function seatPlayer() {
  const f = FACES[player.face];
  const lim = HALF - 0.05;
  const a = Math.max(-lim, Math.min(lim,
    player.pos.x * f.u[0] + player.pos.y * f.u[1] + player.pos.z * f.u[2]));
  const b = Math.max(-lim, Math.min(lim,
    player.pos.x * f.v[0] + player.pos.y * f.v[1] + player.pos.z * f.v[2]));
  const up = HALF + EYE + player.h;
  player.pos.set(f.n[0] * up + f.u[0] * a + f.v[0] * b,
                 f.n[1] * up + f.u[1] * a + f.v[1] * b,
                 f.n[2] * up + f.u[2] * a + f.v[2] * b);
}

// ── a starter line, so the loop is legible the moment it loads ─────────────
// Called again after every meltdown: a prestige that drops you onto an empty
// cube with no line running is indistinguishable from having lost.
function seedLine(placePlayer) {
  // Pick a node with a CLEAR run east of it. The first version just took the
  // first node it found and drew six tiles east regardless — a second node
  // sitting in that line silently refused two placements, so the demo line
  // ended in mid-air with no hub and delivered nothing. A starter line that
  // does not complete the loop teaches the player the wrong thing.
  // On the top face, so the game opens on the orientation people expect —
  // the other five are discovered by walking there.
  const RUN = 6, F = 0;
  let found = null;
  for (let i = 2; i < N - RUN - 1 && !found; i++) {
    for (let j = 2; j < N - 2 && !found; j++) {
      if (cells[F][i][j].t !== NODE) continue;
      let clear = true;
      for (let k = 1; k <= RUN && clear; k++) clear = cells[F][i + k][j].t === EMPTY;
      if (clear) found = [i, j];
    }
  }
  if (!found) return;
  const x = found[0], z = found[1];
  place(F, x, z, MINER, 0);
  place(F, x + 1, z, BELT, 0);
  place(F, x + 2, z, BELT, 0);
  place(F, x + 3, z, SMELTER, 0);     // two crystals in, one ingot out
  place(F, x + 4, z, BELT, 0);
  place(F, x + 5, z, BELT, 0);
  place(F, x + RUN, z, HUB, 0);

  // STAND WHERE THE LOOP IS (2026-09-07). A fixed spawn on the south edge left
  // the whole starter line behind the player on a large grid: the game was
  // running perfectly and the first frame showed bare ground. Put the camera
  // just south of the middle of the line, looking along it, so the first thing
  // anyone sees — player or screenshot gate — is ore actually moving.
  // BEHIND the line, not past the edge. The top face's v axis is -Z, so the
  // tile "in front of" the player is j+1; standing at j+4 put the spawn four
  // tiles PAST the line and, on a line near the far edge, off the face
  // entirely — where the clamp pinned it and W did nothing at all.
  const w = tileWorld(F, x + RUN / 2, Math.max(1, Math.min(N - 2, z - 4)));
  player.pos.set(w[0], HALF + EYE, w[2]);
  player.face = F;
  player.up.set(0, 1, 0);
  camUp.set(0, 1, 0);
  // FACES[0].v is -Z, so the line we just built lies that way
  if (!placePlayer) return;
  player.fwd.set(0, 0, -1);
}
seedLine(true);

// ── the meltdown itself ────────────────────────────────────────────────────
// The machines are not deleted, they are THROWN. Every build group is detached
// from its tile, given an outward velocity off the cube and a tumble, and left
// to shrink into nothing over a couple of seconds. The engine side of this
// project has shipped physics-driven destruction before; here it is two lines
// of integration per frame, and it is the only moment in the game that is
// worth filming.
const debris = [];
let melting = 0;

function meltdown() {
  if (ore < MELT_MIN || melting > 0) return;
  const won = Math.max(1, coresFor(runValue));
  cores += won;

  eachTile((c, f, i, j) => {
    if (c.build) {
      const g = c.build;
      const p = g.position;
      const r = Math.max(1e-3, Math.hypot(p.x, p.y, p.z));
      debris.push({
        o: g,
        // SLOW ENOUGH TO WATCH (2026-09-07). The first pass threw everything at
        // 9-25 m/s and the entire factory was out of frame inside 300ms — the
        // one moment in the game worth filming, over before a screenshot could
        // catch it. Pieces now arc out and fall back toward the cube.
        v: new THREE.Vector3(
          p.x / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4,
          p.y / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4,
          p.z / r * (5 + Math.random() * 6) + (Math.random() - 0.5) * 4),
        w: new THREE.Vector3((Math.random() - 0.5) * 9,
                             (Math.random() - 0.5) * 9,
                             (Math.random() - 0.5) * 9),
      });
      c.build = null;
    }
    // a node outlives the factory built on it, exactly as it does for ERASE
    c.t = c.mesh ? NODE : EMPTY;
    c.item = 0; c.buf = 0; c.bt = 0; c.fa = 0; c.fb = 0; c.cook = 0; c.rr = 0;
  });

  ore = 0; ingots = 0; runValue = 0;
  for (const k in UPGRADES) UPGRADES[k].lvl = 0;
  applyUpgrades();
  renderUpgrades();
  items.count = 0;
  melting = 2.4;
  refreshCounts();
  document.getElementById('tok').textContent = cores;
}

function stepDebris(dt) {
  for (let k = debris.length - 1; k >= 0; k--) {
    const d = debris[k];
    // the worldlet still pulls: pieces arc out and come back, which reads as
    // a collapse rather than as a scene being deleted
    const p = d.o.position;
    const r = Math.max(1e-3, Math.hypot(p.x, p.y, p.z));
    d.v.addScaledVector(_bx.set(p.x / r, p.y / r, p.z / r), -7 * dt);
    p.addScaledVector(d.v, dt);
    d.o.rotateX(d.w.x * dt); d.o.rotateY(d.w.y * dt); d.o.rotateZ(d.w.z * dt);
    const sc = Math.max(0, d.o.scale.x - dt * 0.42);
    d.o.scale.setScalar(sc);
    if (sc <= 0.02) { scene.remove(d.o); debris.splice(k, 1); }
  }
}

{
  const btn = document.getElementById('melt');
  if (btn) btn.addEventListener('pointerdown', ev => { ev.stopPropagation(); meltdown(); });
}

{
  const h = document.querySelector('#hud h1');
  if (h) h.textContent = (SPEC.title || 'FACTORY').toUpperCase();
}
applyUpgrades();
renderUpgrades();

// ── frame ──────────────────────────────────────────────────────────────────
let last = performance.now();
renderer.setAnimationLoop(() => {
  const now = performance.now();
  const dt = Math.min(0.1, (now - last) / 1000);
  last = now;

  if (melting > 0) {
    melting = Math.max(0, melting - dt);
    // the replacement line arrives when the old one has finished falling, not
    // while it is still in the air — otherwise the collapse and the rebuild
    // are the same frame and neither reads
    if (melting === 0) { seedLine(false); refreshCounts(); }
  }
  stepDebris(dt);

  sinceTick += dt;
  rateWindow += dt;
  const before = ore;
  // the tick stops while the factory is still in the air — a meltdown that
  // kept banking value would read as though nothing had been given up
  while (sinceTick >= TICK) { sinceTick -= TICK; if (!melting) step(); }
  minedWindow += ore - before;
  if (rateWindow >= 1) {
    // AVERAGE OVER LONGER THAN THE SLOWEST MACHINE (2026-09-06). This sampled
    // a one-second window, and a smelter emits once every three ticks — 1.26s.
    // So the readout sat at 0 for whole seconds while value was visibly
    // climbing, which reads as a broken game rather than as a bursty one. In
    // a genre whose entire hook is watching a number go up, the number has to
    // be trustworthy. Six one-second buckets, reported as their sum.
    rateBuckets.push(minedWindow / rateWindow);
    if (rateBuckets.length > 6) rateBuckets.shift();
    const perSec = rateBuckets.reduce((a, b) => a + b, 0) / rateBuckets.length;
    document.getElementById('rate').textContent = Math.round(perSec * 60);
    minedWindow = 0;
    rateWindow = 0;
  }
  document.getElementById('ore').textContent = ore;
  document.getElementById('ingot').textContent = ingots;
  document.getElementById('alloy').textContent = alloys;
  // the buttons light up the moment you can afford them — the whole point of
  // the number climbing is watching it cross a threshold
  if (Math.floor(ore) !== lastOreShown) { lastOreShown = Math.floor(ore); renderUpgrades(); }
  document.getElementById('melt').classList.toggle('on', ore >= MELT_MIN && !melting);
  document.getElementById('nitem').textContent = drawItems(sinceTick / TICK);

  // a crystal on the west face spins about the west face's up
  scene.traverse(o => {
    if (!o.userData.spin) return;
    const ax = o.userData.axis;
    if (ax) o.rotateOnAxis(_bx.set(0, 1, 0), dt * o.userData.spin);
    else o.rotation.y += dt * o.userData.spin;
  });

  if (overhead) {
    camera.position.set(
      Math.sin(orbYaw) * Math.cos(orbPitch) * orbDist,
      Math.sin(orbPitch) * orbDist,
      Math.cos(orbYaw) * Math.cos(orbPitch) * orbDist);
    camera.lookAt(0, 0, 0);
    // fog is tuned for standing ON the surface; from an orbit it erases the
    // whole worldlet, which is the one view that has to read at a glance
    scene.fog = null;
    ghost.visible = false;
  } else {
    if (!scene.fog) scene.fog = worldFog;
    movePlayer(dt);
    camera.position.copy(player.pos);
    // Built from a basis, not from Euler angles: there is no global "up" left
    // to write a yaw against once the player can be standing on the underside
    // of the world. camUp trails the true up so an edge crossing rolls.
    camUp.lerp(player.up, Math.min(1, dt * 7)).normalize();
    _bz.copy(player.fwd).addScaledVector(camUp, -player.fwd.dot(camUp));
    if (_bz.lengthSq() < 1e-8) _bz.copy(player.fwd);
    _bz.normalize();
    _bx.crossVectors(_bz, camUp).normalize();     // right
    _by.crossVectors(_bx, _bz).normalize();       // orthonormal up
    _mx.makeBasis(_bx, _by, _bz.negate());        // a camera looks down -Z
    camera.quaternion.setFromRotationMatrix(_mx);
    camera.rotateX(player.pitch);
    updateGhost();
  }
  document.body.classList.toggle('overhead', overhead);
  renderer.render(scene, camera);
});

// The shot gate, the scene audit and the brief check all talk to window.__game.
// A second genre that invented its own interface would need a second gate, and
// then only one of them would stay honest.
window.__game = {
  ready: true,
  pos: () => player.pos.toArray(),
  keys: {},
  stats: () => ({ calls: renderer.info.render.calls,
                  tris: renderer.info.render.triangles,
                  programs: renderer.info.programs ? renderer.info.programs.length : -1,
                  textures: renderer.info.memory.textures,
                  geometries: renderer.info.memory.geometries }),
  facts: () => ({
    genre: 'factory',
    style: SPEC.style || 'default',
    grid: N,
    nodes: NODE_COUNT,
    value: ore,
    ingots,
    machines: (() => { let n = 0;
      eachTile(c => { if (c.t !== EMPTY && c.t !== NODE) n++; });
      return n; })(),
    items_on_belts: items.count,
    alloys,
    minerals: MINERAL_OF_FACE.map(m => MINERAL_NAME[m]),
    cores,
    run_value: +runValue.toFixed(1),
    melting: +melting.toFixed(2),
    debris: debris.length,
    faces: 6,
    player_face: FACES[player.face].name,
    player_up: player.up.toArray().map(v => +v.toFixed(2)),
    player_y: +player.pos.y.toFixed(2),
  }),
};
window.__scene = scene;
window.__renderer = renderer;
window.__camera = camera;

window.__factory = {
  cells, items, N, T, player, HALF, FACES,
  stepTile, tileWorld, faceOfPoint,
  TYPES: { EMPTY, MINER, BELT, HUB, NODE, SMELTER, SPLITTER, FORGE,
           CRYSTAL, EMBER, SALT, INGOT, ALLOY },
  MINERAL_OF_FACE, get alloys() { return alloys; },
  UPGRADES, buy, costOf, get tick() { return TICK; },
  meltdown, MELT_MIN, get cores() { return cores; },
  addValue: n => { ore += n; },
  get ingots() { return ingots; },
  get ore() { return ore; },
  place, removeAt,
  camPos: () => camera.position.toArray(),
  ghostVisible: () => ghost.visible,
};
